#!/usr/bin/env python3
"""Phase 0.5d feasibility proof — generate an AppInspect-shaped Splunk app.

Reads a UC JSON sidecar and emits a minimal Splunk app under
``build/poc/SplunkAppForComplianceUseCases/`` containing:

* ``default/app.conf`` and ``app.manifest`` (2.0.0 schema)
* ``default/savedsearches.conf`` with one compliance saved search
* ``default/data/ui/views/compliance_overview.xml`` — trivial Simple XML
* ``default/data/ui/nav/default.xml`` — navigation stanza
* ``metadata/default.meta`` — explicit, auditable export rules
* ``README.md`` — what this is, plus the exact AppInspect / SLIM commands

The goal is NOT to produce a production-shippable app (that is Phase 2+).
The goal is to prove that, given a conformant JSON sidecar, we can
deterministically emit a directory tree that already passes a lint-level
check for AppInspect and that a reviewer can run ``splunk-appinspect``
against later.

Run:
    .venv-feasibility/bin/python scripts/feasibility/splunk_app_poc.py

Exit 0 on success, 2 on missing input.
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import re
import shutil
import sys
import xml.etree.ElementTree as ET

REPO = pathlib.Path(__file__).resolve().parents[2]
EXEMPLAR = REPO / "use-cases" / "cat-22" / "uc-22.35.1.json"
APP_ID = "SplunkAppForComplianceUseCases"
APP_ROOT = REPO / "build" / "poc" / APP_ID
APP_VERSION = "0.1.0-alpha"


def stanza_name(uc: dict) -> str:
    uc_full_id = f"UC-{uc['id']}"
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", uc["title"]).strip("_")
    return f"{uc_full_id} — {slug[:80]}"


def write_app_conf(target: pathlib.Path, uc_count: int) -> None:
    target.write_text(
        "[install]\n"
        "is_configured = 0\n"
        "state = enabled\n"
        "build = 1\n"
        "\n"
        "[ui]\n"
        "is_visible = true\n"
        "label = Splunk Monitoring Use Cases — Compliance (POC)\n"
        "\n"
        "[launcher]\n"
        "author = Splunk Monitoring Use Cases contributors\n"
        "description = Phase 0.5d feasibility proof: an AppInspect-shaped Splunk app "
        f"containing {uc_count} compliance use case(s) generated from JSON sidecars. "
        "This is not a production distribution.\n"
        f"version = {APP_VERSION}\n"
        "\n"
        "[package]\n"
        f"id = {APP_ID}\n"
        "check_for_updates = false\n",
        encoding="utf-8",
    )


def write_manifest(target: pathlib.Path, uc_count: int) -> None:
    manifest = {
        "schemaVersion": "2.0.0",
        "info": {
            "title": "Splunk Monitoring Use Cases — Compliance (POC)",
            "id": {
                "group": None,
                "name": APP_ID,
                "version": APP_VERSION,
            },
            "author": [
                {
                    "name": "Splunk Monitoring Use Cases contributors",
                    "email": None,
                    "company": None,
                }
            ],
            "releaseDate": None,
            "description": (
                f"Phase 0.5d feasibility proof containing {uc_count} compliance use case(s) "
                "generated from JSON sidecars under use-cases/cat-22/."
            ),
            "classification": {
                "intendedAudience": "Compliance, audit, security engineering",
                "categories": ["Security", "IT Operations"],
                "developmentStatus": "Development",
            },
            "commonInformationModels": None,
            "license": {
                "name": "MIT",
                "text": "../LICENSE",
                "uri": "https://github.com/fenre/splunk-monitoring-use-cases/blob/main/LICENSE",
            },
            "privacyPolicy": {"name": None, "text": None, "uri": None},
            "releaseNotes": {
                "name": None,
                "text": "README.md",
                "uri": "https://github.com/fenre/splunk-monitoring-use-cases/blob/main/CHANGELOG.md",
            },
        },
        "dependencies": None,
        "tasks": None,
        "inputGroups": None,
        "incompatibleApps": None,
        "platformRequirements": {"splunk": {"Enterprise": "*"}},
        "targetWorkloads": ["_search_heads"],
    }
    target.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def spl_as_conf_line(spl: str) -> str:
    """Fold multi-line SPL into a savedsearches.conf-safe continuation block."""
    lines = [line.rstrip() for line in spl.strip().splitlines()]
    if len(lines) == 1:
        return lines[0]
    joined = " \\\n".join(lines)
    return joined


def write_savedsearches(target: pathlib.Path, ucs: list[dict]) -> None:
    body = [
        "# -------------------------------------------------------------------",
        "# GENERATED by scripts/feasibility/splunk_app_poc.py — DO NOT EDIT.",
        "# Source of truth: use-cases/cat-22/*.json (UC JSON sidecars).",
        "# -------------------------------------------------------------------",
        "",
    ]
    for uc in ucs:
        uc_full_id = f"UC-{uc['id']}"
        stanza = stanza_name(uc)
        title_clean = re.sub(r"[\[\]]", "", uc["title"])
        description = (
            f"{title_clean} ({uc_full_id}, criticality: {uc.get('criticality', 'unknown')}). "
            "Phase 0.5d feasibility POC; see README.md for AppInspect verification."
        )
        compliance_tags = ", ".join(
            sorted({entry["regulation"] for entry in uc.get("compliance", [])})
        )
        body.extend(
            [
                f"[{stanza}]",
                f"description = {description}",
                f"search = {spl_as_conf_line(uc['spl'])}",
                "cron_schedule = */5 * * * *",
                "dispatch.earliest_time = -30m@m",
                "dispatch.latest_time = now",
                "enableSched = 0",
                "is_scheduled = 0",
                "disabled = 1",
                "run_n_times = 0",
                "alert.severity = 4",
                "alert_condition = search count > 0",
                "alert.track = 1",
                "alert.suppress = 0",
                "action.email = 0",
                "action.summary_index = 0",
                f"# Compliance tags: {compliance_tags}",
                f"# Upstream reference: https://github.com/fenre/splunk-monitoring-use-cases/blob/main/use-cases/cat-22/uc-{uc['id']}.json",
                "",
            ]
        )
    target.write_text("\n".join(body), encoding="utf-8")


def write_nav(target: pathlib.Path) -> None:
    nav = ET.Element("nav", attrib={"search_view": "search"})
    ET.SubElement(nav, "view", attrib={"name": "compliance_overview", "default": "true"})
    ET.SubElement(nav, "view", attrib={"name": "search"})
    target.write_bytes(
        b'<?xml version="1.0" encoding="UTF-8"?>\n'
        + ET.tostring(nav, encoding="utf-8")
        + b"\n"
    )


def write_view(target: pathlib.Path, uc: dict) -> None:
    uc_full_id = f"UC-{uc['id']}"
    view_xml = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<dashboard version="1.1">\n'
        f"  <label>{uc_full_id} — compliance overview (POC)</label>\n"
        f"  <description>Feasibility-spike dashboard. The search is disabled by default; this XML is shape-checked only.</description>\n"
        "  <row>\n"
        "    <panel>\n"
        f"      <title>{uc_full_id}</title>\n"
        "      <table>\n"
        "        <search>\n"
        f"          <query>| makeresults count=1 | eval uc=\"{uc_full_id}\" | table uc</query>\n"
        "          <earliest>-15m</earliest>\n"
        "          <latest>now</latest>\n"
        "        </search>\n"
        "      </table>\n"
        "    </panel>\n"
        "  </row>\n"
        "</dashboard>\n"
    )
    target.write_text(view_xml, encoding="utf-8")


def write_meta(target: pathlib.Path) -> None:
    target.write_text(
        "# Phase 0.5d feasibility POC — explicit export rules so an auditor can\n"
        "# see at a glance which knowledge objects are app-scoped vs system-scoped.\n"
        "[]\n"
        "access = read : [ * ], write : [ admin, power ]\n"
        "export = app\n"
        "\n"
        "[savedsearches]\n"
        "export = none\n",
        encoding="utf-8",
    )


def write_readme(target: pathlib.Path, ucs: list[dict]) -> None:
    lines = [
        f"# {APP_ID} — Phase 0.5d feasibility proof",
        "",
        "This directory is **generated**, not hand-authored.",
        "",
        "It exists only to prove, during Phase 0 of the regulatory-gold-standard",
        "work, that a JSON-first UC sidecar (see `use-cases/cat-22/uc-22.35.1.json`)",
        "can be rendered into an AppInspect-shaped Splunk app deterministically.",
        "",
        "## Contents",
        "",
        "```",
        f"{APP_ID}/",
        "├── default/",
        "│   ├── app.conf",
        "│   ├── savedsearches.conf",
        "│   └── data/",
        "│       └── ui/",
        "│           ├── nav/default.xml",
        "│           └── views/compliance_overview.xml",
        "├── metadata/",
        "│   └── default.meta",
        "├── app.manifest",
        "└── README.md",
        "```",
        "",
        "## Use cases included",
        "",
    ]
    for uc in ucs:
        uc_full_id = f"UC-{uc['id']}"
        lines.append(f"* **{uc_full_id}** — {uc['title']}")
    lines.extend(
        [
            "",
            "## Verification commands",
            "",
            "The following commands are **not** executed by the feasibility harness ",
            "(that would require installing AppInspect and SLIM, which live behind ",
            "Splunk login). They document what a reviewer would run in Phase 1:",
            "",
            "```bash",
            "# 1. Package the app",
            f"slim package {APP_ROOT.relative_to(REPO)}",
            "",
            "# 2. Validate against AppInspect",
            f"splunk-appinspect inspect \\",
            f"  --mode precert \\",
            f"  --included-tags cloud \\",
            f"  {APP_ROOT.relative_to(REPO)}",
            "",
            "# 3. Lint savedsearches.conf",
            f"btool check --app={APP_ID}",
            "```",
            "",
            "## What this POC does NOT do",
            "",
            "* Sign the package (Phase 2).",
            "* Include any real alerts, ES notables, or lookup tables.",
            "* Contain actionable compliance evidence — the search is disabled by ",
            "  default and the dashboard is a stub.",
            "",
            "## Regenerating",
            "",
            "```bash",
            ".venv-feasibility/bin/python scripts/feasibility/splunk_app_poc.py",
            "```",
            "",
            "Exit 0 means the tree was (re)written cleanly.",
            "",
            "## Provenance",
            "",
            f"Generator : `scripts/feasibility/splunk_app_poc.py`",
            f"Exemplar UC : `use-cases/cat-22/uc-22.35.1.json`",
            f"POC version : `{APP_VERSION}`",
            "",
        ]
    )
    target.write_text("\n".join(lines), encoding="utf-8")


def build_app(exemplar_path: pathlib.Path) -> list[pathlib.Path]:
    if not exemplar_path.exists():
        sys.stderr.write(f"ERROR: exemplar UC not found: {exemplar_path}\n")
        raise SystemExit(2)

    uc = json.loads(exemplar_path.read_text(encoding="utf-8"))
    ucs = [uc]

    if APP_ROOT.exists():
        shutil.rmtree(APP_ROOT)
    default_dir = APP_ROOT / "default"
    views_dir = default_dir / "data" / "ui" / "views"
    nav_dir = default_dir / "data" / "ui" / "nav"
    meta_dir = APP_ROOT / "metadata"
    for d in (default_dir, views_dir, nav_dir, meta_dir):
        d.mkdir(parents=True, exist_ok=True)

    write_app_conf(default_dir / "app.conf", len(ucs))
    write_manifest(APP_ROOT / "app.manifest", len(ucs))
    write_savedsearches(default_dir / "savedsearches.conf", ucs)
    write_nav(nav_dir / "default.xml")
    write_view(views_dir / "compliance_overview.xml", uc)
    write_meta(meta_dir / "default.meta")
    write_readme(APP_ROOT / "README.md", ucs)

    files = sorted(
        p for p in APP_ROOT.rglob("*") if p.is_file()
    )
    return files


def shape_check(files: list[pathlib.Path]) -> list[str]:
    """Minimal static checks that AppInspect will otherwise catch."""
    errors: list[str] = []
    required = {
        APP_ROOT / "default" / "app.conf",
        APP_ROOT / "default" / "savedsearches.conf",
        APP_ROOT / "default" / "data" / "ui" / "nav" / "default.xml",
        APP_ROOT / "default" / "data" / "ui" / "views" / "compliance_overview.xml",
        APP_ROOT / "metadata" / "default.meta",
        APP_ROOT / "app.manifest",
        APP_ROOT / "README.md",
    }
    present = set(files)
    for req in required:
        if req not in present:
            errors.append(f"missing required file: {req.relative_to(REPO)}")

    manifest_path = APP_ROOT / "app.manifest"
    if manifest_path in present:
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            if manifest.get("schemaVersion") != "2.0.0":
                errors.append("app.manifest schemaVersion must be 2.0.0")
            info = manifest.get("info", {})
            if info.get("id", {}).get("name") != APP_ID:
                errors.append(f"app.manifest info.id.name must be {APP_ID}")
        except json.JSONDecodeError as exc:
            errors.append(f"app.manifest not valid JSON: {exc}")

    nav_path = APP_ROOT / "default" / "data" / "ui" / "nav" / "default.xml"
    if nav_path in present:
        try:
            ET.parse(nav_path)
        except ET.ParseError as exc:
            errors.append(f"nav/default.xml not valid XML: {exc}")

    view_path = APP_ROOT / "default" / "data" / "ui" / "views" / "compliance_overview.xml"
    if view_path in present:
        try:
            ET.parse(view_path)
        except ET.ParseError as exc:
            errors.append(f"views/compliance_overview.xml not valid XML: {exc}")

    return errors


def main() -> int:
    files = build_app(EXEMPLAR)
    errors = shape_check(files)
    if errors:
        for err in errors:
            sys.stderr.write(f"FAIL: {err}\n")
        return 1

    contents_hash = hashlib.sha256()
    for path in files:
        rel = path.relative_to(APP_ROOT).as_posix().encode("utf-8")
        contents_hash.update(rel + b"\0" + path.read_bytes() + b"\0")

    print(
        f"PASS: generated {len(files)} file(s) under {APP_ROOT.relative_to(REPO)}\n"
        f"      sha256 (tree) : {contents_hash.hexdigest()}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
