[package]
id = imucl
check_for_updates = 0

[ui]
label = Infrastructure & Security Use Case Library
is_visible = 1
show_in_launcher = 1

[launcher]
author = Splunk Monitoring Use Case Repository
description = Use Case Library built with Splunk UI Toolkit (React). Browse categories and use cases.
version = 0.0.1

[install]
build = 1
is_configured = 1
