.PHONY: build serve clean audit audit-full audit-ntv audit-all audit-structure \
       audit-cim audit-links audit-consistency audit-perf audit-placeholders \
       audit-mitre audit-gold audit-spl-duplicates audit-spl-grammar audit-ids \
       audit-spl-hallucinations audit-splunk-cloud-compat \
       audit-monitoring-type audit-roadmap export-roadmap audit-license-inventory \
       write-license-inventory audit-metrics-snapshot snapshot-metrics \
       audit-regulation-alignment audit-nis2-no-gap audit-oscal \
       audit-regulatory-change-watch \
       audit-compliance-gaps audit-compliance-mappings \
       audit-doc-counts audit-openapi-drift audit-content-quality \
       audit-baseline-clause-grammar-free audit-peer-review-signoffs \
       audit-mcp-tool-schemas \
       stewardship-digest audit-reproducibility audit-reproducibility-fast \
       baseline \
       generate-md-from-json generate-grandma-explanations \
       generate-stewardship-digest generate-mapping-ledger \
       generate-manifest-samples generate-equipment-tags \
       generate-evidence-packs generate-api-surface \
       generate-phase2-mini-categories generate-phase2-3-per-regulation \
       generate-phase3-1-backfill generate-phase3-2-cross-cutting \
       generate-phase3-3-derivatives \
       generate-backlinks generate-doc-references \
       check-source-links audit-auto-gen-provenance \
       splunk-uc splunk-uc-help \
       inventory manifest test test-unit help

PYTHON ?= python3
BUILD  := $(PYTHON) tools/build/build.py --out dist
DIST   := dist

# P6 (scripts taxonomy, 2026-05-09): the dispatcher lives under
# src/splunk_uc/. Until the package is editable-installed, we put
# src/ on PYTHONPATH on demand. Both ``python3 -m splunk_uc <verb>``
# and the legacy ``python3 scripts/<name>.py`` shims work; this
# variable is the canonical way Makefile targets reach the new CLI.
SPLUNK_UC := PYTHONPATH=src $(PYTHON) -m splunk_uc

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'

build: ## Build the full site into dist/
	$(BUILD)

serve: build ## Build then serve locally on port 8000
	cd $(DIST) && $(PYTHON) -m http.server 8000

clean: ## Remove dist/ and build artefacts
	rm -rf $(DIST)

# --- Audits (quick) ---

audit: audit-structure audit-cim audit-consistency ## Run core audit checks

# --- Audits (comprehensive) ---

audit-full: audit audit-placeholders audit-mitre audit-spl-duplicates audit-spl-grammar audit-ids audit-monitoring-type ## Run ALL audit checks

audit-structure: ## Audit UC JSON structure (content/cat-*/UC-*.json)
	$(SPLUNK_UC) audit-uc-structure --full

audit-cim: ## Audit CIM ↔ SPL alignment
	$(SPLUNK_UC) audit-cim-spl-alignment

audit-links: ## Check HTTP(S) URLs in UC references (network required)
	$(SPLUNK_UC) audit-links

audit-consistency: ## Audit repo consistency (enrichment, INDEX, HTML)
	$(SPLUNK_UC) audit-repo-consistency

audit-perf: ## Performance + accessibility budget check
	$(SPLUNK_UC) audit-perf-a11y

audit-placeholders: ## Detect placeholder/scaffolded content
	$(SPLUNK_UC) audit-placeholders

audit-mitre: ## Validate MITRE ATT&CK taxonomy
	$(SPLUNK_UC) audit-mitre-taxonomy

audit-gold: ## Gold standard quality profile audit
	$(SPLUNK_UC) audit-gold-profile

audit-ntv:
	$(SPLUNK_UC) audit-non-technical-sync

audit-all: audit audit-ntv audit-gold
	@echo "All audit checks passed"

audit-spl-duplicates: ## Find duplicate SPL queries across UCs
	$(SPLUNK_UC) audit-spl-duplicates

audit-spl-grammar: ## Check SPL grammar issues
	$(SPLUNK_UC) audit-spl-grammar

audit-spl-hallucinations: ## Detect SPL hallucinations (unknown commands, bad CIM datasets)
	$(SPLUNK_UC) audit-spl-hallucinations

audit-splunk-cloud-compat: ## Audit SPL + content packs for Splunk Cloud compatibility
	$(SPLUNK_UC) audit-splunk-cloud-compat

generate-backlinks: ## Refresh docs/backlinks.md (wiki "What links here" index)
	$(PYTHON) scripts/generate_backlinks.py

generate-doc-references: ## Refresh APA-style References footer + inline `[N]` markers on every doc
	$(PYTHON) scripts/generate_doc_references.py

check-source-links: ## HTTP-probe every URL in the bibliographic database (network required)
	$(PYTHON) scripts/check_source_links.py

audit-auto-gen-provenance: ## Verify every auto-generated doc carries a 'Generated by ...' banner
	$(PYTHON) scripts/audit_auto_gen_provenance.py --check

audit-ids: ## Validate UC IDs (duplicates, ordering, category match)
	$(SPLUNK_UC) audit-uc-ids

audit-monitoring-type: ## Validate monitoringType values and MITRE consistency
	$(SPLUNK_UC) audit-monitoring-type

audit-regulation-alignment: ## Lint compliance[].regulation against data/regulations.json
	$(SPLUNK_UC) audit-regulation-alignment

audit-nis2-no-gap: ## Validate the NIS2 no-gap obligation matrix and per-UC traceability
	$(SPLUNK_UC) audit-nis2-no-gap

audit-oscal: ## NIST OSCAL component-definition schema + canonical-byte gate
	$(SPLUNK_UC) audit-oscal-roundtrip --check

audit-regulatory-change-watch: ## Hermetic regulatory change-watch ledger audit (no network)
	$(SPLUNK_UC) audit-regulatory-change-watch --check

audit-compliance-gaps: ## Per-regulation clause-level gap analysis (--check ensures no drift)
	$(SPLUNK_UC) audit-compliance-gaps --check

audit-compliance-mappings: ## Validate compliance[] mappings + golden tuple gate + coverage metrics
	$(SPLUNK_UC) audit-compliance-mappings

audit-doc-counts: ## Cross-check numeric claims (UC counts) in AGENTS.md and docs/ vs actual content
	$(SPLUNK_UC) audit-doc-counts

audit-openapi-drift: ## Flag dist/api/ paths missing from openapi.yaml / api/v1/openapi.yaml
	$(SPLUNK_UC) audit-openapi-drift

audit-content-quality: ## Flag description==value, jargon in grandmaExplanation, broken fixtureRefs
	$(SPLUNK_UC) audit-content-quality

audit-baseline-clause-grammar-free: ## Refuse `clause-grammar` fingerprints in audit-baseline.json
	$(SPLUNK_UC) audit-baseline-clause-grammar-free

audit-peer-review-signoffs: ## Phase 4.5a peer-review gate (schema + semantic invariants)
	$(SPLUNK_UC) audit-peer-review-signoffs

audit-mcp-tool-schemas: ## Drift guard: MCP tool surface vs api/v1/* + outputSchema runtime probes
	$(SPLUNK_UC) audit-mcp-tool-schemas

audit-gold-profile-v2: ## Gold-standard v2 audit (SPL provenance, KFP, suppressions)
	$(SPLUNK_UC) audit-gold-profile-v2

audit-prerequisites: ## Validate UC prerequisite graph (cycles, unknown IDs, wave monotonicity)
	$(SPLUNK_UC) audit-prerequisites --check

audit-sandbox-validation: ## Audit sample-data/ fixture coverage and shape vs UC controlTest blocks
	$(SPLUNK_UC) audit-sandbox-validation --check

audit-sme-review-signoffs: ## Validate data/provenance/sme-signoffs.json (schema + cross-references)
	$(SPLUNK_UC) audit-sme-review-signoffs

audit-mapping-ledger: ## Validate data/provenance/mapping-ledger.json (schema + hash chain + integrity)
	$(SPLUNK_UC) audit-mapping-ledger

audit-roadmap: ## Validate ROADMAP.md structure + repo-relative links
	$(SPLUNK_UC) audit-roadmap-consistency --check

export-roadmap: ## Emit a Project-board JSON snapshot of ROADMAP.md
	$(SPLUNK_UC) audit-roadmap-consistency --export reports/roadmap-export.json

audit-license-inventory: ## Validate dependency licenses against allowlist
	$(SPLUNK_UC) audit-license-inventory --check

write-license-inventory: ## Regenerate data/license-inventory.json baseline
	$(SPLUNK_UC) audit-license-inventory --write

audit-metrics-snapshot: ## Ensure release-time metrics snapshot exists
	$(PYTHON) scripts/snapshot_metrics.py --check

snapshot-metrics: ## Write data/metrics-history/<VERSION>.json from dist/metrics.json
	$(PYTHON) scripts/snapshot_metrics.py --write

baseline: ## Capture data/baselines/v<VERSION>.json (size/timing snapshot)
	$(PYTHON) tools/capture_baselines.py

stewardship-digest: ## Generate dist/stewardship-digest.{json,md}
	$(SPLUNK_UC) generate-stewardship-digest

generate-md-from-json: ## Render UC-X.Y.Z.md companions from JSON SSOT
	$(SPLUNK_UC) generate-md-from-json

generate-grandma-explanations: ## Fill missing plain-language `grandmaExplanation` fields
	$(SPLUNK_UC) generate-grandma-explanations

generate-stewardship-digest: ## Alias for stewardship-digest (dispatcher verb name)
	$(SPLUNK_UC) generate-stewardship-digest

generate-mapping-ledger: ## Regenerate data/provenance/mapping-ledger.json
	$(SPLUNK_UC) generate-mapping-ledger

generate-manifest-samples: ## Replay samples/manifest.json fixtures through HEC
	$(SPLUNK_UC) generate-manifest-samples

generate-equipment-tags: ## Backfill UC sidecar equipment[]/equipmentModels[] tags
	$(SPLUNK_UC) generate-equipment-tags

generate-evidence-packs: ## Build per-regulation evidence packs
	$(SPLUNK_UC) generate-evidence-packs

generate-api-surface: ## Regenerate api/v1/* static JSON surface
	$(SPLUNK_UC) generate-api-surface

generate-phase2-mini-categories: ## Phase 2.2 generator (cat-22.35-22.49 mini-category UCs)
	$(SPLUNK_UC) generate-phase2-mini-categories

generate-phase2-3-per-regulation: ## Phase 2.3 generator (per-regulation content fills)
	$(SPLUNK_UC) generate-phase2-3-per-regulation

generate-phase3-1-backfill: ## Phase 3.1 generator (clause-level backfill on cat-22)
	$(SPLUNK_UC) generate-phase3-1-backfill

generate-phase3-2-cross-cutting: ## Phase 3.2 generator (cross-cutting compliance tags)
	$(SPLUNK_UC) generate-phase3-2-cross-cutting

generate-phase3-3-derivatives: ## Phase 3.3 generator (derivative-regulation propagation)
	$(SPLUNK_UC) generate-phase3-3-derivatives

audit-reproducibility: ## Two consecutive --reproducible builds must match (~90s)
	$(SPLUNK_UC) audit-reproducibility

audit-reproducibility-fast: ## Single --reproducible build smoke (~30s)
	$(SPLUNK_UC) audit-reproducibility --first-build-only

# --- splunk_uc dispatcher (P6) ---

splunk-uc: ## Show the splunk_uc CLI help (alias for `splunk-uc-help`)
	@$(SPLUNK_UC) --help

splunk-uc-help: ## Show the splunk_uc CLI help
	@$(SPLUNK_UC) --help

# --- Data generation ---

inventory: ## Regenerate data/inventory/ucs.json + ucs.csv
	$(SPLUNK_UC) inventory-ucs --stats

manifest: ## Regenerate eventgen_data/manifest-all.json
	$(PYTHON) scripts/parse_uc_catalog.py --check --output eventgen_data/manifest-all.json

# --- Tests ---

test: test-unit build ## Run unit tests + build validation
	@echo "Build succeeded — $(DIST)/ is up to date."
	@test -f $(DIST)/api/catalog-index.json || (echo "FAIL: catalog-index.json missing" && exit 1)
	@echo "All checks passed."

test-unit: ## Run pytest unit tests for tools/build
	$(PYTHON) -m pytest tests/build/ -v
