"""Pick a category for the weekly P14 stewardship-rotation reminder.

Repo-overhaul plan §P14 (2026-05-17 follow-on): the per-category
CODEOWNERS rows (PR #35, 2026-05-13) and the per-category scorecard
drill-downs (commit ``00729f198``, 2026-05-14) established the
*structure* of per-category stewardship. This verb closes the
*cadence* half by deterministically rotating across the 23 categories
once per ISO week, so each category receives a focused stewardship
ping roughly twice a year (52 weeks / 23 categories ≈ 2.3
reminders per category per year).

The verb is invoked by ``.github/workflows/stewardship-rotation.yml``
which runs every Monday at 08:30 UTC (just after the
``stewardship.yml`` digest at 08:00). It is also invocable manually
(``--week N``) for testing or for one-off catch-ups.

What this verb does
-------------------

1. Compute the target ISO week (or read it from ``--week``).
2. Map the week to a category number via ``cat_num = (iso_week % 23) + 1``.
   This gives a stable, deterministic, gap-free rotation that does
   not depend on calendar boundaries — week 1 of 2026 picks cat 2,
   week 23 of 2026 picks cat 1, week 1 of 2027 picks cat 2 again, etc.
3. Read the canonical category slug from the matching
   ``content/cat-NN-<slug>/`` directory name (single source of truth
   for the slug; mirrors how ``test_codeowners.py`` derives it).
4. Look up the category's CODEOWNERS owner list from
   ``.github/CODEOWNERS`` — every ``@``-prefixed token after the
   matching ``/content/cat-NN-<slug>/`` line.
5. Read the category's composite score, grade, and dimension
   breakdown from ``dist/scorecard.json`` (already generated by
   ``make build`` upstream in the workflow).
6. Emit two outputs:
   * structured JSON (always to stdout) for any downstream tool that
     wants the raw decision data
   * optional issue-body markdown (``--write-issue-body PATH``) for
     ``gh issue create --body-file`` in the workflow

The workflow then uses the rendered markdown to open or comment on a
GitHub issue tagged with a per-week label so each rotation pick is
idempotent (re-running the workflow for the same week updates the
existing issue rather than creating a duplicate).

This module is stdlib-only — no jsonschema, no requests, no
dependencies beyond Python's standard library — because the
workflow runs it before any extras would be installed.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
from pathlib import Path
from typing import Any

# Number of categories in the rotation. Matches the 23 top-level
# categories under ``content/cat-NN-<slug>/`` today. The verb asserts
# this against the actual directory count at runtime so adding a
# category 24 is a single one-line constant update.
EXPECTED_CATEGORY_COUNT = 23

# The repo root resolved relative to this file:
#   src/splunk_uc/tools/pick_rotation_category.py
#   → parents[3] = repo root
REPO_ROOT = Path(__file__).resolve().parents[3]

CONTENT_DIR = REPO_ROOT / "content"
CODEOWNERS_PATH = REPO_ROOT / ".github" / "CODEOWNERS"
SCORECARD_PATH = REPO_ROOT / "dist" / "scorecard.json"

# Mirrors ``tests/build/test_codeowners.py::CAT_DIR_RE``. Locked here
# so the two surfaces validate against the same regex.
CAT_DIR_RE = re.compile(r"^cat-(\d{2})-([a-z0-9-]+)$")

# Capture every ``@``-prefixed token on a CODEOWNERS line. CODEOWNERS
# allows multiple owners per row (space-separated), so a single
# pattern with ``findall`` is the cleanest read.
OWNER_TOKEN_RE = re.compile(r"@[A-Za-z0-9][A-Za-z0-9._/-]*")


def _category_directories() -> list[tuple[int, str]]:
    """Return ``[(cat_num, slug), ...]`` sorted by ``cat_num`` ascending.

    ``cat_num`` is the integer parsed from the ``NN`` portion of
    ``cat-NN-<slug>`` (1..23 today, no zero-padding in the integer
    form). ``slug`` is the full directory name (``cat-NN-<slug>``)
    because that's the canonical token used by CODEOWNERS rows and
    by scorecard.md anchors — keeping it as one token avoids a
    class of off-by-one slug-construction bugs.
    """
    out: list[tuple[int, str]] = []
    if not CONTENT_DIR.is_dir():
        raise SystemExit(f"content directory missing: {CONTENT_DIR}")
    for path in sorted(CONTENT_DIR.iterdir()):
        if not path.is_dir():
            continue
        m = CAT_DIR_RE.match(path.name)
        if m is None:
            continue
        out.append((int(m.group(1)), path.name))
    if not out:
        raise SystemExit(
            f"no cat-NN-<slug>/ directories found under {CONTENT_DIR} — "
            "the content tree appears empty or has been reorganised; "
            "this is a sanity-check abort"
        )
    return out


def _codeowners_owners_for(slug: str, codeowners_text: str) -> list[str]:
    """Return the GitHub @-owners assigned to ``/content/<slug>/`` in CODEOWNERS.

    ``slug`` is the full directory name (``cat-NN-<short>``). Returns
    an empty list if no matching row is found; the caller decides
    whether that's a hard failure or a soft warning. We deliberately
    do not raise here so the picker can still produce a usable
    rotation record even if CODEOWNERS lags behind a newly added
    category — the workflow will surface the empty owner list as a
    "no @-mention" notice in the issue body.
    """
    pattern = rf"^/content/{re.escape(slug)}/\s+(.+?)\s*$"
    match = re.search(pattern, codeowners_text, flags=re.MULTILINE)
    if match is None:
        return []
    return OWNER_TOKEN_RE.findall(match.group(1))


def _grade_url_suffix(slug: str) -> str:
    """Return the scorecard drill-down anchor for ``slug``.

    The scorecard's section IDs match ``slug`` exactly (see
    ``docs/scorecard.md`` and the CODEOWNERS comment block above the
    per-category rows). Returning the anchor as the ``#frag`` part
    lets the workflow assemble the full URL from a repo + branch
    base, keeping this verb deployment-environment-agnostic.
    """
    return f"docs/scorecard.md#{slug}"


def _load_scorecard() -> dict[str, Any]:
    """Load ``dist/scorecard.json`` and return its parsed top-level dict.

    Raises ``SystemExit`` with a useful message if the file is
    missing — the workflow's ``make build`` step must have run
    successfully before this verb is invoked. Reproducible builds
    keep scorecard.json deterministic, so a stale file is rare in
    practice, but the workflow always rebuilds upstream so the
    verb sees fresh data.
    """
    if not SCORECARD_PATH.is_file():
        raise SystemExit(
            f"scorecard JSON missing at {SCORECARD_PATH}; "
            "ensure ``make build`` ran successfully before invoking "
            "``pick-rotation-category``"
        )
    with SCORECARD_PATH.open(encoding="utf-8") as fh:
        loaded = json.load(fh)
    if not isinstance(loaded, dict):
        raise SystemExit(
            f"scorecard.json at {SCORECARD_PATH} is not a JSON object "
            f"(got {type(loaded).__name__}); the scorecard generator "
            "is expected to emit a top-level object with a "
            "'categories' array — re-run ``make build``"
        )
    return loaded


def _scorecard_entry_for(cat_num: int, scorecard: dict[str, Any]) -> dict[str, Any]:
    """Find the scorecard entry whose ``cat_num`` matches.

    scorecard.json stores ``cat_num`` as a *string* (``"1"`` through
    ``"23"``); we normalise to int comparison so callers can pass an
    int from the rotation logic without worrying about that detail.
    """
    categories = scorecard.get("categories", [])
    for entry in categories:
        if not isinstance(entry, dict):
            continue
        if int(entry.get("cat_num", -1)) == cat_num:
            # Narrow the dict to the verb's expected shape via cast-via-comprehension.
            return {str(k): v for k, v in entry.items()}
    raise SystemExit(
        f"scorecard.json has no entry for cat_num={cat_num}; "
        "scorecard.json may be stale relative to content/ — re-run ``make build``"
    )


def _rotation_index(iso_week: int) -> int:
    """Map an ISO week number to a 0-based category index.

    Rotation is ``iso_week % EXPECTED_CATEGORY_COUNT``. Caveats:

    * ISO week numbers are 1..52 (or 53), so ``week % 23`` cycles
      through 1..22 in the first 22 weeks of any year, then 0, then
      1..22, then 0, etc. To make this readable we shift to a 0-based
      index here and add 1 at the call site to derive ``cat_num``.
    * The "first week of the year picks cat 2" surprise (week 1 % 23
      = 1 → cat 2, not cat 1) is intentional: it keeps the math
      uniform with the rest of the year and avoids special-casing
      week 1. Year-to-year continuity is preserved because the rotation
      cycle (23 weeks) and the year length (52/53 weeks) are coprime,
      so every category gets a fair share over a long horizon.
    """
    return iso_week % EXPECTED_CATEGORY_COUNT


def _build_record(
    *,
    iso_year: int,
    iso_week: int,
    cat_num: int,
    slug: str,
    owners: list[str],
    scorecard_entry: dict[str, Any],
) -> dict[str, Any]:
    """Assemble the structured JSON record emitted by this verb."""
    dimensions = {
        "content_depth": scorecard_entry.get("content_depth"),
        "references_pct": scorecard_entry.get("references_pct"),
        "kfp_pct": scorecard_entry.get("kfp_pct"),
        "mitre_pct": scorecard_entry.get("mitre_pct"),
        "freshness_score": scorecard_entry.get("freshness_score"),
        "freshness_median_days": scorecard_entry.get("freshness_median_days"),
        "provenance_authority": scorecard_entry.get("provenance_authority"),
        "samples_pct": scorecard_entry.get("samples_pct"),
    }
    return {
        "iso_year": iso_year,
        "iso_week": iso_week,
        "rotation_index": _rotation_index(iso_week),
        "cat_num": cat_num,
        "slug": slug,
        "name": scorecard_entry.get("name", "(unknown)"),
        "composite": scorecard_entry.get("composite"),
        "grade": scorecard_entry.get("grade"),
        "uc_count": scorecard_entry.get("uc_count"),
        "security_count": scorecard_entry.get("security_count"),
        "owners": owners,
        "drilldown": _grade_url_suffix(slug),
        "codeowners_row": f"/content/{slug}/",
        "content_dir": f"content/{slug}/",
        "dimensions": dimensions,
        "depth_tier_distribution": scorecard_entry.get("depth_tier_distribution", {}),
        "status_distribution": scorecard_entry.get("status_distribution", {}),
        "origin_distribution": scorecard_entry.get("origin_distribution", {}),
    }


def _format_dimensions_table(dimensions: dict[str, Any]) -> str:
    """Render the dimensions dict as a markdown table mirroring scorecard.md."""
    rows = [
        ("Content depth", dimensions.get("content_depth"), "20%"),
        ("References", dimensions.get("references_pct"), "20%", "%"),
        ("Provenance authority", dimensions.get("provenance_authority"), "20%"),
        ("Freshness", dimensions.get("freshness_score"), "15%"),
        ("Known false positives", dimensions.get("kfp_pct"), "10%", "%"),
        ("MITRE ATT&CK coverage", dimensions.get("mitre_pct"), "8%", "%"),
        ("Sample fixtures", dimensions.get("samples_pct"), "7%", "%"),
    ]
    out: list[str] = ["| Dimension | Score | Weight |", "| --------- | ----- | ------ |"]
    for row in rows:
        name, score, weight = row[0], row[1], row[2]
        suffix = row[3] if len(row) > 3 else ""
        score_str = "n/a" if score is None else f"{float(score):.1f}{suffix}"
        out.append(f"| {name} | {score_str} | {weight} |")
    return "\n".join(out)


def _format_distribution(label: str, distribution: dict[str, Any]) -> str:
    """Render a single distribution dict as one summary line."""
    if not distribution:
        return f"**{label}:** _none recorded_"
    parts = [f"{k} {v}" for k, v in sorted(distribution.items(), key=lambda kv: -int(kv[1]))]
    return f"**{label}:** " + " · ".join(parts)


def _render_issue_body(record: dict[str, Any], *, repo_url_base: str) -> str:
    """Render the human-facing markdown body for the GitHub issue.

    ``repo_url_base`` is the absolute base URL for the repository on
    the default branch (e.g.
    ``https://github.com/fenre/splunk-monitoring-use-cases/blob/main``)
    so the issue body's drill-down link is clickable from the GitHub
    issue UI without depending on a relative-path interpretation.
    """
    owners_line = (
        " ".join(record["owners"])
        if record["owners"]
        else "_(no CODEOWNERS owner found — add a `/content/`-prefixed row in `.github/CODEOWNERS`)_"
    )
    composite = record["composite"]
    composite_str = "n/a" if composite is None else f"{float(composite):.1f}"
    grade = record["grade"] or "(no grade)"
    cat_num = record["cat_num"]
    name = record["name"]
    drilldown_url = f"{repo_url_base.rstrip('/')}/{record['drilldown']}"
    content_url = f"{repo_url_base.rstrip('/')}/{record['content_dir']}"

    lines = [
        f"## Category {cat_num}: {name} — **{grade}** ({composite_str})",
        "",
        f"This week's stewardship-rotation pick (ISO {record['iso_year']}-W{record['iso_week']:02d}).",
        "",
        f"**Owners:** {owners_line}",
        "",
        f"- **Volume:** {record['uc_count']} UCs ({record['security_count']} security)",
        f"- **Content directory:** [`{record['content_dir']}`]({content_url})",
        f"- **CODEOWNERS row:** `{record['codeowners_row']}`",
        f"- **Scorecard drill-down:** [`{record['drilldown']}`]({drilldown_url})",
        "",
        "### Current dimension scores",
        "",
        _format_dimensions_table(record["dimensions"]),
        "",
        _format_distribution("Depth tiers", record["depth_tier_distribution"]),
        " ",
        _format_distribution("Status mix", record["status_distribution"]),
        " ",
        _format_distribution("Provenance origins", record["origin_distribution"]),
        "",
        "### Suggested stewardship review",
        "",
        "Use the drill-down above to spot the dimensions where this category is weakest, then triage:",
        "",
        "1. **Freshness:** any UC whose `last_modified` is older than 180 days — does the SPL still parse against current Splunk? Are the data sources still recommended?",
        "2. **References:** any UC missing a `references[]` entry? Run `python -m splunk_uc audit-uc-structure --only <UC-ID>` to confirm.",
        "3. **MITRE ATT&CK coverage** (if `pillar` is `security` or `both`): are the tagged techniques still current per the latest MITRE ATT&CK matrix?",
        "4. **Provenance authority:** any UC whose `origin` is `unclassified` or `contributor` — can it be promoted to `splunk-official` / `vendor-official` with a citation?",
        "5. **`grandmaExplanation`:** for any newly added UC, run `python -m splunk_uc generate-grandma-explanations --only <UC-ID>` and review the generated copy.",
        "",
        "Close this issue when the review is complete (or when the next rotation pick lands and supersedes it). The same category will be re-picked roughly every 23 weeks.",
        "",
        "---",
        "",
        "_Auto-generated by `.github/workflows/stewardship-rotation.yml` via `python -m splunk_uc pick-rotation-category`._",
    ]
    return "\n".join(lines) + "\n"


def _iso_week_today(reference_date: dt.date | None = None) -> tuple[int, int]:
    """Return ``(iso_year, iso_week)`` for ``reference_date`` (default: today UTC)."""
    d = reference_date or dt.datetime.now(dt.UTC).date()
    iso = d.isocalendar()
    return (iso.year, iso.week)


def _parse_argv(argv: list[str] | None) -> argparse.Namespace:
    """Parse command-line arguments. Public for testability."""
    parser = argparse.ArgumentParser(
        prog="splunk_uc pick-rotation-category",
        description=(
            "Pick the category for this week's P14 stewardship-rotation "
            "reminder. Maps ISO week → category number via "
            "(iso_week %% 23) + 1; emits structured JSON to stdout and "
            "optionally renders the GitHub-issue markdown body."
        ),
    )
    parser.add_argument(
        "--week",
        type=int,
        default=None,
        metavar="ISO_WEEK",
        help=(
            "Override the ISO week (1..53). Default: this week (UTC). "
            "Combine with --year to pick a specific (year, week) pair "
            "for testing or catch-up runs."
        ),
    )
    parser.add_argument(
        "--year",
        type=int,
        default=None,
        metavar="ISO_YEAR",
        help="Override the ISO year. Default: current ISO year (UTC).",
    )
    parser.add_argument(
        "--write-issue-body",
        type=Path,
        default=None,
        metavar="PATH",
        help=(
            "Write the rendered GitHub-issue markdown body to PATH. "
            "If omitted, only the JSON record is emitted (to stdout)."
        ),
    )
    parser.add_argument(
        "--repo-url-base",
        type=str,
        default="https://github.com/fenre/splunk-monitoring-use-cases/blob/main",
        metavar="URL",
        help=(
            "Base URL for repository links rendered in the issue body. "
            "Should point at the repo root on the default branch."
        ),
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Dispatcher entry-point. See module docstring for the contract."""
    args = _parse_argv(argv)

    # Resolve target ISO week.
    if args.week is None or args.year is None:
        cur_year, cur_week = _iso_week_today()
        iso_year = args.year if args.year is not None else cur_year
        iso_week = args.week if args.week is not None else cur_week
    else:
        iso_year, iso_week = args.year, args.week

    # Defense-in-depth: reject obviously broken inputs early.
    if not (1 <= iso_week <= 53):
        print(
            f"--week must be in [1, 53]; got {iso_week}",
            file=sys.stderr,
        )
        return 2

    # Resolve the rotation.
    categories = _category_directories()
    if len(categories) != EXPECTED_CATEGORY_COUNT:
        print(
            f"warning: found {len(categories)} category directories under "
            f"content/, expected {EXPECTED_CATEGORY_COUNT}. Update "
            "EXPECTED_CATEGORY_COUNT in pick_rotation_category.py.",
            file=sys.stderr,
        )

    rotation_idx = _rotation_index(iso_week)
    # Categories are 1-indexed; the rotation index is 0-based modulo
    # category-count, so the picked category at index ``rotation_idx``
    # in the sorted ``categories`` list is the one to ping.
    if rotation_idx >= len(categories):
        # Defensive guard for the edge case where the actual category
        # count is below 23 (e.g. a category was removed and the
        # EXPECTED_CATEGORY_COUNT constant has not yet been updated).
        rotation_idx = rotation_idx % len(categories)
    picked_cat_num, picked_slug = categories[rotation_idx]

    # Look up the rest of the record.
    codeowners_text = CODEOWNERS_PATH.read_text(encoding="utf-8")
    owners = _codeowners_owners_for(picked_slug, codeowners_text)
    scorecard = _load_scorecard()
    scorecard_entry = _scorecard_entry_for(picked_cat_num, scorecard)
    record = _build_record(
        iso_year=iso_year,
        iso_week=iso_week,
        cat_num=picked_cat_num,
        slug=picked_slug,
        owners=owners,
        scorecard_entry=scorecard_entry,
    )

    # Always emit JSON on stdout so the workflow (or any other caller)
    # can capture the structured decision data.
    print(json.dumps(record, indent=2, sort_keys=True))

    # Optionally write the rendered issue body.
    if args.write_issue_body is not None:
        body = _render_issue_body(record, repo_url_base=args.repo_url_base)
        args.write_issue_body.parent.mkdir(parents=True, exist_ok=True)
        args.write_issue_body.write_text(body, encoding="utf-8")
        print(
            f"issue body ({len(body)} chars) written to {args.write_issue_body}",
            file=sys.stderr,
        )

    return 0


if __name__ == "__main__":  # pragma: no cover -- thin shim
    raise SystemExit(main())
