#!/usr/bin/env node
/**
 * Phase 3a headless smoke test.
 *
 * Stands up a minimal window/document shim, loads catalog.json for
 * globals, then loads src/scripts/01-state.js,
 * src/scripts/02-filters.js and src/scripts/04-panel.js in the same
 * order as index.html concatenates them, then exercises the three
 * behaviours Phase 3a introduced:
 *
 *   1) __recomputeCachedFacets() populates _cachedClausesByReg with
 *      one entry per regulation that has at least one cmp row.
 *   2) currentRegulationFilter + currentClauseFilter together narrow
 *      getFilteredUCs() to the exact (reg, version, clause) subset.
 *   3) panelHTML() emits the <table class="uc-compliance-table"> block
 *      for a UC that carries a cmp array.
 *
 * The script exits 0 on success, 1 on any assertion failure, and
 * never touches the network. We deliberately stub out only the
 * globals these three scripts actually touch — full DOM rendering is
 * out of scope for a smoke test.
 */
"use strict";

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = path.resolve(__dirname, "..", "..");

function readSrc(relPath) {
  return fs.readFileSync(path.join(ROOT, relPath), "utf8");
}

function assert(ok, msg) {
  if (!ok) {
    console.error("FAIL:", msg);
    process.exit(1);
  }
  console.log("ok   -", msg);
}

// Minimal document shim — just enough for the loaded scripts to
// evaluate without ReferenceError. We capture writes to
// ``document.getElementById('detail-pane').innerHTML`` so we can
// assert on the HTML that ``fillDetailPane`` produced.
const stubElements = {
  "detail-pane": { innerHTML: "" },
  "panel-body": { innerHTML: "" },
  "panel-id": { textContent: "" },
  "panel-title": { textContent: "" },
};
const stubDocument = {
  getElementById: (id) => stubElements[id] || null,
  querySelector: () => null,
  querySelectorAll: () => [],
  addEventListener: () => {},
  body: { classList: { add: () => {}, remove: () => {}, toggle: () => {} } },
  documentElement: { classList: { add: () => {}, remove: () => {} } },
  createElement: () => ({
    style: {},
    classList: { add: () => {}, remove: () => {}, contains: () => false },
    appendChild: () => {},
    setAttribute: () => {},
  }),
  createEvent: () => ({ initEvent: () => {} }),
};

const sandbox = {
  console,
  Date,
  JSON,
  Math,
  Promise,
  Set,
  Map,
  Error,
  setTimeout,
  clearTimeout,
  setInterval,
  clearInterval,
  URL,
  encodeURIComponent,
  decodeURIComponent,
  // Scripts occasionally probe localStorage — fail-open is fine for
  // this smoke test; the scripts already wrap those reads in try/catch.
  localStorage: {
    getItem: () => null,
    setItem: () => {},
    removeItem: () => {},
    clear: () => {},
  },
  document: stubDocument,
  addEventListener: () => {},
  dispatchEvent: () => {},
  CustomEvent: function () {},
  Event: function () {},
  location: { hash: "", pathname: "/", search: "", href: "http://localhost/" },
  history: { replaceState: () => {}, pushState: () => {} },
  navigator: { userAgent: "phase3a-smoke" },
  // Globals the smoke does NOT need (provenance/custom-text) but that
  // 02-filters.js defensively reads — ship empty defaults so the
  // guarded reads evaluate to falsy without throwing.
  UC_CUSTOM_TEXT: {},
  UC_PROVENANCE: {},
};
sandbox.window = sandbox;
sandbox.globalThis = sandbox;

vm.createContext(sandbox);

// Populate window globals from catalog.json (same structure as the
// API loader builds at runtime from catalog-index.json).
//
// v8.2.0 retired the legacy root-level ``catalog.json`` (commit
// faffd68e4); the SSOT-derived copy lives under ``dist/catalog.json``
// instead, generated by ``python3 tools/build/build.py --out dist``.
// We probe both locations so this smoke test stays runnable
// regardless of the build order in CI or locally — without forcing a
// 30-second build inside the test itself.
const candidatePaths = [
  path.join(ROOT, "dist", "catalog.json"),
  path.join(ROOT, "catalog.json"),
];
const catalogPath = candidatePaths.find((p) => fs.existsSync(p));
if (!catalogPath) {
  throw new Error(
    "Phase 3a smoke test cannot find catalog.json. Tried:\n" +
      candidatePaths.map((p) => "  - " + p).join("\n") +
      "\nRun `python3 tools/build/build.py --out dist` first."
  );
}
const catalog = JSON.parse(fs.readFileSync(catalogPath, "utf-8"));
sandbox.DATA = catalog.DATA || [];
sandbox.window.DATA = sandbox.DATA;
sandbox.EQUIPMENT = catalog.EQUIPMENT || [];
sandbox.window.EQUIPMENT = sandbox.EQUIPMENT;
sandbox.CAT_META = catalog.CAT_META || {};
sandbox.window.CAT_META = sandbox.CAT_META;
sandbox.CAT_GROUPS = catalog.CAT_GROUPS || {};
sandbox.window.CAT_GROUPS = sandbox.CAT_GROUPS;
sandbox.FILTER_FACETS = catalog.FILTER_FACETS || {};
sandbox.window.FILTER_FACETS = sandbox.FILTER_FACETS;

// Load SPA script chunks in bundle order. We skip chunks that pull in
// non-trivial DOM APIs we haven't stubbed — for Phase 3a only the
// state/filters/panel chunks matter.
const scripts = [
  "src/scripts/01-state.js",
  "src/scripts/02-filters.js",
  "src/scripts/04-panel.js",
];

for (const rel of scripts) {
  const src = readSrc(rel);
  try {
    vm.runInContext(src, sandbox, { filename: rel });
  } catch (err) {
    console.error("Failed to load " + rel + ":", err.message);
    process.exit(1);
  }
}

// __bootstrapCatalogState runs inside 00-loader in production.
assert(
  typeof sandbox.__bootstrapCatalogState === "function",
  "01-state.js exports __bootstrapCatalogState()",
);
sandbox.__bootstrapCatalogState();

// Debug: quickly inspect how many cmp rows the bootstrap actually saw.
let totalUCs = 0;
let withCmp = 0;
(sandbox.DATA || []).forEach((cat) => {
  (cat.s || []).forEach((sc) => {
    (sc.u || []).forEach((uc) => {
      totalUCs++;
      if (Array.isArray(uc.cmp) && uc.cmp.length > 0) withCmp++;
    });
  });
});
console.log("debug: totalUCs=" + totalUCs + " withCmp=" + withCmp);

// ---------------------------------------------------------------
// Assertion 1 — cached clause facets
// ---------------------------------------------------------------
const clausesByReg = sandbox._cachedClausesByReg || {};
const regKeys = Object.keys(clausesByReg);
assert(
  regKeys.length > 0,
  "_cachedClausesByReg has at least one regulation",
);
assert(
  regKeys.length >= 10,
  "expect >=10 regulations with clause-level cmp data (got " + regKeys.length + ")",
);

// Canonical form should be "{version}#{clause}". A single version
// should only appear once per clause.
const pickOne = regKeys[0];
const sample = clausesByReg[pickOne];
assert(
  Array.isArray(sample) && sample.length > 0,
  "clauses[" + pickOne + "] is a non-empty array",
);
assert(
  sample.every((s) => typeof s === "string" && s.includes("#")),
  "every clause option is canonical {version}#{clause} form",
);

// ---------------------------------------------------------------
// Assertion 2 — reg + clause filter narrows results
// ---------------------------------------------------------------
// Pick GDPR Art.5 if available (most authoritative test fixture);
// otherwise fall back to the first reg with >=2 UCs under a single
// clause so we can prove the filter is actually cutting results.
function candidatePairs() {
  const out = [];
  for (const reg of regKeys) {
    for (const canonical of clausesByReg[reg]) {
      out.push([reg, canonical]);
    }
  }
  return out;
}

let testReg = null;
let testClause = null;
const allPairs = candidatePairs();
for (const [reg, clause] of allPairs) {
  if (reg.toUpperCase().includes("GDPR") && clause.toUpperCase().includes("ART.5")) {
    testReg = reg;
    testClause = clause;
    break;
  }
}
if (!testReg) {
  testReg = allPairs[0][0];
  testClause = allPairs[0][1];
}

// Baseline — reg only.
sandbox.currentRegulationFilter = testReg;
sandbox.currentClauseFilter = "all";
const regOnly = sandbox.getFilteredUCs();
assert(regOnly.length > 0, "regulation-only filter returns non-empty set");

// Narrowed — reg + clause.
sandbox.currentClauseFilter = testClause;
const narrowed = sandbox.getFilteredUCs();
assert(
  narrowed.length > 0 && narrowed.length <= regOnly.length,
  "clause filter narrows to <= regulation-only count (reg=" +
    regOnly.length + " narrowed=" + narrowed.length + ")",
);

// Every narrowed UC must carry a cmp row matching (reg, version, clause).
const hashIdx = testClause.indexOf("#");
const wantVer = testClause.slice(0, hashIdx);
const wantCl = testClause.slice(hashIdx + 1);
const mismatch = narrowed.find((e) => {
  const cmp = Array.isArray(e.uc.cmp) ? e.uc.cmp : [];
  return !cmp.some((r) => r && r.r === testReg && r.v === wantVer && r.cl === wantCl);
});
assert(
  !mismatch,
  "every narrowed UC has a matching cmp row for " + testReg + " / " + testClause,
);

// ---------------------------------------------------------------
// Assertion 3 — fillDetailPane renders the clause table
// ---------------------------------------------------------------
// fillDetailPane writes into document.getElementById('detail-pane').
// innerHTML. We stub detail-pane up front and inspect the string
// after the function returns. Pick a narrowed entry that does NOT
// have ``uc.z`` (visualization) so we don't need to stub
// ntVizMockups from 03-render.js.
assert(
  typeof sandbox.fillDetailPane === "function",
  "04-panel.js exports fillDetailPane()",
);
const renderEntry = narrowed.find((e) => !e.uc.z) || narrowed[0];
sandbox.fillDetailPane(renderEntry);
const renderedHtml = stubElements["detail-pane"].innerHTML;
assert(
  typeof renderedHtml === "string" && renderedHtml.length > 0,
  "fillDetailPane() populates detail-pane innerHTML",
);
assert(
  renderedHtml.includes("uc-compliance-table"),
  "panel HTML includes the uc-compliance-table block",
);
assert(
  renderedHtml.includes("Compliance clauses"),
  "panel HTML includes the 'Compliance clauses' heading",
);
assert(
  renderedHtml.includes("filterByClauseEnc("),
  "panel HTML wires clause-filter buttons via filterByClauseEnc",
);
// Cross-check: the escape function would turn section markers into
// entities, so search for the regulation name raw or entity-escaped.
const regNameEscaped = testReg.replace(/[&<>"']/g, function (c) {
  return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
});
assert(
  renderedHtml.includes(regNameEscaped) || renderedHtml.includes(testReg),
  "panel HTML includes the selected regulation name (" + testReg + ")",
);

console.log("\nAll Phase 3a smoke assertions passed.");
process.exit(0);
