/**
 * DSA Mapping Tables — shared between the main catalog and the DSA tool.
 *
 * EQUIPMENT_GROUPS:   UI grouping for the equipment inventory, shared by both tools.
 * DSA_EQUIPMENT_MAP:  equipment_id (from EQUIPMENT in data.js) → [dsa_source_ids]
 * DSA_UC_MAP:         use_case_id (e.g. "5.2.1") → [dsa_source_ids]
 *
 * These are derived from ot-data-sources.js and should be updated when
 * that file changes.
 */

window.EQUIPMENT_GROUPS = [
  { name: 'Servers & OS', ids: ['linux','windows','macos'] },
  { name: 'Virtualization', ids: ['vmware','hyperv','proxmox','ovirt','openstack','nutanix','vxrail'] },
  { name: 'Cloud & Containers', ids: ['aws','azure','gcp','kubernetes','docker','argocd'] },
  { name: 'Networking & Security Appliances', ids: ['cisco','paloalto','fortinet','f5','citrix','checkpoint','nsx','infoblox','netflow','snmp','syslog','zscaler','netskope','cloudflare','guardicore','broadcom_symantec','forcepoint','sonicwall'] },
  { name: 'Cisco Security & Observability', ids: ['cisco_duo','cisco_umbrella','cisco_secure_endpoint','cisco_secure_access','cisco_email_security','cisco_web_security','cisco_secure_network_analytics','cisco_xdr','cisco_appdynamics','cisco_cyber_vision','cisco_edge_intelligence','cisco_ind'] },
  { name: 'Web & Application Servers', ids: ['apache','nginx','iis','haproxy','traefik','tomcat','jboss','phpfpm','varnish','squid','memcached','envoy'] },
  { name: 'Databases', ids: ['db_connect','mssql','oracle','postgresql','mysql','mongodb','redis','elasticsearch','clickhouse','cassandra','snowflake'] },
  { name: 'Messaging & Middleware', ids: ['kafka','rabbitmq','activemq','zookeeper'] },
  { name: 'Identity & Access', ids: ['okta','cyberark','beyondtrust','m365','exchange','sharepoint'] },
  { name: 'Security Tools', ids: ['security_essentials','crowdstrike','defender','tenable','qualys','proofpoint','suricata','claroty','dragos','nozomi'] },
  { name: 'DevOps & CI/CD', ids: ['jenkins','github','gitlab','ansible','controlm'] },
  { name: 'Splunk Products', ids: ['itsi','stream','opentelemetry','prometheus','grafana','log_pipeline','edge_hub'] },
  { name: 'ITSM & Collaboration', ids: ['servicenow','jira','pagerduty'] },
  { name: 'OT Vendor Systems', ids: ['siemens','rockwell','schneider','abb','honeywell','emerson','ge_vernova','yokogawa','aveva','fanuc','kuka','beckhoff','phoenix_contact','wago','copa_data','ignition','vtscada','tridium','jci_metasys','ibm_maximo','sap_pm'] },
  { name: 'OT Systems & Equipment', ids: ['scada_hmi','dcs','historian','mes','plc_rtu','safety_system','energy_meter','vibration_sensor','bacnet_devices'] },
  { name: 'OT / IoT Protocols', ids: ['modbus','opcua','mqtt','dnp3','iec104','iec61850','profinet','ethernetip','ethercat','s7comm','mtconnect','profibus','hart','knx','lorawan','zigbee','coap','aranet','asterisk'] },
  { name: 'Storage & Backup', ids: ['netapp','pure_storage','dell_emc','truenas','ceph','veeam','commvault'] },
  { name: 'Physical Infrastructure', ids: ['hardware_bmc','apc','cctv','hashicorp'] }
];

window.DSA_EQUIPMENT_MAP = {
  // ── Servers & OS ──
  "linux":              ["it_linux"],
  "windows":            ["it_windows", "it_windows_dc"],
  "macos":              ["it_linux"],

  // ── Virtualization ──
  "vmware":             ["it_vmware"],
  "vmware_vsphere":     ["it_vmware"],
  "vmware_esxi":        ["it_vmware"],
  "vmware_vcenter":     ["it_vmware"],
  "hyperv":             ["it_vmware"],
  "proxmox":            ["it_linux"],
  "ovirt":              ["it_linux"],
  "openstack":          ["dsa_it_cloud_iaas"],
  "nutanix":            ["it_vmware"],
  "vxrail":             ["it_vmware"],

  // ── Cloud & Containers ──
  "aws":                ["dsa_it_cloud_iaas", "dsa_it_cloud_paas"],
  "azure":              ["dsa_it_cloud_iaas", "dsa_it_cloud_paas"],
  "gcp":                ["dsa_it_cloud_iaas", "dsa_it_cloud_paas"],
  "kubernetes":         ["dsa_it_cloud_iaas"],
  "docker":             ["dsa_it_cloud_iaas"],
  "argocd":             ["dsa_it_cicd"],

  // ── Cisco (parent: empty — select specific models) ──
  "cisco":              [],
  "cisco_firepower":    ["sec_fw_cisco", "cisco_secure_firewall"],
  "cisco_asa":          ["sec_fw_cisco", "cisco_secure_firewall"],
  "cisco_ios":          ["net_switch", "net_router", "cisco_catalyst_switches", "cisco_routers"],
  "cisco_ise":          ["sec_ise", "cisco_ise", "dsa_net_nac"],
  "cisco_meraki":       ["net_meraki", "cisco_meraki_network", "cisco_meraki_sensors", "cisco_meraki_cameras"],
  "cisco_ucs":          ["cisco_intersight"],
  "cisco_intersight":   ["cisco_intersight"],
  "cisco_aci":          ["net_switch"],
  "cisco_nexus":        ["net_switch", "cisco_catalyst_switches"],
  "cisco_sdwan":        ["net_sdwan", "cisco_sdwan", "cisco_catalyst_center"],
  "cisco_wlc":          ["net_wireless", "cisco_wlc"],
  "cisco_ucm":          ["cisco_ucm"],
  "cisco_webex":        ["cisco_webex_meetings", "cisco_webex_calling", "cisco_webex_contact_center"],
  "cisco_spaces":       ["cisco_spaces"],
  "cisco_thousandeyes": ["cisco_thousandeyes"],

  // ── Palo Alto (parent + models) ──
  "paloalto":                ["sec_ngfw_paloalto"],
  "paloalto_pan_firewall":   ["sec_ngfw_paloalto"],
  "paloalto_globalprotect":  ["dsa_net_vpn"],
  "paloalto_prisma":         ["sec_ngfw_paloalto"],

  // ── Fortinet (parent + models) ──
  "fortinet":                ["sec_ngfw_fortinet"],
  "fortinet_fortigate":      ["sec_ngfw_fortinet"],
  "fortinet_fortianalyzer":  ["sec_ngfw_fortinet"],

  // ── F5 (parent + models) ──
  "f5":               ["dsa_sec_waf", "dsa_net_loadbalancer"],
  "f5_bigip":         ["dsa_net_loadbalancer"],
  "f5_asm":           ["dsa_sec_waf"],

  // ── Citrix (parent + models) ──
  "citrix":               ["dsa_net_loadbalancer"],
  "citrix_netscaler":     ["dsa_net_loadbalancer"],
  "citrix_cvad":          ["dsa_it_desktop", "dsa_it_uxm"],
  "citrix_uberagent":     ["dsa_it_uxm"],

  // ── Infoblox (parent + models) ──
  "infoblox":         ["it_dns", "it_dhcp", "dsa_net_ldap"],
  "infoblox_dns":     ["it_dns"],
  "infoblox_dhcp":    ["it_dhcp"],

  // ── NetFlow (parent + models) ──
  "netflow":          ["net_netflow"],
  "netflow_netflow":  ["net_netflow"],
  "netflow_sflow":    ["net_netflow"],

  // ── SNMP (parent + models) ──
  "snmp":             ["proto_snmp"],
  "snmp_generic":     ["proto_snmp", "dsa_net_snmp_mgmt"],
  "snmp_pdu":         ["proto_snmp"],
  "snmp_ups":         ["proto_snmp"],
  "snmp_apc":         ["proto_snmp"],

  "checkpoint":       ["sec_ngfw_paloalto"],
  "nsx":              ["net_switch"],
  "syslog":           ["it_linux", "it_windows"],
  "zscaler":          ["it_proxy"],
  "netskope":         ["it_proxy"],
  "cloudflare":       ["dsa_net_ddos", "dsa_it_webserver"],
  "guardicore":       ["dsa_sec_ndr"],
  "broadcom_symantec": ["it_proxy", "dsa_sec_dlp"],
  "forcepoint":       ["it_proxy", "dsa_sec_dlp"],
  "sonicwall":        ["sec_ngfw_fortinet"],

  // ── Web & App Servers (parent + models) ──
  "apache":           ["dsa_it_webserver"],
  "apache_httpd":     ["dsa_it_webserver"],
  "nginx":            ["dsa_it_webserver"],
  "nginx_open":       ["dsa_it_webserver"],
  "nginx_plus":       ["dsa_it_webserver"],
  "iis":              ["dsa_it_webserver"],
  "haproxy":          ["dsa_net_loadbalancer"],
  "traefik":          ["dsa_it_webserver"],
  "tomcat":           ["dsa_it_appserver"],
  "jboss":            ["dsa_it_appserver"],
  "phpfpm":           ["dsa_it_appserver"],
  "varnish":          ["dsa_it_webserver"],
  "squid":            ["it_proxy"],
  "memcached":        ["dsa_it_appserver"],
  "envoy":            ["dsa_it_webserver"],

  // ── Databases (parent + models) ──
  "db_connect":       ["dsa_it_database"],
  "mssql":            ["dsa_it_database"],
  "oracle":           ["dsa_it_database"],
  "oracle_oracle_db": ["dsa_it_database"],
  "postgresql":       ["dsa_it_database"],
  "postgresql_pg":    ["dsa_it_database"],
  "postgresql_pgbouncer": ["dsa_it_database"],
  "mysql":            ["dsa_it_database"],
  "mongodb":          ["dsa_it_database"],
  "mongodb_mongod":   ["dsa_it_database"],
  "redis":            ["dsa_it_database"],
  "elasticsearch":    ["dsa_it_database"],
  "elasticsearch_es": ["dsa_it_database"],
  "elasticsearch_opensearch": ["dsa_it_database"],
  "clickhouse":       ["dsa_it_database"],
  "cassandra":        ["dsa_it_database"],
  "snowflake":        ["dsa_it_database"],

  // ── Messaging & Middleware ──
  "kafka":            ["dsa_it_middleware"],
  "rabbitmq":         ["dsa_it_middleware", "proto_amqp"],
  "activemq":         ["dsa_it_middleware"],
  "zookeeper":        ["dsa_it_middleware"],

  // ── Identity & Access ──
  "okta":             ["dsa_it_sso"],
  "cyberark":         ["dsa_it_pam"],
  "beyondtrust":      ["dsa_it_pam"],
  "m365":             ["dsa_it_office365", "dsa_it_cloud_saas"],
  "exchange":         ["it_email"],
  "sharepoint":       ["dsa_it_office365"],

  // ── Security Tools ──
  "security_essentials": ["dsa_sec_threat_intel", "dsa_sec_uba"],
  "crowdstrike":      ["sec_edr"],
  "defender":         ["sec_edr"],
  "tenable":          ["dsa_sec_vuln_mgmt"],
  "qualys":           ["dsa_sec_vuln_mgmt"],
  "proofpoint":       ["it_email"],
  "suricata":         ["dsa_sec_ips_ids"],

  // ── DevOps & CI/CD ──
  "jenkins":          ["dsa_it_cicd"],
  "github":           ["dsa_it_cicd"],
  "gitlab":           ["dsa_it_cicd"],
  "ansible":          ["dsa_it_config_mgmt"],
  "controlm":         ["dsa_biz_batch", "dsa_biz_transaction"],

  // ── Splunk Products ──
  "itsi":             ["dsa_it_splunk_internal"],
  "stream":           ["dsa_net_dpi"],
  "opentelemetry":    ["dsa_it_apm", "dsa_biz_apm"],
  "prometheus":       ["dsa_it_apm"],
  "grafana":          ["dsa_it_apm"],
  "log_pipeline":     ["dsa_it_splunk_internal"],
  "edge_hub":         ["ot_edge_hub", "dsa_ot_file_transfer", "proto_restjson"],

  // ── ITSM & Collaboration ──
  "servicenow":       ["dsa_sec_asset_identity"],
  "jira":             ["dsa_it_cicd"],
  "pagerduty":        ["dsa_sec_soar"],

  // ── OT / IoT ──
  "modbus":           ["ot_plc_modbus", "proto_modbus"],
  "opcua":            ["ot_plc_opcua", "proto_opcua"],
  "mqtt":             ["ot_mqtt", "proto_mqtt", "proto_sparkplug"],
  "aranet":           ["ot_iot_sensor", "ot_env_sensor"],
  "asterisk":         ["dsa_it_telephone", "dsa_it_voip"],

  // ── Storage & Backup ──
  "netapp":           ["dsa_it_storage"],
  "pure_storage":     ["dsa_it_storage"],
  "dell_emc":         ["dsa_it_storage"],
  "truenas":          ["dsa_it_storage"],
  "ceph":             ["dsa_it_storage"],
  "veeam":            ["it_backup"],
  "commvault":        ["it_backup"],

  // ── Physical Infrastructure (parent + models) ──
  "hardware_bmc":             ["proto_snmp"],
  "hardware_bmc_idrac":       ["proto_snmp"],
  "hardware_bmc_ilo":         ["proto_snmp"],
  "hardware_bmc_ipmi":        ["proto_snmp"],
  "apc":                      ["proto_snmp"],
  "cctv":                     ["sec_physical"],
  "hashicorp":                ["dsa_it_config_mgmt"],
  "hashicorp_vault":          ["dsa_it_pam"],

  // ── Cisco Security & Observability ──
  "cisco_duo":                ["cisco_duo"],
  "cisco_umbrella":           ["cisco_umbrella"],
  "cisco_secure_endpoint":    ["cisco_secure_endpoint", "sec_edr", "dsa_sec_malware_sandbox"],
  "cisco_appdynamics":        ["cisco_appdynamics", "dsa_biz_transaction", "dsa_biz_ecommerce"],
  "cisco_secure_network_analytics": ["cisco_secure_network_analytics", "dsa_sec_ndr"],
  "cisco_email_security":     ["cisco_email_security", "dsa_sec_dlp"],
  "cisco_web_security":       ["cisco_web_security"],
  "cisco_xdr":                ["cisco_xdr", "dsa_sec_soar", "dsa_sec_threat_intel"],
  "cisco_secure_access":      ["cisco_secure_access"],
  "cisco_edge_intelligence":  ["cisco_edge_intelligence", "ot_cisco_ei"],
  "cisco_ind":                ["cisco_ind"],
  "cisco_cyber_vision":       ["sec_ids_cybervision", "cisco_cyber_vision"],

  // ── OT IDS Vendors ──
  "claroty":                  ["sec_ids_claroty", "dsa_ot_firewall", "dsa_ot_asset_mgmt"],
  "dragos":                   ["sec_ids_dragos", "dsa_ot_firewall"],
  "nozomi":                   ["sec_ids_nozomi", "dsa_ot_firewall"],

  // ── OT Vendor Systems ──
  "siemens":                  ["siemens_wincc", "siemens_tia_portal", "siemens_scalance", "proto_s7comm", "proto_profinet"],
  "siemens_wincc":            ["siemens_wincc"],
  "siemens_tia_portal":       ["siemens_tia_portal"],
  "siemens_scalance":         ["siemens_scalance"],
  "siemens_sinema":           ["siemens_sinema"],
  "siemens_mindsphere":       ["siemens_mindsphere"],
  "siemens_opcenter":         ["siemens_opcenter"],
  "siemens_industrial_edge":  ["siemens_industrial_edge"],

  "rockwell":                 ["rockwell_factorytalk", "rockwell_ft_historian", "proto_ethernetip"],
  "rockwell_factorytalk":     ["rockwell_factorytalk"],
  "rockwell_ft_historian":    ["rockwell_ft_historian"],
  "rockwell_plantpax":        ["rockwell_plantpax"],
  "rockwell_plex":            ["rockwell_plex"],
  "rockwell_fiix":            ["rockwell_fiix"],
  "rockwell_thinmanager":     ["rockwell_thinmanager"],

  "schneider":                ["schneider_ecostruxure_plant", "schneider_powerlogic"],
  "schneider_ecostruxure_plant":    ["schneider_ecostruxure_plant"],
  "schneider_ecostruxure_building": ["schneider_ecostruxure_building"],
  "schneider_ecostruxure_power":    ["schneider_ecostruxure_power"],
  "schneider_powerlogic":     ["schneider_powerlogic"],
  "schneider_triconex":       ["schneider_triconex"],

  "abb":                      ["abb_800xa", "abb_ability"],
  "abb_800xa":                ["abb_800xa"],
  "abb_ability":              ["abb_ability"],
  "abb_robotics":             ["abb_robotics"],

  "honeywell":                ["honeywell_experion", "honeywell_phd"],
  "honeywell_experion":       ["honeywell_experion"],
  "honeywell_phd":            ["honeywell_phd"],
  "honeywell_bms":            ["honeywell_bms"],

  "emerson":                  ["emerson_deltav", "emerson_ovation"],
  "emerson_deltav":           ["emerson_deltav"],
  "emerson_ovation":          ["emerson_ovation"],
  "emerson_plantweb":         ["emerson_plantweb"],

  "ge_vernova":               ["ge_ifix", "ge_proficy_historian"],
  "ge_vernova_ifix":          ["ge_ifix"],
  "ge_vernova_proficy_historian": ["ge_proficy_historian"],
  "ge_vernova_mark_vie":      ["ge_mark_vie"],

  "yokogawa":                 ["yokogawa_centum", "yokogawa_prosafe"],
  "yokogawa_centum":          ["yokogawa_centum"],
  "yokogawa_prosafe":         ["yokogawa_prosafe"],

  "aveva":                    ["aveva_pi_system", "aveva_historian"],
  "aveva_pi_system":          ["aveva_pi_system"],
  "aveva_historian":          ["aveva_historian"],
  "aveva_system_platform":    ["aveva_system_platform"],

  "fanuc":                    ["fanuc_cnc", "fanuc_robotics"],
  "fanuc_cnc":                ["fanuc_cnc"],
  "fanuc_robotics":           ["fanuc_robotics"],

  "kuka":                     ["kuka_robotics"],
  "beckhoff":                 ["beckhoff_twincat"],
  "phoenix_contact":          ["phoenix_plcnext"],
  "wago":                     ["wago_pfc"],
  "copa_data":                ["copadata_zenon"],
  "ignition":                 ["ignition_scada"],
  "vtscada":                  ["vtscada"],
  "tridium":                  ["tridium_niagara"],
  "jci_metasys":              ["jci_metasys"],
  "ibm_maximo":               ["ibm_maximo"],
  "sap_pm":                   ["sap_pm", "dsa_it_sap"],

  // ── OT Systems & Equipment ──
  "scada_hmi":                ["ot_hmi", "ot_scada", "dsa_ot_scada_security", "dsa_ot_remote_access"],
  "dcs":                      ["ot_dcs"],
  "historian":                ["ot_historian", "dsa_ot_historian_access"],
  "mes":                      ["ot_mes", "ot_erp", "dsa_ot_asset_mgmt"],
  "plc_rtu":                  ["ot_plc_modbus", "ot_plc_opcua", "ot_rtu", "dsa_ot_server_mgmt", "proto_cclink", "proto_fins", "proto_melsec", "proto_iolink", "proto_opcda", "proto_wirelesshart"],
  "safety_system":            ["ot_safety_system"],
  "energy_meter":             ["ot_energy_meter"],
  "vibration_sensor":         ["ot_vibration"],
  "bacnet_devices":           ["ot_bacnet", "proto_bacnet"],

  // ── Industrial Protocols ──
  "dnp3":                     ["proto_dnp3"],
  "iec104":                   ["proto_iec104"],
  "iec61850":                 ["proto_iec61850"],
  "profinet":                 ["proto_profinet"],
  "ethernetip":               ["proto_ethernetip"],
  "ethercat":                 ["proto_ethercat"],
  "s7comm":                   ["proto_s7comm"],
  "mtconnect":                ["proto_mtconnect"],
  "profibus":                 ["proto_profibus"],
  "hart":                     ["proto_hartip"],
  "knx":                      ["proto_knx"],
  "lorawan":                  ["proto_lorawan"],
  "zigbee":                   ["proto_zigbee"],
  "coap":                     ["proto_coap"]
};

window.DSA_UC_MAP = {
  "1.1.1": ["it_linux"],
  "1.1.2": ["it_linux"],
  "1.1.12": ["it_linux"],
  "1.1.18": ["it_linux"],
  "1.1.20": ["it_linux"],
  "1.2.1": ["it_windows"],
  "1.2.4": ["it_windows"],
  "1.2.6": ["it_windows"],
  "1.2.8": ["it_windows"],
  "1.2.9": ["it_windows"],
  "1.2.15": ["it_dns"],
  "2.1.1": ["it_vmware"],
  "2.1.2": ["it_vmware"],
  "2.1.11": ["it_vmware"],
  "2.1.14": ["it_vmware"],
  "2.1.21": ["it_vmware"],
  "5.1.1": ["net_switch"],
  "5.1.4": ["net_router"],
  "5.1.5": ["net_router"],
  "5.1.6": ["net_switch"],
  "5.1.13": ["net_switch"],
  "5.1.14": ["proto_snmp"],
  "5.1.16": ["net_router"],
  "5.1.22": ["net_switch"],
  "5.1.35": ["net_router"],
  "5.1.36": ["net_switch", "net_meraki"],
  "5.2.1": ["sec_ngfw_paloalto", "sec_fw_cisco", "cisco_secure_firewall"],
  "5.2.2": ["sec_ngfw_paloalto"],
  "5.2.3": ["sec_ngfw_paloalto", "sec_fw_cisco", "cisco_secure_firewall"],
  "5.2.19": ["net_meraki"],
  "5.2.44": ["sec_ngfw_fortinet"],
  "5.2.45": ["sec_ngfw_fortinet"],
  "5.2.46": ["sec_ngfw_fortinet"],
  "5.4.2": ["net_wireless", "cisco_wlc"],
  "5.4.7": ["net_wireless", "cisco_wlc"],
  "5.4.10": ["net_wireless", "cisco_wlc"],
  "5.4.12": ["net_wireless", "net_meraki", "cisco_wlc"],
  "5.4.20": ["net_wireless", "cisco_wlc"],
  "5.5.1": ["net_sdwan", "cisco_sdwan"],
  "5.5.4": ["net_sdwan", "cisco_sdwan"],
  "5.5.18": ["net_sdwan", "cisco_sdwan"],
  "5.6.1": ["it_dns"],
  "5.6.2": ["it_dns"],
  "5.6.4": ["it_dns"],
  "5.6.8": ["it_dns"],
  "5.7.1": ["net_netflow"],
  "5.7.2": ["net_netflow"],
  "5.7.7": ["net_netflow"],
  "5.7.8": ["net_netflow"],
  "5.7.10": ["net_netflow"],
  "5.8.1": ["cisco_catalyst_center"],
  "5.8.2": ["net_meraki"],
  "5.8.3": ["proto_snmp"],
  "5.9.1": ["cisco_thousandeyes"],
  "5.9.2": ["cisco_thousandeyes"],
  "5.9.6": ["cisco_thousandeyes"],
  "5.9.18": ["cisco_thousandeyes"],
  "5.9.29": ["net_sdwan", "cisco_sdwan"],
  "5.9.46": ["cisco_thousandeyes"],
  "10.1.46": ["sec_fw_cisco", "cisco_secure_firewall"],
  "10.1.58": ["sec_fw_cisco", "cisco_secure_firewall"],
  "10.1.62": ["sec_fw_cisco", "cisco_secure_firewall"],
  "10.7.277": ["sec_edr"],
  "10.11.41": ["sec_edr"],
  "10.11.42": ["sec_edr"],
  "10.11.45": ["sec_edr"],
  "10.11.46": ["sec_edr"],
  "14.1.1": ["proto_bacnet"],
  "14.1.8": ["proto_modbus"],
  "14.1.9": ["proto_opcua"],
  "14.1.10": ["proto_snmp"],
  "14.1.11": ["proto_snmp"],
  "14.1.14": ["proto_snmp"],
  "14.1.15": ["net_meraki"],
  "14.1.45": ["proto_bacnet"],
  "14.1.46": ["proto_bacnet"],
  "14.2.1": ["ot_scada"],
  "14.2.7": ["proto_modbus"],
  "14.2.8": ["proto_opcua"],
  "14.2.12": ["ot_historian"],
  "14.2.15": ["ot_scada"],
  "14.2.16": ["ot_historian"],
  "14.2.25": ["ot_scada", "ot_historian"],
  "14.2.26": ["ot_historian"],
  "14.3.1": ["ot_edge_hub"],
  "14.3.5": ["proto_mqtt"],
  "14.3.6": ["ot_edge_hub"],
  "14.3.7": ["ot_edge_hub"],
  "14.3.24": ["proto_mqtt", "proto_bacnet"],
  "14.3.31": ["proto_opcua"],
  "14.3.32": ["proto_modbus"],
  "14.3.33": ["proto_mqtt"],
  "14.3.34": ["ot_edge_hub"],
  "14.3.35": ["proto_opcua"],
  "14.3.38": ["ot_scada"],
  "14.3.42": ["ot_edge_hub"],
  "14.9.1": ["sec_ids_cybervision", "cisco_cyber_vision"],
  "14.9.3": ["sec_ids_cybervision", "cisco_cyber_vision"],
  "14.9.5": ["sec_ids_cybervision", "cisco_cyber_vision"],
  "14.9.20": ["sec_ids_cybervision", "cisco_cyber_vision"],
  "14.9.21": ["sec_ids_cybervision", "cisco_cyber_vision"],
  "15.3.30": ["cisco_spaces"],
  "15.3.34": ["cisco_spaces"],
  "15.3.38": ["cisco_spaces"],
  "15.3.39": ["cisco_spaces"],
  "15.3.40": ["cisco_spaces"],
  "17.1.1": ["sec_ise", "cisco_ise"],
  "17.1.3": ["sec_ise", "cisco_ise"],
  "17.1.7": ["sec_ise", "cisco_ise"],
  "17.1.13": ["sec_ise", "cisco_ise"],
  "17.1.21": ["sec_ise", "cisco_ise"],
  "17.2.9": ["sec_ngfw_paloalto"],
  "17.3.23": ["sec_ngfw_paloalto"],
  "17.3.39": ["sec_ngfw_fortinet"],
  "17.3.42": ["sec_ngfw_fortinet"]
};
