"""Curated baseline of well-known Splunkbase TA sourcetypes and ESCU macros.

Goal: keep the ``audit-spl-references`` MEDIUM tier surfaceable without
forcing every contributor to vendor the entire ESCU repo and every
Splunkbase add-on into ``external/``. Anything in this file is treated
as known-good vocabulary — i.e. the audit will not flag it as
"unknown".

What goes here:

* Sourcetypes from the **top public Splunkbase add-ons** (every one
  documented in the corresponding TA's README on Splunkbase). These
  are facts about Splunk's published add-on conventions, not creative
  expression.
* Macros shipped by **Splunk's Enterprise Security Content Update**
  (`splunk/security_content`_, Apache-2.0). These are the macros
  every modern detection authoring workflow expects to be present.

What does NOT go here:

* Customer-specific or environment-specific identifiers — those go in
  the local reference corpus emitted by
  ``tools/research/build_spl_reference.py`` from ``external/``.
* Splunk-core SPL commands / eval functions / stats functions —
  those live in ``_spl_baseline.py``.

When an entry needs adding, prefer adding to this file over expanding
``_spl_baseline.py`` — it keeps the boundary between "Splunk core
language" and "well-known third-party content" explicit.

.. _`splunk/security_content`: https://github.com/splunk/security_content
"""

from __future__ import annotations

__all__ = [
    "WELL_KNOWN_SOURCETYPES",
    "WELL_KNOWN_MACROS",
    "WELL_KNOWN_INDEXES",
]


# ---------------------------------------------------------------------------
# Sourcetypes from popular Splunkbase Technology Add-ons.
#
# Each grouping cites the TA on Splunkbase. Where a TA defines a parametric
# family (e.g. WinEventLog:<channel>) we list the most common channels;
# wildcarded uses (`sourcetype="WinEventLog:*"`) are handled by the
# parser's `is_wildcard` flag and never reach the audit.
# ---------------------------------------------------------------------------
WELL_KNOWN_SOURCETYPES: set[str] = {
    # Splunk Add-on for Microsoft Windows (TA-windows) — Splunkbase 742
    "WinEventLog",
    "WinEventLog:Security",
    "WinEventLog:System",
    "WinEventLog:Application",
    "WinEventLog:Setup",
    "WinEventLog:DNS Server",
    "WinEventLog:Microsoft-Windows-PowerShell/Operational",
    "WinEventLog:Microsoft-Windows-Sysmon/Operational",
    "WinEventLog:Microsoft-Windows-AppXDeploymentServer/Operational",
    "WinEventLog:Microsoft-Windows-PrintService/Operational",
    "WinEventLog:Microsoft-Windows-WMI-Activity/Operational",
    "WinEventLog:Microsoft-Windows-TaskScheduler/Operational",
    "WinEventLog:Microsoft-Windows-Bits-Client/Operational",
    "WinEventLog:Microsoft-Windows-Windows Defender/Operational",
    "WinEventLog:ForwardedEvents",
    "XmlWinEventLog",
    "XmlWinEventLog:Security",
    "XmlWinEventLog:System",
    "XmlWinEventLog:Application",
    "XmlWinEventLog:Microsoft-Windows-PowerShell/Operational",
    "XmlWinEventLog:Microsoft-Windows-Sysmon/Operational",
    "XmlWinEventLog:Microsoft-Windows-AppXDeploymentServer/Operational",
    "WinHostMon",
    "WinRegistry",
    "WinPrintMon",
    "WinNetMon",
    "MSAD:NT6:DNS",
    "Perfmon",
    "Perfmon:CPU",
    "Perfmon:Memory",
    "Perfmon:LogicalDisk",
    "Perfmon:Network",
    # Splunk Add-on for Sysmon (Splunkbase 1914)
    "sysmon",
    "Sysmon",
    # Splunk Add-on for Linux / Unix (TA-nix) — Splunkbase 833
    "linux_secure",
    "syslog",
    "linux_audit",
    "auditd",
    "Unix:Service",
    "Unix:Uptime",
    "Unix:Version",
    "Unix:Update",
    "Unix:UserAccounts",
    "Unix:VSFTPDLog",
    "Unix:CPUTime",
    "Unix:DiskSpace",
    "Unix:File",
    "Unix:Hardware",
    "Unix:NetworkPorts",
    "Unix:NetworkInterface",
    "Unix:Process",
    "ps",
    "df",
    "vmstat",
    "iostat",
    "top",
    "lastlog",
    "interfaces",
    "openPorts",
    "package",
    "usersWithLoginPrivs",
    "osx_secure",
    "Unix:SSHDConfig",
    # Splunk Add-on for Active Directory / LDAP — Splunkbase 1151
    "MSAD:NT6:Replication",
    "MSAD:NT6:Health",
    "ActiveDirectory",
    # Splunk Add-on for AWS — Splunkbase 1876
    "aws:cloudtrail",
    "aws:cloudwatch",
    "aws:cloudwatchlogs",
    "aws:cloudwatchlogs:vpcflow",
    "aws:cloudwatchlogs:guardduty",
    "aws:cloudwatchlogs:eks",
    "aws:cloudwatchlogs:cloudtrail",
    "aws:cloudwatchlogs:waf",
    "aws:config",
    "aws:config:notification",
    "aws:config:rule",
    "aws:description",
    "aws:elb:accesslogs",
    "aws:cloudfront:accesslogs",
    "aws:s3:accesslogs",
    "aws:s3",
    "aws:rds:audit",
    "aws:rds:slowquery",
    "aws:billing",
    "aws:billing:cur",
    "aws:cur",
    "aws:guardduty",
    "aws:inspector",
    "aws:inspector:findings",
    "aws:macie",
    "aws:waf",
    "aws:vpcflow",
    "aws:lambda:cloudwatchlogs",
    "aws:firehose:json",
    "aws:metadata",
    "aws:cloudtrail:digest",
    "aws:securityhub:findings",
    "aws:securityhub",
    "aws:cloudwatch:events",
    "aws:cloudwatch:metric",
    "aws:config:resource",
    "aws:ecr:scan",
    "aws:ssm:compliance",
    "aws:trustedadvisor",
    "aws:service_quotas",
    # Microsoft Azure / Office 365 — Splunkbase 3757 / 4055
    "azure:audit",
    "azure:resource:graph",
    "azure:monitor:activity",
    "azure:monitor:resource",
    "azure:monitor:aad",
    "azure_monitor_aad",
    "azure:graph:audit",
    "azure:eventhub",
    "azure:costmanagement",
    "azure:defender",
    "azure:keyvault:certs",
    "mscs:azure:audit",
    "mscs:azure:defender",
    "mscs:azure:diagnostics",
    "mscs:azure:metrics",
    "mscs:azure:signinlog",
    "ms:aad:audit",
    "ms:aad:signin",
    "ms:aad:auditlog",
    "ms:o365:management",
    "o365:management:activity",
    "o365:management:activity:azureactivedirectory",
    "o365:management:activity:exchange",
    "o365:management:activity:sharepoint",
    "o365:management:activity:onedrive",
    "ms:defender:atp:alerts",
    "ms:defender:atp:advancedhuntingschema",
    "ms:defender:m365",
    # Google Cloud Platform / GCP — Splunkbase 3088
    "google:gcp:pubsub:message",
    "google_gcp_pubsub_message",
    "google:gcp:billing:resource",
    "google:gcp:billing:report",
    "google:gcp:audit",
    "google:gcp:monitoring",
    "google:gcp:resource:asset",
    "gcp:billing",
    "gcp:scc",
    # Multi-cloud / cross-cutting cloud monitoring
    "adconnect:health",
    "billing:daily",
    "dns:resolution",
    "endpoint:health",
    "synthetic:dns",
    "terraform:plan",
    "gws:reports:login",
    "gws:reports:admin",
    "gws:reports:drive",
    "gws:reports:meet",
    "gws:reports:saml",
    "gws:reports:user_accounts",
    "gws:reports:groups_enterprise",
    # Oracle Cloud Infrastructure (OCI) — Splunk Add-on for Oracle Cloud Infrastructure
    "oci:audit",
    "oci:log",
    "oci:cloudguard",
    "oci:cloudguard:problem",
    "oci:functions:invocation",
    "oci:vcn:flowlogs",
    "oci:objectstorage:access",
    # Alibaba Cloud — Splunk Add-on for Alibaba Cloud
    "alibaba:actiontrail",
    "alibaba:sls",
    "alibaba:config",
    "alibaba:cloudmonitor",
    # Splunk Connect for Kubernetes — Splunkbase 4467
    "kube:objects:events",
    "kube:objects:metrics",
    "kube:objects:pods",
    "kube:objects:nodes",
    "kube:container",
    "kube:container:logs",
    "kube:objects:configmaps",
    "kube:objects:deployments",
    "kube:objects:replicasets",
    "kube:objects:services",
    "kube:objects:statefulsets",
    "kube:objects:namespaces",
    "kube:objects:secrets",
    "kube:objects:ingresses",
    "kube:objects:persistentvolumeclaims",
    "kube:objects:cronjobs",
    "kube:objects:jobs",
    "kube:audit",
    # Splunk Add-on for ServiceNow — Splunkbase 1928
    "snow:incident",
    "snow:problem",
    "snow:change_request",
    "snow:change_task",
    "snow:cmdb_ci",
    "snow:em_event",
    "snow:em_alert",
    "snow:sys_user",
    "snow:incident_sla",
    "snow:audit",
    # Splunk Add-on for Cisco ASA / Firepower — Splunkbase 1620
    "cisco:asa",
    "cisco:fwsm",
    "cisco:pix",
    "cisco:ftd",
    "cisco:firepower",
    "cisco:firepower:syslog",
    "cisco:firepower:event",
    "cisco:firepower:host",
    "cisco:firepower:flow",
    "cisco:firepower:malware",
    "cisco:firepower:intrusion",
    "cisco:firepower:correlation",
    # Splunk Add-on for Cisco IOS — Splunkbase 1467
    "cisco:ios",
    "cisco:iosxe",
    "cisco:iosxr",
    "cisco:nxos",
    "cisco:wlc:syslog",
    "cisco:catalyst:wireless",
    # Splunk Add-on for Cisco UCS — Splunkbase 1734
    "cisco:ucs:inventory",
    "cisco:ucs:stats",
    "cisco:ucs:fault",
    "cisco:ucs:event",
    # Cisco Meraki — Splunkbase 5197
    "meraki",
    "meraki:flows",
    "meraki:syslog",
    "meraki:events",
    "meraki:airmarshal",
    "meraki:urls",
    "meraki:ids",
    "meraki:wireless",
    "meraki_security_events",
    "meraki_appliance_events",
    "meraki:wirelessHealth",
    # Cisco Catalyst Center / DNAC — Splunkbase 5811
    "cisco:dnac:devicehealth",
    "cisco:dnac:clienthealth",
    "cisco:dnac:networkhealth",
    "cisco:dnac:issue",
    "cisco:dnac:compliance",
    # Cisco Cyber Vision — Splunkbase 5403
    "cybervision:event",
    "cybervision:alert",
    # Splunk Add-on for Palo Alto Networks — Splunkbase 2757
    "pan:traffic",
    "pan:threat",
    "pan:system",
    "pan:config",
    "pan:hipmatch",
    "pan:hipmatch_general_health",
    "pan:url",
    "pan:wildfire",
    "pan:wildfire_report",
    "pan:globalprotect",
    "pan:userid",
    "pan:correlation",
    "pan:authentication",
    "pan:data",
    "pan:decryption",
    "pan:gtp",
    "pan:dns",
    # Fortinet FortiGate / FortiAnalyzer — Splunkbase 2846
    "fgt_event",
    "fgt_traffic",
    "fgt_utm",
    "fgt_log",
    "fortigate_traffic",
    "fortigate_event",
    "fortigate_utm",
    # Check Point — Splunkbase 4293
    "opsec",
    "checkpoint:opsec",
    "cp_log",
    # Juniper Networks — Splunkbase 2847
    "juniper:firewall",
    "juniper:idp",
    "juniper:junos",
    "juniper:junos:firewall",
    "juniper:junos:idp",
    "juniper:junos:traffic",
    # F5 BIG-IP — Splunkbase 2680
    "f5:bigip:apm:syslog",
    "f5:bigip:asm:syslog",
    "f5:bigip:ltm:syslog",
    "f5:bigip:irule:syslog",
    "f5:silverline:asm",
    # Tenable / Nessus / Tenable.io / Tenable.sc — Splunkbase 1418
    "tenable:io:vuln",
    "tenable:io:assets",
    "tenable:io:plugins",
    "tenable:sc:vuln",
    "tenable:vuln",
    "tenable:asset",
    "tenable:plugin",
    "nessus_scan",
    # Qualys — Splunkbase 2964
    "qualys:hostDetection",
    "qualys:hostsummary",
    "qualys_knowledgebase",
    "qualys_vm_detection",
    "qualys:vmdr:knowledgebase",
    "qualys:vmdr:vulnerability",
    # CrowdStrike Falcon — Splunkbase 4710
    "CrowdStrike:Detection",
    "CrowdStrike:Audit",
    "CrowdStrike:Telemetry",
    "CrowdStrike:Hosts",
    "crowdstrike:falconhost:json",
    "crowdstrike:falconhost",
    # Carbon Black — Splunkbase 1085 / 5219
    "bit9:carbonblack:json",
    "carbonblack:edr",
    "carbonblack:cb:edr:event",
    "vmware:cb:edr",
    # SentinelOne — Splunkbase 4988
    "sentinelone:cef",
    "sentinelone:event",
    # Symantec Endpoint Protection — Splunkbase 2772
    "symantec:ep:agt:file",
    "symantec:ep:proactive:file",
    "symantec:ep:scan:file",
    "symantec:ep:syslog",
    # Trend Micro — Splunkbase 5403
    "trendmicro:officescan",
    "trendmicro:deepsecurity",
    # GitHub Actions — Splunkbase 5536
    "github:actions",
    "github:audit",
    "github:webhook",
    "github:enterprise:audit",
    # GitLab — Splunkbase 5234
    "gitlab:audit",
    "gitlab:application",
    # Atlassian Jira / Confluence — Splunkbase 5219
    "atlassian:jira:audit",
    "atlassian:confluence:access",
    # Okta — Splunkbase 2806
    "OktaIM2:log",
    "OktaIM2:groups",
    "OktaIM2:users",
    "OktaIM2:apps",
    "okta:im2:log",
    "okta:im2",
    "okta",
    # Duo Security — Splunkbase 3504
    "duo:authentication",
    "duo:administrator",
    "duo:telephony",
    "duo:offlineenrollment",
    # CyberArk — Splunkbase 3393
    "cyberark:epv:cef",
    "cyberark:epm",
    # Zscaler — Splunkbase 3865
    "zscalernss-fw",
    "zscalernss-web",
    "zscalernss-dns",
    "zscaler:web",
    "zscaler:firewall",
    "zscaler:zia:weblog",
    "zscaler:zia:dnslog",
    "zscaler:zpa:auditlog",
    # Forcepoint — Splunkbase 3500
    "forcepoint:one",
    "forcepoint:web",
    "forcepoint:email",
    "forcepoint:dlp",
    # Splunk Stream — Splunkbase 1812
    "stream:dns",
    "stream:http",
    "stream:tcp",
    "stream:udp",
    "stream:tls",
    "stream:smtp",
    "stream:icmp",
    "stream:smb",
    "stream:ldap",
    "stream:smb2",
    "stream:mysql",
    "stream:ftp",
    # Splunk Enterprise / Splunk Cloud platform internals
    "splunkd",
    "splunkd_access",
    "splunkd_ui_access",
    "splunkd_remote_searches",
    "splunk_web_access",
    "splunk_web_service",
    "splunk_resource_usage",
    "splunk_disk_objects",
    "scheduler",
    "audittrail",
    "audit",
    "metrics",
    "dispatch",
    "splunk_python",
    "license_usage",
    "btool",
    # Web servers
    "access_combined",
    "access_combined_wcookie",
    "access_common",
    "apache:access",
    "apache:error",
    "iis",
    "ms:iis:auto",
    "ms:iis:default",
    "nginx:access",
    "nginx:error",
    "nginx:plus:access",
    # Databases
    "oracle:auditDB",
    "oracle:audit",
    "mysql:error",
    "mysql:slow",
    "mssql:errorlog",
    "postgres:errorlog",
    # Load balancers / proxies
    "haproxy",
    "haproxy:tcp",
    "haproxy:http",
    "squid:access",
    # Open-source observability
    "redis:info",
    "memcached:stats",
    "zookeeper:mntr",
    "kafka:logs",
    "elasticsearch:logs",
    "elasticsearch:slowlogs",
    "vault:audit",
    "consul:metrics",
    "consul:logs",
    "etcd:metrics",
    "rabbitmq:metrics",
    "rabbitmq:logs",
    "mongodb:errorlog",
    "mongodb:slowQueries",
    # Prometheus / OTel
    "prometheus:metrics",
    "prometheus:ocp",
    "otel:metrics",
    "otel:logs",
    "otel:traces",
    # Cloud-native / CI
    "kafka:metrics",
    "consul:health",
    # ServiceNow / ITSM
    "servicenow:incident",
    "servicenow:cmdb",
    # Backup / DR
    "veeam:job",
    "veeam:event",
    "veeam:repository",
    # Misc Cisco
    "cisco:ise:syslog",
    "cisco:ise:radius",
    "cisco:asa:syslog",
    "cisco:netflow",
    "cisco:secureendpoint:event",
    "cisco:secureendpoint:webhook",
    # Generic open formats
    "json",
    "xml",
    "csv",
    "cef",
    "leef",
    "key_value",
    "_json",
    # OPNsense / pfSense — community add-ons
    "opnsense:filterlog",
    "pfsense:filterlog",
    # ------------------------------------------------------------------
    # cat-24 Business Intelligence & Analytics Platforms — BI tooling and
    # modern-data-stack sourcetypes. These are the canonical ingest names
    # for the admin/audit logs, REST-API scripted inputs, and DB Connect
    # probes documented in each UC's ``dataSources`` field.
    # ------------------------------------------------------------------
    # BI tools
    "tableau:backgrounder",
    "tableau:vizqlserver",
    "tableau:dataserver",
    "tableau:httpd",
    "tableau:vizportal",
    "tableau:licensing",
    "tableau:tsm:metrics",
    "powerbi:admin:refreshes",
    "powerbi:admin:api",
    "powerbi:gateway:info",
    "powerbi:gateway:mashup",
    "powerbi:capacity:metrics",
    "looker:system_activity",
    "looker:api",
    "looker:lookml_validation",
    "qlik:scheduler",
    "qlik:engine",
    "qlik:proxy",
    "superset:app",
    "metabase:app",
    "redash:app",
    "bi:embed:client",
    "microstrategy:dsserror",
    "cognos:audit",
    "businessobjects:audit",
    "oracle:analytics:usage",
    "thoughtspot:audit",
    # Data orchestration / transformation
    "airflow:scheduler",
    "airflow:task",
    "dbt:run_results",
    "dbt:sources",
    "dbt:semantic_layer",
    # Data ingestion / ELT
    "fivetran:log",
    "airbyte:job",
    "kafka:connect",
    "aws:cloudwatch:glue",
    "azure:monitor:adf",
    # Data quality & observability
    "montecarlo:incident",
    "great_expectations:validation",
    "soda:scan",
    "dbx:warehouse_freshness",
    "dbx:warehouse_rowcounts",
    "dbx:warehouse_columns",
    "dbx:warehouse_nullrates",
    "dbx:metric_probe",
    # Catalog / lineage / governance
    "collibra:audit",
    "atlan:audit",
    "openlineage:event",
    "unity_catalog:audit",
    "purview:scan",
    # Semantic / metrics layer
    "cube:api",
    # Reverse ETL & activation
    "hightouch:sync",
    "census:sync",
    "segment:delivery",
    "rudderstack:delivery",
    # ------------------------------------------------------------------
    # Phase 1 — data-engineering depth (24.7 / 24.8 / 24.9)
    # ------------------------------------------------------------------
    # Orchestration
    "airflow:worker",
    "airflow:statsd",
    "dagster:daemon",
    "dagster:run",
    "dagster:event",
    "prefect:worker",
    "prefect:agent",
    "prefect:api",
    "dbtcloud:run",
    "controlm:job",
    "controlm:em",
    "controlm:agent",
    # Ingestion / ELT
    "fivetran:connector",
    "airbyte:worker",
    "kafkaconnect:status",
    "kafkaconnect:worker",
    "kafkaconnect:jmx",
    "aws:glue:jobrun",
    "azure:datafactory",
    "matillion:task",
    "informatica:session",
    # Data quality & observability
    "greatexpectations:validation",
    "bigeye:issue",
    # ------------------------------------------------------------------
    # Phase 2 — BI-tool breadth (24.3 / 24.4 / 24.5 / 24.6)
    # ------------------------------------------------------------------
    "qlik:qrs",
    "domo:activity",
    # ------------------------------------------------------------------
    # Phase 3 — governance & activation (24.10 / 24.11 / 24.12 / 24.13)
    # ------------------------------------------------------------------
    "semantic_layer:query",
    # ------------------------------------------------------------------
    # Phase 4 — monitoring-angle matrix (breadth across the roster)
    # ------------------------------------------------------------------
    # BI tools
    "tableau:cloud:activity",
    "tableau:prep:flow",
    "fabric:capacity:metrics",
    "powerbi:dataflow",
    "powerbi:reportserver",
    "lookerstudio:usage",
    "qlik:cloud:audit",
    "qlik:nprinting",
    "qlikview:distribution",
    "preset:audit",
    "lightdash:app",
    "sigma:audit",
    "mode:audit",
    "hex:audit",
    "evidence:build",
    "sas:viya:audit",
    "sac:audit",
    "yellowfin:audit",
    "gooddata:audit",
    "sisense:audit",
    # Orchestration
    "argo:workflow",
    "astronomer:dag",
    "databricks:jobs",
    "aws:states:execution",
    "gcp:composer",
    "azure:synapse:pipeline",
    "mage:pipeline",
    "kestra:execution",
    # Ingestion / ELT
    "aws:dms:task",
    "gcp:dataflow",
    "stitch:extraction",
    "meltano:run",
    "hevo:pipeline",
    "dlt:load",
    "rivery:run",
    "informatica:iics",
    "talend:job",
    # Data quality & observability
    "elementary:test",
    "datafold:diff",
    "anomalo:check",
    "metaplane:monitor",
    "acceldata:policy",
    "lightup:check",
    # Catalog / lineage / governance
    "alation:audit",
    "atlan:audit",
    "datahub:event",
    "openmetadata:audit",
    "immuta:audit",
    "amundsen:event",
    "secoda:audit",
    # Semantic / metrics layer
    "atscale:query",
    "kyvos:query",
    # Reverse ETL & activation
    "segment:delivery",
    "polytomic:sync",
    "grouparoo:run",
    # ------------------------------------------------------------------
    # cat-25 Personal & Hobbyist Monitoring (the fun category)
    # ------------------------------------------------------------------
    # Fitness & activity
    "strava:activity",
    "garmin:activity",
    "fitbit:activity",
    "peloton:workout",
    "zwift:activity",
    # Health, sleep & wearables
    "apple:health",
    "oura:daily",
    "whoop:cycle",
    "withings:measure",
    "dexcom:egv",
    # Connected cars & EVs
    "tesla:vehicle",
    "tesla:charge",
    "obd:pid",
    "evcharger:session",
    # Smart home platforms & automation
    "homeassistant:event",
    "homey:flow",
    "nodered:event",
    # Smart home devices & sensors
    "zigbee2mqtt:device",
    "shelly:status",
    "ecobee:thermostat",
    # Home energy & solar
    "solaredge:power",
    "enphase:production",
    "powerwall:aggregate",
    "dsmr:telegram",
    "emporia:circuit",
    # Media, gaming & entertainment
    "tautulli:play",
    "jellyfin:activity",
    "spotify:play",
    "steam:player",
    "sonarr:event",
    # Home lab & self-hosting
    "truenas:pool",
    "docker:stats",
    "proxmox:metric",
    "nut:ups",
    "uptime:probe",
    "rpi:metric",
    "synology:disk",
    # Home network & connectivity
    "speedtest:result",
    "pihole:query",
    "unifi:event",
    # Weather, environment & garden
    "airgradient:sensor",
    "purpleair:aqi",
    "ecowitt:obs",
    "weatherflow:obs",
    "plant:sensor",
    "aquarium:sensor",
    # Pets & home life
    "whistle:activity",
    "tractive:position",
    "petfeeder:event",
    "litterrobot:cycle",
    "birdfeeder:detection",
    "doorbell:event",
    # Personal finance & crypto
    "crypto:price",
    "coinbase:txn",
    "firefly:txn",
    "wallet:balance",
    # Digital life & productivity
    "rescuetime:activity",
    "screentime:usage",
    "github:personal",
    "habit:entry",
    "calendar:event",
    "passwordmanager:audit",
    "email:metadata",
    # Travel, commute & flight-spotting
    "adsb:aircraft",
    "flight:log",
    "commute:trip",
    "transit:arrival",
    "geofence:event",
    "travel:document",
    "airprice:quote",
    # Kitchen, cooking & fermentation
    "sourdough:reading",
    "bbq:probe",
    "kitchen:appliance",
    "espresso:shot",
    "pantry:item",
    "kombucha:reading",
    # Homebrewing, beer & wine
    "brew:fermentation",
    "kegerator:pour",
    "winecellar:reading",
    # Making, 3D printing & workshop
    "octoprint:job",
    "printer:telemetry",
    "filament:spool",
    "cnc:job",
    "workshop:air",
    "tool:battery",
    # Home security & surveillance
    "frigate:event",
    "camera:health",
    "alarm:event",
    "lock:access",
    "plate:detection",
    # Water, plumbing & utilities
    "watermeter:flow",
    "sumppump:event",
    "wellpump:event",
    "pool:chemistry",
    "watersoftener:status",
    "irrigation:zone",
    # Citizen science & backyard sensing (25.20)
    "seismo:reading",
    "geiger:cpm",
    "lightning:strike",
    "radon:reading",
    "allsky:capture",
    "riverlevel:reading",
    "magnetometer:reading",
    "satpass:prediction",
    # Radio, SDR & space (25.21)
    "aprs:packet",
    "wspr:spot",
    "noaa:apt",
    "meteorscatter:ping",
    "sstv:image",
    # Backyard astronomy & observatory (25.22)
    "observatory:env",
    "skyquality:reading",
    "imaging:session",
    "mount:status",
    "allsky:cloud",
    # Family, baby & household chaos (25.23)
    "baby:feed",
    "baby:sleep",
    "diaper:change",
    "chore:completion",
    "allowance:ledger",
    "family:calendar",
    "growth:measurement",
    # Homestead, bees & livestock (25.24)
    "beehive:reading",
    "chickencoop:door",
    "egg:count",
    "livestock:tag",
    "feed:level",
    "pasture:sensor",
    # Advanced health & biohacking (25.25)
    "hrv:reading",
    "spo2:reading",
    "bloodpanel:result",
    "supplement:intake",
    "cgm:glucose",
    "apnea:event",
    "bodycomp:measure",
    "bloodpressure:reading",
    # Wildlife & biodiversity (25.26)
    "birdnet:detection",
    "trailcam:detection",
    "mothtrap:capture",
    "batdetector:pass",
    "pollinator:count",
    "wildlifecam:visit",
    # Aquariums, reptiles & vivariums (25.27)
    "reeftank:param",
    "vivarium:climate",
    "fishfeeder:event",
    "doser:event",
    "ato:event",
    "pondsensor:reading",
    # Sports, skills & training telemetry (25.28)
    "vbt:rep",
    "gait:metric",
    "hangboard:session",
    "golfswing:metric",
    "powermeter:interval",
    "shotarc:make",
    # Games & tabletop (25.29)
    "game:session",
    "achievement:unlock",
    "boardgame:play",
    "chess:game",
    "dice:roll",
    # Collections & hobbies (25.30)
    "collection:item",
    "vinyl:play",
    "lego:set",
    "tradingcard:price",
    # Mind, mood & journaling (25.31)
    "mood:entry",
    "meditation:session",
    "journal:entry",
    "gratitude:log",
    # Relationships & togetherness (25.32)
    "relationship:checkin",
    "datenight:log",
    "giftidea:item",
    "keptintouch:contact",
    # Everyday habits & vices (25.33)
    "alcohol:drink",
    "vice:log",
    "hydration:intake",
    "swearjar:entry",
    # Money pettiness & microspending (25.34)
    "microspend:txn",
    "nospend:day",
    "priceperuse:item",
    "cashback:reward",
    # Body signals & personal oddities (25.35)
    "posture:reading",
    "symptom:log",
    "bathroom:visit",
    "sneeze:event",
    # Household supplies & logistics (25.36)
    "supply:level",
    "delivery:parcel",
    "bincollection:event",
    "giftcard:balance",
    # Building health & structural (25.37)
    "mould:risk",
    "crackmeter:reading",
    "hvacfilter:life",
    "structural:tilt",
    # Personal cyber & digital exhaust (25.38)
    "breach:alert",
    "inbox:stats",
    "clouddrive:usage",
    "certexpiry:check",
    # Seasonal & silly (25.39)
    "festive:lights",
    "candy:counter",
    "countdown:event",
    "santa:tracker",
    # Cross-stream ML & the personal digital twin (25.40)
    "lifescore:daily",
    "personalslo:status",
    "correlation:pair",
    # Micro-mobility & action sports (25.41)
    "ebike:ride",
    "scooter:trip",
    "skate:session",
    "surf:session",
    "snow:run",
    # Aviation & flight simulation (25.42)
    "flightlog:entry",
    "avionics:telemetry",
    "flightsim:session",
    "preflight:check",
    # Boating & marine (25.43)
    "nmea:reading",
    "bilge:event",
    "mooring:status",
    "marineweather:forecast",
    # Fishing, hunting & foraging (25.44)
    "fishing:catch",
    "fishfinder:reading",
    "foraging:find",
    "gamecam:trigger",
    # Music-making & creator analytics (25.45)
    "practice:session",
    "daw:session",
    "release:stats",
    "setlist:play",
    # Tabletop RPG campaigns (25.46)
    "campaign:session",
    "npc:ledger",
    "loot:drop",
    "xp:award",
    # Reading & second brain (25.47)
    "reading:progress",
    "highlight:capture",
    "note:link",
    "book:finished",
    # Language learning (25.48)
    "lesson:complete",
    "vocab:review",
    "immersion:log",
    "speaking:session",
    # Wardrobe, fashion & beauty (25.49)
    "wardrobe:item",
    "outfit:wear",
    "skincare:routine",
    "laundry:cycle",
    # Sustainability & zero-waste (25.50)
    "carbon:estimate",
    "recycling:weight",
    "foodwaste:log",
    "repair:event",
    # Chronic-condition management (25.51)
    "condition:symptom",
    "medication:dose",
    "vitals:reading",
    "flareup:event",
    "labresult:value",
    # Elder care & accessibility (25.52)
    "eldercare:activity",
    "fall:alert",
    "medreminder:event",
    "checkin:call",
    "wandering:alert",
    # Wedding & event planning (25.53)
    "event:task",
    "event:budget",
    "event:rsvp",
    "event:vendor",
    "event:countdown",
    # Home renovation & project management (25.54)
    "reno:task",
    "reno:budget",
    "reno:material",
    "reno:inspection",
    "reno:contractor",
    # Genealogy & family history (25.55)
    "genealogy:record",
    "dna:match",
    "ancestor:event",
    "archive:document",
    "familytree:node",
    # Spiritual practice & mindfulness (25.56)
    "prayer:session",
    "scripture:reading",
    "fasting:log",
    "gratitude:entry",
    "retreat:event",
    # Volunteering & community (25.57)
    "volunteer:shift",
    "donation:gift",
    "community:event",
    "mutualaid:request",
    "impact:metric",
    # Life-logging & memories (25.58)
    "photo:capture",
    "location:visit",
    "voicememo:note",
    "lifelog:moment",
    "timeline:event",
    # Personal Life-OS & gamification (25.59)
    "lifeos:score",
    "quest:task",
    "streak:status",
    "achievement:life",
    "household:leaderboard",
    # Self-forecasting & prediction markets (25.60)
    "prediction:forecast",
    "prediction:outcome",
    "bet:personal",
    "calibration:score",
    "brier:score",
    # cat-25 depth wave 6 — additional consumer sourcetypes (25.1–25.60 deepen)
    "adguard:query",
    "adsb:message",
    "airquality:reading",
    "ais:message",
    "allsky:event",
    "archery:end",
    "astroimage:sub",
    "astronomy:session",
    "balance:trial",
    "batting:rep",
    "beehive:climate",
    "beehive:weight",
    "brew:batch",
    "brew:mash",
    "brewfridge:compressor",
    "brooder:climate",
    "chore:event",
    "collection:auth",
    "collection:condition",
    "collection:loan",
    "collection:photo",
    "collection:price",
    "collection:scan",
    "coop:egg",
    "coop:session",
    "family:location",
    "focus:metric",
    "fraglight:reading",
    "frogcall:detection",
    "gate:event",
    "greenhouse:climate",
    "greywater:tank",
    "hue:event",
    "kegerator:pressure",
    "ketone:reading",
    "klipper:telemetry",
    "leaksensor:event",
    "milking:session",
    "mood:checkin",
    "mount:session",
    "nestbox:event",
    "observatory:roof",
    "orchard:bloom",
    "phenology:observation",
    "pickleball:rally",
    "plantedtank:co2",
    "quarantine:observation",
    "quest:completion",
    "radiation:count",
    "raid:attempt",
    "rainbarrel:level",
    "ranked:match",
    "reaction:trial",
    "reeftank:feeding",
    "repeater:activity",
    "resinprint:job",
    "rtl433:sensor",
    "satnogs:observation",
    "sauna:session",
    "school:departure",
    "sdr:spectrum",
    "seismograph:event",
    "seismograph:noise",
    "serve:attempt",
    "server:event",
    "smartcar:vehicle",
    "smartthings:event",
    "speedrun:attempt",
    "sprint:rep",
    "stroller:walk",
    "swim:set",
    "tapline:clean",
    "tasmota:sensor",
    "temp:reading",
    "tool:usage",
    "waterheater:event",
    "waterpressure:reading",
    "weatherstation:reading",
    "ynab:txn",
    # cat-25 wave 9 — additional consumer sourcetypes
    "alias:sale",
    "amazon:wishlist",
    "anylist:grocery",
    "audible:listen",
    "battery:expiration",
    "betterhelp:session",
    "birthday:budget",
    "box:inventory",
    "brick:workout",
    "brightwheel:checkin",
    "cbt:homework",
    "clay:relationship",
    "daycare:incident",
    "daylio:mood",
    "deadstock:age",
    "dental:hygiene",
    "downdog:session",
    "ergast:result",
    "f1fantasy:team",
    "f1telemetry:lap",
    "fastf1:session",
    "followup:reminder",
    "garmin:multisport",
    "gift:registry",
    "glo:class",
    "goat:listing",
    "gobag:inventory",
    "goodreads:audiobook",
    "headway:appointment",
    "hingehealth:session",
    "holiday:card",
    "huckleberry:sleep",
    "ikon:pass",
    "instacart:order",
    "intro:request",
    "linkedin:connection",
    "listen:streak",
    "mat:usage",
    "mealime:plan",
    "medbridge:exercise",
    "monica:contact",
    "move:checklist",
    "mover:quote",
    "nanny:timesheet",
    "onthesnow:report",
    "opendental:appointment",
    "pain:diary",
    "pantry:inventory",
    "paprika:recipe",
    "peloton:yoga",
    "pilates:session",
    "podcast:queue",
    "prep:drill",
    "procare:attendance",
    "pt:session",
    "race:watchparty",
    "radio:test",
    "rehab:rom",
    "simplepractice:session",
    "skitracks:run",
    "slopes:session",
    "sneaker:rotation",
    "snow:safety",
    "stockx:price",
    "thankyou:note",
    "transition:log",
    "tridot:plan",
    "usps:change",
    "utility:transfer",
    "vision:prescription",
    "water:rotation",
    "withings:eye",
    "zocdoc:booking",
    # cat-25 wave 10 — additional consumer sourcetypes
    "airbnb:booking",
    "airbnb:payout",
    "cellartracker:bottle",
    "chrono24:listing",
    "claim:home",
    "cleaning:checklist",
    "contacts:order",
    "curology:prescription",
    "cvs:refill",
    "derm:appointment",
    "estate:review",
    "github:commit",
    "github:issue",
    "github:release",
    "github:repo",
    "glasses:prescription",
    "goodrx:price",
    "guest:review",
    "homeinsurance:premium",
    "homeinsurance:renewal",
    "hotspring:session",
    "irs:transcript",
    "lemonade:policy",
    "lens:replacement",
    "local:alert",
    "myswimpro:session",
    "neighborhood:watch",
    "nextdoor:post",
    "petinsurance:premium",
    "pharmacy:pickup",
    "poa:record",
    "pool:lap",
    "prescription:adherence",
    "ring:neighbor",
    "roborock:session",
    "skin:diary",
    "spa:chemistry",
    "spa:energy",
    "spa:filter",
    "spirit:bottle",
    "swim:meet",
    "swimcom:workout",
    "tax:estimate",
    "tax:payment",
    "tidy:schedule",
    "trupanion:claim",
    "trust:document",
    "turbotax:return",
    "uv:exposure",
    "vacuum:runtime",
    "vet:invoice",
    "vet:visit",
    "vision:exam",
    "vivino:wine",
    "vrbo:reservation",
    "w2:import",
    "watch:service",
    "watch:wristtime",
    "watchbox:service",
    "will:status",
    "wine:tasting",
    # cat-25 research expand — variable-depth sourcetypes (v8.19.0)
    "abode:alarm",
    "abrp:plan",
    "acaia:metric1",
    "achievement:metric3",
    "airbnb:metric0",
    "airbnb:metric2",
    "airbnb:metric4",
    "alcohol:metric0",
    "alias:metric2",
    "amazon:metric1",
    "ambientweather:obs",
    "ancestor:metric2",
    "anovaoven:cook",
    "antennapod:metric0",
    "anylist:metric1",
    "apple:metric0",
    "archive:metric3",
    "ascom:device",
    "astap:solve",
    "astrometry:solve",
    "audible:metric1",
    "authelia:auth",
    "avionics:metric1",
    "babytracker:diaper",
    "barkio:bark",
    "bathroom:metric2",
    "batlogger:recording",
    "beanconqueror:metric0",
    "beanhive:roast",
    "beersmith:batch",
    "betterhelp:metric2",
    "beurer:bp",
    "bga:match",
    "bgg:metric0",
    "bilge:metric1",
    "bincollection:metric2",
    "biostrap:daily",
    "biostrap:sleep",
    "birdweather:station",
    "blitzortung:strike",
    "bloomsky:sky",
    "blueiris:event",
    "bluelab:probe",
    "bluetti:status",
    "blynk:garden",
    "bond:fan",
    "book:metric3",
    "breach:metric0",
    "breach:metric4",
    "breadboard:rise",
    "brewpi:ferment",
    "brick:metric3",
    "brightwheel:metric0",
    "broodminder:weight",
    "calendar:metric0",
    "campaign:metric0",
    "camtrapr:detection",
    "candy:metric1",
    "canvas:metric0",
    "carbide:job",
    "carbon:metric0",
    "cashback:metric3",
    "catlink:litter",
    "cattlemax:health",
    "cbt:metric3",
    "cellartracker:metric0",
    "certexpiry:metric3",
    "chefsteps:cook",
    "chickenguard:door",
    "chrono24:metric0",
    "chrono24:metric4",
    "citizenweather:obs",
    "citymapper:route",
    "claim:metric1",
    "clay:metric1",
    "cleaning:metric2",
    "clockify:entry",
    "clouddrive:metric2",
    "club:metric0",
    "cncjs:job",
    "collection:metric0",
    "condition:metric0",
    "contacts:metric0",
    "correlation:metric2",
    "correlation:metric5",
    "cosmicpi:muon",
    "cozi:event",
    "crackmeter:metric1",
    "cuboai:alert",
    "curology:metric0",
    "cvs:metric1",
    "dartfish:tag",
    "datenight:metric1",
    "davis:vantage",
    "daw:metric1",
    "deako:switch",
    "debank:portfolio",
    "delivery:metric1",
    "derm:metric2",
    "discord:presence",
    "dna:metric1",
    "dnsmasq:query",
    "domoticz:event",
    "donation:metric1",
    "downdog:metric0",
    "ebike:metric0",
    "ebird:checklist",
    "ecoflow:delta",
    "eldercare:metric0",
    "emfit:hrv",
    "emfit:sleep",
    "enode:vehicle",
    "epic:achievement",
    "ergast:metric1",
    "ergast:metric6",
    "esphome:device",
    "eufy:security",
    "eve:accessory",
    "event:metric0",
    "event:metric1",
    "event:metric2",
    "f1fantasy:metric2",
    "f1fantasy:metric7",
    "f1telemetry:metric4",
    "fall:metric1",
    "famcal:event",
    "farmbrite:task",
    "farmos:log",
    "fastf1:metric0",
    "fastf1:metric5",
    "fasting:metric2",
    "fermtec:pressure",
    "festive:metric0",
    "fidelity:balance",
    "finalsurge:workout",
    "fishfinder:metric1",
    "fishing:metric0",
    "fitbit:sleep",
    "fldigi:spot",
    "flickr:metric1",
    "flightlog:metric0",
    "flightradar24:flight",
    "flightsim:metric2",
    "foodwaste:metric2",
    "foraging:metric2",
    "fordpass:vehicle",
    "forest:session",
    "freelance:metric0",
    "freelance:metric1",
    "freelance:project",
    "fronius:solar",
    "frost:alert",
    "function:lab",
    "garmin:golf",
    "garmin:metric0",
    "garmin:metric1",
    "garmin:metric6",
    "garmin:runningdynamics",
    "gasbuddy:price",
    "genealogy:metric0",
    "ghl:controller",
    "gift:metric0",
    "giftidea:metric2",
    "github:metric0",
    "github:metric1",
    "github:metric2",
    "github:metric3",
    "github:metric4",
    "github:metric5",
    "github:metric6",
    "glasses:metric1",
    "glinet:syslog",
    "glo:metric2",
    "glowbaby:log",
    "glowmarkt:reading",
    "goat:metric1",
    "gobag:metric0",
    "gog:library",
    "gog:session",
    "golf:metric0",
    "goodreads:metric2",
    "goodrx:metric0",
    "govee:metric1",
    "grafana:alert",
    "grafana:earthquake",
    "grainfather:brew",
    "gratitude:metric3",
    "growatt:inverter",
    "guest:metric3",
    "gymaware:rep",
    "halo:collar",
    "hamclock:contact",
    "headway:metric1",
    "hearthstone:match",
    "hevy:workout",
    "hibp:metric2",
    "highlight:metric1",
    "hingehealth:metric2",
    "hiveeyes:reading",
    "holiday:metric2",
    "homeassistant:metric0",
    "homebridge:accessory",
    "homebuying:milestone",
    "homeinsurance:metric2",
    "homekit:securevideo",
    "homewizard:p1",
    "horus:telemetry",
    "hotspring:metric0",
    "household:account",
    "household:metric4",
    "hubitat:event",
    "huckleberry:metric2",
    "hudl:clip",
    "hvacfilter:metric2",
    "hydration:metric2",
    "hydrawise:zone",
    "hydros:control",
    "immersion:metric2",
    "inaturalist:obs",
    "inbox:metric1",
    "indi:property",
    "inkbird:controller",
    "insidetracker:result",
    "instacart:metric2",
    "intervalsicu:activity",
    "iobroker:state",
    "ioverlander:metric1",
    "irs:metric1",
    "joule:cook",
    "journal:metric2",
    "juicebox:session",
    "kasa:plug",
    "kaya:metric0",
    "keep:note",
    "keg:inventory",
    "kegpunk:pour",
    "kerchunk:stream",
    "khan:metric1",
    "kindertales:attendance",
    "kinsa:reading",
    "knitcompanion:metric1",
    "kraken:trade",
    "lastfm:scrobble",
    "leakbot:alert",
    "leaksmart:sensor",
    "lego:metric2",
    "lemonade:metric0",
    "lesson:metric0",
    "lesson:metric4",
    "lidarr:release",
    "lifeadmin:document",
    "lifeadmin:metric0",
    "lifelog:metric3",
    "lifeos:metric0",
    "lifeos:metric1",
    "lifeos:metric5",
    "lifescore:metric0",
    "lifescore:metric3",
    "lifescore:metric6",
    "lightburn:job",
    "lightroom:metric0",
    "linear:issue",
    "linkedin:metric2",
    "local:metric3",
    "location:metric1",
    "loot:metric2",
    "loxone:audit",
    "lumen:metabolism",
    "mapmyfitness:activity",
    "mealime:metric0",
    "medbridge:metric0",
    "medication:metric1",
    "meditation:metric1",
    "medreminder:metric2",
    "merlin:sound",
    "meross:device",
    "meteobridge:summary",
    "microspend:metric0",
    "mobilityaid:metric0",
    "mobilityaid:status",
    "monica:metric0",
    "mood:metric0",
    "mooheat:alert",
    "mooring:metric2",
    "mortgage:metric0",
    "motus:tag",
    "mould:metric0",
    "move:metric0",
    "mtga:deck",
    "mtr:trace",
    "multimon:decode",
    "muse:session",
    "myswimpro:metric1",
    "neighborhood:metric2",
    "neptune:apex",
    "netatmo:weather",
    "netdata:alarm",
    "neurosity:focus",
    "nextcloud:activity",
    "nextdoor:metric0",
    "nina:weather",
    "nmea:metric0",
    "nospend:metric1",
    "note:metric2",
    "notion:page",
    "npc:metric1",
    "ntopng:flow",
    "nutrisense:glucose",
    "obd:metric1",
    "obico:detection",
    "obsidian:metric0",
    "octopus:agile",
    "octopus:ev",
    "onthesnow:metric2",
    "opendental:metric0",
    "openhab:event",
    "opensky:state",
    "opnsense:syslog",
    "outfit:metric1",
    "ovms:metric",
    "owlet:dream",
    "pantry:metric4",
    "paprika:metric3",
    "parkmobile:session",
    "passport:metric1",
    "peloton:metric1",
    "pentair:intellicenter",
    "personalcapital:networth",
    "personalslo:metric1",
    "personalslo:metric4",
    "personalweather:metric1",
    "petcube:video",
    "petinsurance:metric2",
    "petpace:vitals",
    "pharmacy:metric2",
    "photo:metric0",
    "phyn:plus",
    "pilates:metric3",
    "pkm:review",
    "planta:metric0",
    "plato:reading",
    "plexamp:play",
    "podcast:metric3",
    "pokernow:metric1",
    "polar:activity",
    "polar:hrv",
    "pomofocus:metric0",
    "pool:metric2",
    "poolmath:log",
    "portainer:stack",
    "portfolio:quote",
    "posture:metric0",
    "practice:metric0",
    "prayer:metric0",
    "prediction:metric0",
    "preflight:metric3",
    "prep:metric1",
    "prescription:metric3",
    "priceperuse:metric2",
    "procare:metric1",
    "prometheus:metric",
    "property:metric1",
    "prusafarm:printer",
    "psn:trophy",
    "pt:metric1",
    "pushband:set",
    "quest:metric1",
    "quest:metric6",
    "race:metric3",
    "raceresult:metric0",
    "racketpal:rally",
    "radarr:event",
    "radiosonde:track",
    "radoneye:reading",
    "rainbird:zone",
    "ravelry:metric0",
    "reading:metric0",
    "recycling:metric1",
    "reefpi:reading",
    "relationship:metric0",
    "release:metric2",
    "reno:metric0",
    "reno:metric1",
    "reno:metric2",
    "reno:metric3",
    "repair:metric3",
    "repetier:job",
    "ridewithgps:route",
    "ring:metric1",
    "rnode:packet",
    "roam:metric1",
    "roborock:metric0",
    "rocketmoney:metric1",
    "rome2rio:itinerary",
    "runkeeper:activity",
    "safecast:reading",
    "schwab:position",
    "scooter:metric1",
    "scripture:metric1",
    "scrypted:event",
    "scylla:detection",
    "sensibo:climate",
    "sequencegenerator:run",
    "setlist:metric3",
    "sharpcap:capture",
    "shelly:3em",
    "simplepractice:metric0",
    "simplisafe:event",
    "simplypiano:metric1",
    "simplyprint:job",
    "skate:metric2",
    "skin:metric1",
    "skincare:metric2",
    "skitracks:metric1",
    "slack:personal",
    "slopes:metric0",
    "smartcoop:status",
    "smartthings:schema",
    "smokeping:latency",
    "sneaker:metric3",
    "sneeze:metric3",
    "snug:jar",
    "soilwatch:moisture",
    "sonoff:relay",
    "spa:metric1",
    "spa:metric2",
    "speaking:metric3",
    "spire:breath",
    "spirit:metric2",
    "spoolman:spool",
    "stayfree:usage",
    "stellarium:session",
    "stockx:metric0",
    "strava:metric0",
    "streak:metric2",
    "streamlabs:water",
    "stripe:metric2",
    "supply:metric0",
    "surefeed:feeder",
    "surepetcare:flap",
    "surf:metric3",
    "suunto:workout",
    "swim:metric3",
    "swimcom:metric0",
    "swingtracker:swing",
    "swingvision:metric0",
    "symptom:metric1",
    "tabletopia:session",
    "tax:metric2",
    "tempest:lightning",
    "tensionboard:session",
    "tessie:vehicle",
    "thermapen:log",
    "thermoworks:cloud",
    "thinq:metric0",
    "thinq:metric1",
    "tidy:metric1",
    "tiller:txn",
    "timeline:metric4",
    "timeline:visit",
    "timery:entry",
    "titan:doser",
    "trackman:shot",
    "tradingcard:metric3",
    "traefik:access",
    "trainingpeaks:metric0",
    "trainingpeaks:metric1",
    "trainingpeaks:metric5",
    "trakt:scrobble",
    "transition:metric4",
    "trident:alk",
    "tridot:metric2",
    "trupanion:metric0",
    "trust:metric0",
    "turbotax:metric0",
    "twitch:vod",
    "untappd:checkin",
    "upliftdesk:metric1",
    "uptimekuma:monitor",
    "uradmonitor:reading",
    "usps:metric1",
    "utility:meter",
    "utility:payment",
    "utr:metric1",
    "uv:metric3",
    "vacuum:metric3",
    "vet:metric1",
    "vet:metric3",
    "vice:metric1",
    "victron:metric0",
    "vinyl:metric1",
    "vision:metric2",
    "vitals:metric2",
    "vivino:metric1",
    "vocab:metric1",
    "voicememo:metric2",
    "volunteer:metric0",
    "vrbo:metric1",
    "vrbo:metric5",
    "wag:walk",
    "wallbox:session",
    "wanderlog:stop",
    "wardrobe:metric0",
    "watch:metric2",
    "watch:metric3",
    "watchbox:metric1",
    "water:metric2",
    "weatherstation:metric0",
    "wheelchair:metric1",
    "wildlifeinsights:detection",
    "will:metric1",
    "wine:metric3",
    "wireguard:peer",
    "withings:ecg",
    "wyze:event",
    "wyze:sensor",
    "xp:metric3",
    "yousician:metric0",
    "yucata:game",
    "zapper:defi",
    "zocdoc:metric1",
    # cat-25 waves 7–8 — additional consumer sourcetypes
    "abrp:trip",
    "acaia:brew",
    "alexa:routine",
    "allergy:entry",
    "allowance:txn",
    "amazon:order",
    "ambee:pollen",
    "anomalyday:score",
    "anova:session",
    "antennapod:episode",
    "apex:reading",
    "applefitness:workout",
    "aqara:device",
    "backuprestore:test",
    "bambulab:job",
    "beanconqueror:brew",
    "beauty:product",
    "bgg:play",
    "birthday:spend",
    "blindmotor:state",
    "bodycomp:reading",
    "bookclub:meeting",
    "breathwork:session",
    "brewfather:coffee",
    "bridgebase:board",
    "calendar:freebusy",
    "canvas:assignment",
    "care:checkin",
    "care:geofence",
    "care:medication",
    "care:ops",
    "care:pendant",
    "cashback:event",
    "cbt:record",
    "chargepoint:session",
    "checkride:prep",
    "chesscom:game",
    "cloudflared:connector",
    "club:attendance",
    "cnc:coolant",
    "coin:item",
    "comic:item",
    "community:donation",
    "community:impact",
    "community:mutualaid",
    "community:shift",
    "compost:reading",
    "concept2:workout",
    "cook:smoker",
    "copilot:transaction",
    "coros:activity",
    "cpap:session",
    "daylio:entry",
    "decent:shot",
    "direwolf:packet",
    "discogs:item",
    "dnsleak:check",
    "documentscan:index",
    "doh:query",
    "eggcounter:event",
    "eighta:send",
    "eightsleep:sleep",
    "ekos:device",
    "ekos:scheduler",
    "elgato:keylight",
    "emby:session",
    "event:checklist",
    "event:deposit",
    "event:seating",
    "event:sync",
    "f3:card",
    "faith:attendance",
    "faith:fast",
    "faith:ops",
    "faith:retreat",
    "faith:rosary",
    "familylink:usage",
    "fi:activity",
    "filterwheel:event",
    "fireworks:noise",
    "fitness:segment",
    "flatlib:frame",
    "flickr:photo",
    "flight:export",
    "flightaware:flight",
    "flo:event",
    "flowhive:reading",
    "forage:observation",
    "forecast:calibration",
    "forecast:journal",
    "forecast:ops",
    "forecast:personal",
    "forecast:resolution",
    "forscore:practice",
    "freelance:hours",
    "freelance:invoice",
    "freelance:lead",
    "freelance:tax",
    "ft8:spot",
    "furbo:event",
    "garmin:bodybattery",
    "garmin:zumo",
    "genealogy:cemetery",
    "genealogy:hint",
    "genealogy:ops",
    "genealogy:photo",
    "giftbudget:item",
    "goatcare:event",
    "goattag:scan",
    "golf:round",
    "googlehome:event",
    "googleworkspace:license",
    "govee:soil",
    "gymnastics:skill",
    "habit:alcohol",
    "habit:caffeine",
    "habit:fasting",
    "habit:screen",
    "handicap:index",
    "hangboard:protocol",
    "hatch:routine",
    "health:glucose",
    "health:lab",
    "health:ops",
    "health:pt",
    "health:symptom",
    "hearingaid:battery",
    "hibp:alert",
    "hibp:breach",
    "hoa:fee",
    "holidaytimer:event",
    "homeconnect:dishwasher",
    "hunt:map",
    "hvacfilter:reading",
    "immich:job",
    "inat:observation",
    "inreach:message",
    "instantpot:cook",
    "ioverlander:place",
    "ispindel:reading",
    "js8call:message",
    "kaya:session",
    "khan:sat",
    "knitcompanion:counter",
    "kubernetes:pod",
    "language:immersion",
    "language:lesson",
    "language:review",
    "language:sync",
    "language:tutor",
    "laserweb:job",
    "launchmonitor:shot",
    "levels:glucose",
    "libre:glucose",
    "lichess:tournament",
    "lifeos:beeminder",
    "lifeos:habit",
    "lifeos:okr",
    "lifeos:ops",
    "lifeos:service",
    "lifeos:streak",
    "lifx:state",
    "lightroom:photo",
    "logseq:task",
    "makerspace:visit",
    "marina:power",
    "marine:ais",
    "marine:battery",
    "marine:export",
    "marinetraffic:vessel",
    "matter:event",
    "maytronics:robot",
    "mealplan:item",
    "meater:cook",
    "memory:journal",
    "memory:ops",
    "memory:photo",
    "memory:postcard",
    "memory:takeout",
    "migraine:entry",
    "mister:cycle",
    "monarch:transaction",
    "moonboard:session",
    "mopeka:tank",
    "mortgage:rate",
    "mothtrap:session",
    "music:bandcamp",
    "music:distribution",
    "music:ops",
    "music:project",
    "music:streaming",
    "nanit:sleep",
    "nanoleaf:scene",
    "nestprotect:event",
    "nina:autofocus",
    "nina:sequence",
    "nintendo:play",
    "noaaapt:pass",
    "obd:bike",
    "obsidian:note",
    "obsidian:stats",
    "obsidian:sync",
    "ogs:game",
    "openwrt:syslog",
    "oura:stress",
    "ourhome:chore",
    "outdoor:queue",
    "outdoor:trip",
    "paperless:document",
    "passport:status",
    "passwordage:account",
    "pendant:test",
    "personalsla:status",
    "personalweather:daily",
    "personalweather:mood",
    "personalweather:sleep",
    "personalweather:steps",
    "petkit:status",
    "petlibro:feeder",
    "pharmacy:refill",
    "phd2:guide",
    "plaid:account",
    "plaid:investment",
    "plaid:transaction",
    "planta:plant",
    "platesolve:run",
    "plugshare:checkin",
    "pokerhome:session",
    "pokernow:session",
    "pomofocus:session",
    "powermeter:ride",
    "pricetrack:alert",
    "prometronome:session",
    "property:listing",
    "propertytax:installment",
    "prusaconnect:printer",
    "pskreporter:spot",
    "race:bib",
    "race:split",
    "racechrono:lap",
    "raceresult:event",
    "rachio:zone",
    "racket:session",
    "ravelry:project",
    "ravelry:stash",
    "reading:book",
    "reading:highlight",
    "reading:review",
    "reading:sync",
    "relationship:ritual",
    "reno:gantt",
    "reno:ops",
    "reno:permit",
    "reno:photo",
    "reno:punchlist",
    "reolink:event",
    "reptilethermostat:event",
    "research:paper",
    "retroarch:session",
    "rever:ride",
    "revzilla:order",
    "ride:charge",
    "ride:export",
    "ride:incident",
    "ride:session",
    "ring:event",
    "rivian:vehicle",
    "roam:daily",
    "rocketmoney:subscription",
    "roofleak:event",
    "rpg:character",
    "rpg:combat",
    "rpg:initiative",
    "rpg:ops",
    "rpg:session",
    "runbook:checklist",
    "runningclub:session",
    "schoolcalendar:event",
    "seneye:reading",
    "sense:device",
    "sensorpush:climate",
    "sharedcalendar:event",
    "shuttercount:camera",
    "simbrief:plan",
    "simplypiano:session",
    "sleeptalk:event",
    "stairlift:service",
    "stamp:item",
    "steam:activity",
    "steamdeck:session",
    "stretchly:break",
    "stringing:service",
    "stripe:invoice",
    "stryd:run",
    "style:audit",
    "style:cleaning",
    "style:shoes",
    "style:wardrobe",
    "sump:humidity",
    "surf:forecast",
    "sustain:audit",
    "sustain:compost",
    "sustain:repair",
    "sustain:share",
    "sustain:solar",
    "swingvision:session",
    "tailscale:netmap",
    "teatimer:session",
    "therapy:homework",
    "thermometer:reading",
    "thinq:dryer",
    "thinq:washer",
    "thread:router",
    "tide:table",
    "tilt:hydrometer",
    "tiplog:shift",
    "todoist:task",
    "toggl:timeentry",
    "tolltag:trip",
    "tonalenergy:tuning",
    "touchpoint:log",
    "tractive:location",
    "tradfri:device",
    "trailcam:label",
    "trainerroad:workout",
    "trainingpeaks:workout",
    "udisc:round",
    "unifiprotect:event",
    "upliftdesk:desk",
    "utility:bill",
    "utility:rate",
    "utilityrate:tariff",
    "utr:rating",
    "vatsim:session",
    "vaultwarden:event",
    "victron:telemetry",
    "voter:registration",
    "wahoo:workout",
    "warranty:registration",
    "watch:item",
    "wheelchair:battery",
    "whoop:day",
    "xbox:activity",
    "yousician:lesson",
    "zettel:note",
    "zigbee2mqtt:bridge",
}


# ---------------------------------------------------------------------------
# Macros from Splunk's published Enterprise Security Content Update
# (`splunk/security_content`, Apache-2.0). The catalogue here covers
# the macros most frequently invoked from detection SPL — keeping it
# narrow because every macro added here weakens the audit's ability
# to surface real hallucinations.
# ---------------------------------------------------------------------------
WELL_KNOWN_MACROS: set[str] = {
    # ------------------------------------------------------------------
    # Splunk Common Information Model (CIM) add-on — Splunkbase 1621
    # ------------------------------------------------------------------
    # ``cim_<datamodel>_indexes`` macros are the canonical entry points
    # CIM authors expect every dashboard / detection to use as the
    # data-source filter (lets the customer point each data model at
    # the indexes that hold their data without rewriting SPL). They are
    # documented in `docs.splunk.com/Documentation/CIM/.../Usage`.
    "cim_Alerts_indexes",
    "cim_Application_State_indexes",
    "cim_Authentication_indexes",
    "cim_Change_indexes",
    "cim_Compute_Inventory_indexes",
    "cim_DLP_indexes",
    "cim_Databases_indexes",
    "cim_Email_indexes",
    "cim_Endpoint_indexes",
    "cim_Event_Signatures_indexes",
    "cim_IDS_indexes",
    "cim_Inventory_indexes",
    "cim_JVM_indexes",
    "cim_Malware_indexes",
    "cim_Network_Resolution_indexes",
    "cim_Network_Sessions_indexes",
    "cim_Network_Traffic_indexes",
    "cim_Performance_indexes",
    "cim_Splunk_Audit_indexes",
    "cim_Ticket_Management_indexes",
    "cim_Updates_indexes",
    "cim_Vulnerabilities_indexes",
    "cim_Web_indexes",
    # ------------------------------------------------------------------
    # Splunk Enterprise utility macros (commonly published in dashboards
    # and the Splunk Lantern library; not strictly an add-on but every
    # mature production environment carries them or an equivalent).
    # ------------------------------------------------------------------
    # IP -> geo enrichment used in many Splunk-supplied compliance and
    # security dashboards. Documented in the Splunk Enterprise
    # Search Reference under the `iplocation` command guidance.
    "get_geolocation",
    # ------------------------------------------------------------------
    # Cisco ThousandEyes App for Splunk — Splunkbase 7719
    # ------------------------------------------------------------------
    # Index-aliasing macros the TA defines in `default/macros.conf`
    # so dashboards work against whichever index the deployer routes
    # ThousandEyes data into. See ``ta_cisco_thousandeyes`` README.
    "event_index",
    "path_viz_index",
    # Time / event helpers
    "security_content_ctime",
    "security_content_summariesonly",
    "summariesonly",
    "drop_dm_object_name",
    # Index aliases (every detection author defines these per environment;
    # they're also the exact list ESCU expects to be macroed):
    "wineventlog_security",
    "wineventlog_system",
    "wineventlog_application",
    "wineventlog_dns",
    "powershell",
    "sysmon",
    "azure_monitor_aad",
    "google_gcp_pubsub_message",
    "amazon_security_lake",
    "cloudtrail",
    "linux_audit",
    "linux_secure",
    "kubernetes_metrics",
    "kubernetes_objects",
    "stream_dns",
    "stream_http",
    "stream_index",
    "okta",
    "okta_im2",
    "o365_management_activity",
    "office365_management_activity",
    "github",
    "github_audit",
    "github_actions",
    "gws_reports",
    "ms_defender",
    "ms_defender_advanced_hunting",
    "circleci",
    "gitlab",
    # Process-related ESCU macros
    "process_wmic",
    "process_powershell",
    "process_net",
    "process_cmd",
    "process_rundll32",
    "process_regsvr32",
    "process_mshta",
    "process_certutil",
    "process_bitsadmin",
    "process_schtasks",
    "process_at",
    "process_psexec",
    "process_reg",
    "process_runas",
    "process_taskhost",
    "process_taskhostw",
    "process_winrshost",
    "process_winrm",
    "process_wsmprovhost",
    # Notable / risk framework macros (Splunk Enterprise Security)
    "notable",
    "risk",
    "incident_review",
    "es_notable",
    # MCP server data macros (ESCU adds these for MCP detections)
    "mcp_server",
    # Common URL toolbox macros (Splunk Add-on for URL Toolbox)
    "ut_parse",
    "ut_parse_extended",
    "ut_levenshtein",
    "ut_shannon",
    # AWS / Cloudtrail macros widely used in ESCU
    "comment",
}


# ---------------------------------------------------------------------------
# Indexes that always exist on a Splunk instance once the platform or a
# top-1 add-on is installed. These join ``BUILTIN_FIELD_TOKENS`` (Splunk
# core internal indexes) so the audit doesn't flag tenant-agnostic
# names like ``notable`` / ``risk`` / ``cim_modactions``.
# ---------------------------------------------------------------------------
WELL_KNOWN_INDEXES: set[str] = {
    # Splunk Enterprise Security
    "notable",
    "risk",
    "cim_modactions",
    "ioc",
    "threat_activity",
    "endpoint_summary",
    # Splunk IT Service Intelligence
    "itsi_summary",
    "itsi_grouped_alerts",
    "itsi_tracked_alerts",
    "itsi_kpi_summary",
    # Splunk Universal Forwarder boundary
    "summary",
}
