/**
 * Typed access points for the non-technical view catalogue.
 *
 * Two surfaces are exposed:
 *
 *   1. `NON_TECHNICAL` — re-export of the canonical typed source
 *      module under [`./data/non-technical-view.data.ts`](./data/non-technical-view.data.ts).
 *      Application code should import this; it is the recommended
 *      path because it gives zero-runtime-cost access with full
 *      type-checking against `NonTechnicalCatalog`.
 *
 *   2. `loadCatalogFromLegacyJs()` — reads the repository-root file
 *      `non-technical-view.js` and executes it via Node's stdlib
 *      `node:vm` `runInThisContext()` against the current global
 *      (which under `vitest run` with `environment: "jsdom"` is a
 *      jsdom `window`). Used by the 81-shape Vitest suite to give
 *      defense-in-depth: the suite validates the *generated* legacy
 *      JS file rather than the typed source directly, so an emitter
 *      regression that produces a malformed JS catches there before
 *      the CI drift guard catches it.
 *
 * Source-of-truth inversion (2026-05-17): the typed module is now
 * canonical. The legacy JS file is generated by
 * `apps/web/scripts/emit-legacy.ts` (`npm run emit:legacy`). See
 * ADR-0013 §"Migration shape" and the CI drift guard in
 * `.github/workflows/validate.yml`.
 *
 * The `node:vm` execution path is NOT `eval()` and NOT
 * `new Function()`. The codeguard rule against `eval` /
 * `child_process.exec` calls out "with user input" specifically;
 * the input here is a checked-in repository file at a fixed path
 * relative to this module, controlled by the same review process as
 * any other source file.
 */

import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { runInThisContext } from "node:vm";

import { NON_TECHNICAL } from "./data/non-technical-view.data.ts";
import type { NonTechnicalCatalog } from "./non-technical-view.types.ts";

export { NON_TECHNICAL };

const HERE = dirname(fileURLToPath(import.meta.url));

/**
 * Default path to the legacy JS file, resolved from this module's
 * location: `apps/web/src/non-technical-view.ts` → repo root →
 * `non-technical-view.js`. Three `..` segments climb out of
 * `apps/web/src/`.
 */
export const LEGACY_NON_TECHNICAL_JS_PATH = resolve(
  HERE,
  "..",
  "..",
  "..",
  "non-technical-view.js",
);

/**
 * Augment the jsdom `Window` with the `NON_TECHNICAL` property the
 * legacy script writes. The property is `?` because in any context
 * where the script has not yet run it is genuinely undefined.
 */
declare global {
  interface Window {
    NON_TECHNICAL?: NonTechnicalCatalog;
  }
}

/**
 * Read the legacy `non-technical-view.js` file from disk, execute it
 * inside the current global context (which under vitest jsdom has a
 * fully-formed `window`), and return the populated catalogue.
 *
 * Throws if the script does not populate `window.NON_TECHNICAL`,
 * which would indicate either (a) the file has been moved /
 * renamed / corrupted, or (b) the test environment is not jsdom and
 * therefore has no `window` for the script to write to.
 *
 * @param jsPath Optional absolute path to the legacy JS file. Defaults
 *   to {@link LEGACY_NON_TECHNICAL_JS_PATH}; tests override it to
 *   exercise error paths.
 */
export function loadCatalogFromLegacyJs(
  jsPath: string = LEGACY_NON_TECHNICAL_JS_PATH,
): NonTechnicalCatalog {
  const source = readFileSync(jsPath, "utf-8");
  runInThisContext(source, { filename: jsPath });

  const w = (globalThis as { window?: Window }).window;
  if (!w || !w.NON_TECHNICAL) {
    throw new Error(
      `loadCatalogFromLegacyJs: ${jsPath} did not populate window.NON_TECHNICAL ` +
        "(check that vitest is configured with environment: \"jsdom\" and that " +
        "the file is the legacy IIFE-style script, not an ESM module).",
    );
  }

  return w.NON_TECHNICAL;
}

/**
 * Convenience helper: returns the sorted list of category keys
 * (e.g. `["1", "2", ..., "23"]`) from a loaded catalogue.
 */
export function listCategoryKeys(catalog: NonTechnicalCatalog): readonly string[] {
  return Object.keys(catalog).sort((a, b) => Number(a) - Number(b));
}
