[package]
id = imucl
check_for_updates = 0

[ui]
label = Infrastructure & Security Use Case Library
is_visible = 1
show_in_launcher = 1

[launcher]
author = Splunk Monitoring Use Case Repository
description = Browse and implement infrastructure, cloud, application, and security monitoring use cases. Embedded Use Case Library dashboard (v0.0.1).
version = 0.0.1

[install]
build = 1
is_configured = 1
