#!/usr/bin/env python3
"""One-off generator for cat-05 proxy UCs — run from repo root: python3 scripts/_gen_proxy_ucs.py"""
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CAT05 = os.path.join(REPO, "content/cat-05-network-infrastructure")
SCHEMA = "../../schemas/uc.schema.json"
os.makedirs(CAT05, exist_ok=True)


def save(path, d):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(d, f, ensure_ascii=False, indent=2)
        f.write("\n")


def base(**kw):
    d = {
        "$schema": SCHEMA,
        "cimModels": ["N/A"],
        "lastReviewed": "2026-04-24",
        "splunkVersions": ["9.2+", "Cloud"],
        "reviewer": "catalog-team",
        "status": "draft",
        "splunkPillar": "Observability",
    }
    d.update(kw)
    return d


def row(uid, title, crit, diff, mtypes, spl, ds, impl, ref, eq, grandma, desc, value):
    save(
        os.path.join(CAT05, f"UC-{uid}.json"),
        base(
            id=uid,
            title=title,
            criticality=crit,
            difficulty=diff,
            monitoringType=mtypes,
            dataSources=ds,
            app="Splunk Universal Forwarder, Splunk Connect for Syslog, or HTTP Event Collector; `props.conf`/`transforms.conf` for listed sourcetypes",
            spl=spl,
            description=desc,
            value=value,
            implementation=impl,
            visualization="Time series for rates and latency, top/dedup for hotspots, single-value alerts on health thresholds.",
            references=[{"title": "Vendor documentation", "url": ref}],
            equipment=[eq],
            grandmaExplanation=grandma,
        ),
    )


def main():
    # HAProxy 5.14.1 - 8
    row(
        "5.14.1",
        "HAProxy Backend Server Health Check Failures",
        "critical",
        "beginner",
        ["Availability", "Performance"],
        'index=proxy sourcetype="haproxy:http"\n| where status >= 500 OR match(_raw, "(?i)NOLB|no server") OR match(_raw, "(?i)layer7 invalid")\n| stats count by backend, server\n| sort - count',
        "`index=proxy` `sourcetype=haproxy:http` default TCP/HTTP log format; `haproxy:syslog` mirror",
        "Forward HAProxy logs via syslog or UF file tail. Map `backend`/`server` fields per HAProxy 2.8 `log-format`. Correlate with `haproxy:stats` CSV from `show stat`.",
        "https://docs.haproxy.org/2.8/configuration.html#8.2.1",
        "haproxy",
        "We see when HAProxy marks real servers unhealthy before users flood the help desk.",
        "Backend health checks prevent traffic to failed nodes; log evidence shows which farm member and protocol failed first.",
        "Cuts time to restore origin pools by pinpointing DOWN transitions and related 5xx.",
    )
    row(
        "5.14.2",
        "HAProxy Connection Retry and Redispatch Volume",
        "high",
        "intermediate",
        ["Resilience", "Performance"],
        'index=proxy sourcetype="haproxy:http"\n| regex field=_raw "(?i)retry=(?<retry>\\d+)"\n| stats sum(retry) as retries by backend, server\n| where retries > 100',
        "`index=proxy` `sourcetype=haproxy:http` with optional `%rc`/`%rd` style captures in `log-format`",
        "Extend `log-format` to include retry/redispatch counters; validate with `show stat`. Baseline per service.",
        "https://docs.haproxy.org/2.8/configuration.html#log-format",
        "haproxy",
        "We count retries so flaky backends are fixed before errors spread.",
        "Retries absorb brief faults but high volume masks systemic overload or brownouts.",
        "Surfaces upstream instability that averages hide until SLAs break.",
    )
    row(
        "5.14.3",
        "HAProxy Queue Time vs Response Time Saturation Ratio",
        "high",
        "advanced",
        ["Performance", "Capacity"],
        'index=proxy sourcetype="haproxy:http"\n| eval Tw=tonumber(Wait), Tr=tonumber(Response)\n| eval q_ratio=if(Tr>0, round(Tw/Tr,3), null())\n| where Tw > 50 AND q_ratio > 0.5\n| timechart span=5m perc95(q_ratio) by backend',
        "`index=proxy` `sourcetype=haproxy:http` timed fields `Tw` (queue) and `Tr` (response) in TCP log format",
        "Confirm millisecond units in `props.conf`. Tune ratio threshold per API; pair with server `cur_sess`.",
        "https://www.haproxy.com/blog/the-four-golden-signals-for-haproxy/",
        "haproxy",
        "We tell if delays are from waiting in HAProxy versus slow application code.",
        "Queue-heavy latency means the proxy or servers cannot dequeue fast enough even if app CPU is fine.",
        "Directs tuning at maxconn, threads, or origin scale instead of micro-optimizing code alone.",
    )
    row(
        "5.14.4",
        "HAProxy SSL/TLS Handshake Failure Rate",
        "high",
        "intermediate",
        ["Security", "Availability"],
        'index=proxy sourcetype="haproxy:http"\n| regex _raw="(?i)(SSL handshake failure|verify error|alert unknown ca|alert certificate)"\n| bin _time span=5m\n| stats count by frontend, _time\n| where count > 20',
        "`index=proxy` `sourcetype=haproxy:http` or `haproxy:syslog` TLS diagnostics",
        "Enable sufficient TLS logging without secrets. Join failure spikes with certificate inventory expiry.",
        "https://docs.haproxy.org/2.8/configuration.html#5.1",
        "haproxy",
        "We catch certificate and cipher problems at the load balancer.",
        "TLS failures block whole cohorts of clients and often precede major incidents after renewals.",
        "Protects partner and mobile traffic that is sensitive to cipher and chain changes.",
    )
    row(
        "5.14.5",
        "HAProxy Stick-Table and Rate-Limit Table Pressure",
        "medium",
        "advanced",
        ["Security", "Performance"],
        'index=proxy sourcetype="haproxy:syslog"\n| regex _raw="(?i)(stick-table|gpc0|rate-limit|table_full)"\n| stats count by host\n| where count >= 1',
        "`index=proxy` `sourcetype=haproxy:syslog` HAProxy notices mirrored to syslog",
        "Size `stick-table` with `size` and `expire` appropriate to QPS; alert on `table_full` class messages.",
        "https://docs.haproxy.org/2.8/configuration.html#stick-table",
        "haproxy",
        "We detect when tracking tables fill and rate limits skew.",
        "Full stick-tables silently change traffic steering and security posture.",
        "Keeps bot defenses and ACL stickiness predictable under attack.",
    )
    row(
        "5.14.6",
        "HAProxy HTTP Compression Ratio Effectiveness",
        "low",
        "intermediate",
        ["Performance", "Cost"],
        'index=proxy sourcetype="haproxy:http"\n| eval cin=tonumber(comp_in), cout=tonumber(comp_out)\n| eval ratio=if(cin>0, round(100*cout/cin,1), null())\n| timechart span=1h avg(ratio) by frontend',
        "`index=proxy` `sourcetype=haproxy:http` with `comp_in`/`comp_out` from custom `log-format`",
        "Add compression byte fields per HAProxy docs; document field order for parsers.",
        "https://docs.haproxy.org/2.8/configuration.html#compression",
        "haproxy",
        "We verify compression saves bandwidth as expected.",
        "Compression reduces egress cost until misconfiguration disables it for large JSON.",
        "Quantifies CDN and origin offload ROI.",
    )
    row(
        "5.14.7",
        "HAProxy ACL-Based Traffic Routing Audit",
        "medium",
        "intermediate",
        ["Audit", "Security"],
        'index=proxy sourcetype="haproxy:http"\n| stats count by fe_name, be_name\n| sort - count\n| head 40',
        "`index=proxy` `sourcetype=haproxy:http` with frontend/backend names from log-format",
        "Add stable rule identifiers for regulated splits; scrub URIs with PII.",
        "https://docs.haproxy.org/2.8/configuration.html#7",
        "haproxy",
        "We prove which HAProxy paths handled which slice of traffic.",
        "Routing audits support tenant isolation and forensic reconstruction.",
        "Demonstrates control effectiveness to risk teams without packet capture.",
    )
    row(
        "5.14.8",
        "HAProxy Frontend Connection Limiting and Denials",
        "high",
        "advanced",
        ["Security", "Availability"],
        'index=proxy sourcetype="haproxy:http"\n| regex _raw="(?i)(denied by tcp-request connection|too many connections)"\n| bin _time span=1m\n| stats count by frontend, _time\n| where count > 50',
        "`index=proxy` `sourcetype=haproxy:http` connection-layer deny messages",
        "Set intentional `maxconn`; baseline deny velocity to catch DDoS or misconfigured clients.",
        "https://docs.haproxy.org/2.8/configuration.html#maxconn",
        "haproxy",
        "We see when HAProxy refuses connections to protect the farm.",
        "Protective limits look like outages if unexplained; logging proves intent.",
        "Separates attack traffic from true capacity exhaustion.",
    )

    # Varnish 5.14.9 - 22
    row(
        "5.14.9",
        "Varnish Cache Hit Ratio Trending (HIT vs MISS vs PASS)",
        "high",
        "intermediate",
        ["Performance", "Capacity"],
        'index=proxy sourcetype="varnish:vsl"\n| eval hit=if(match(_raw, "(?i)\\bHIT\\b|VCL_hit"),1,0)\n| eval miss=if(match(_raw, "(?i)VCL_miss|\\bMISS\\b"),1,0)\n| eval pass=if(match(_raw, "(?i)VCL_pass|\\bPASS\\b"),1,0)\n| bin _time span=5m\n| stats sum(hit) as hits sum(miss) as misses sum(pass) as passes\n| eval hit_ratio=round(100*hits/(hits+misses+passes+0.001),2)\n| timechart span=5m avg(hit_ratio) as hit_pct',
        "`index=proxy` `sourcetype=varnish:vsl` (Varnish Shared Log / `varnishncsa` VSL tags)",
        "Ship VSL via `varnishncsa` custom format or HEC JSON lines. For counter view add `varnish:stats` companion panel.",
        "https://varnish-cache.org/docs/trunk/users-guide/intro.html",
        "varnish",
        "We track how often Varnish serves from cache versus the origin.",
        "Hit ratio ties origin cost and latency directly to cache effectiveness.",
        "Guides TTL, grace, and storage tuning with measurable outcomes.",
    )
    row(
        "5.14.10",
        "Varnish Backend Health Probe and Fetch Failures",
        "critical",
        "beginner",
        ["Availability"],
        'index=proxy sourcetype="varnish:vsl"\n| regex _raw="(?i)(Backend fetch failed|FetchError|no healthy backend)"\n| stats count by backend\n| sort - count',
        "`index=proxy` `sourcetype=varnish:vsl` backend errors; `varnish:log` for notices",
        "Enable backend polling; include `Backend` VSL tags in forwarded logs.",
        "https://varnish-cache.org/docs/trunk/reference/vcl-backend-health.html",
        "varnish",
        "We alert when Varnish cannot reach origin servers.",
        "Probe failures starve users even when edge CPUs look idle.",
        "Triggers fast failover or capacity before SLAs breach.",
    )
    row(
        "5.14.11",
        "Varnish Thread Pool Queue Length (thread_queue_len)",
        "high",
        "advanced",
        ["Performance"],
        'index=proxy sourcetype="varnish:stats"\n| eval tql=tonumber(thread_queue_len)\n| where tql > 0\n| timechart span=1m max(tql) as thread_queue_len by host',
        "`index=proxy` `sourcetype=varnish:stats` JSON from `varnishstat -j`",
        "Poll every 30s via scripted input to HEC; flatten counter names per version.",
        "https://varnish-cache.org/docs/trunk/reference/varnishstat.html",
        "varnish",
        "We watch Varnish worker backlog that slows every request.",
        "Queued threads mean requests wait before VCL runs.",
        "Early warning for thread pool misconfiguration or CPU starvation.",
    )
    row(
        "5.14.12",
        "Varnish LRU Nuked Objects Rate",
        "medium",
        "intermediate",
        ["Capacity"],
        'index=proxy sourcetype="varnish:stats"\n| eval nuked=tonumber(n_lru_nuked)\n| sort 0 host _time\n| streamstats window=2 global=f last(nuked) as p_n by host\n| eval d=nuked-p_n\n| timechart span=5m sum(d) as lru_nukes by host',
        "`index=proxy` `sourcetype=varnish:stats` counter `n_lru_nuked`",
        "Correlate spikes with origin load; revisit storage size and TTL policies.",
        "https://varnish-cache.org/docs/trunk/users-guide/storage-backends.html",
        "varnish",
        "We see when Varnish evicts cache entries to free space.",
        "Rising nukes predict hit ratio collapse and origin storms.",
        "Informs malloc/file storage sizing decisions.",
    )
    row(
        "5.14.13",
        "Varnish Grace and Keep Serving Stale Content Frequency",
        "medium",
        "intermediate",
        ["Performance", "Reliability"],
        'index=proxy sourcetype="varnish:vsl"\n| regex _raw="(?i)(grace|stale|hit-for-pass)"\n| bin _time span=15m\n| stats count by host, _time',
        "`index=proxy` `sourcetype=varnish:vsl` grace or HFM related VSL lines",
        "Tune thresholds against editorial SLOs; document VCL `grace`/`keep`.",
        "https://varnish-cache.org/docs/trunk/users-guide/vcl-grace.html",
        "varnish",
        "We measure how often users receive intentionally stale responses.",
        "Stale serving shields origins but can confuse content owners if unexplained.",
        "Balances resilience versus freshness commitments.",
    )
    row(
        "5.14.14",
        "Varnish Ban List Growth and Lurker Lag",
        "medium",
        "advanced",
        ["Performance", "Operational"],
        'index=proxy sourcetype="varnish:stats"\n| eval bans=tonumber(bans), done=tonumber(bans_completed)\n| eval lag=bans-done\n| where lag > 1000\n| table _time, host, bans, done, lag',
        "`index=proxy` `sourcetype=varnish:stats` ban counters",
        "Investigate slow lurker or excessive `ban()` calls from publishers.",
        "https://varnish-cache.org/docs/trunk/users-guide/purging.html",
        "varnish",
        "We make sure cache invalidation queues keep up.",
        "Ban lag leaves outdated objects live especially on busy news sites.",
        "Protects editorial correctness after publishes.",
    )
    row(
        "5.14.15",
        "Varnish ESI Fragment Error Rate",
        "high",
        "intermediate",
        ["Fault", "Performance"],
        'index=proxy sourcetype="varnish:vsl"\n| regex _raw="(?i)(ESI.*error|include.*failed)"\n| stats count by host\n| where count > 10',
        "`index=proxy` `sourcetype=varnish:vsl` ESI parser errors",
        "Limit verbose ESI debug to non-prod; aggregate counts in prod.",
        "https://varnish-cache.org/docs/trunk/users-guide/esi.html",
        "varnish",
        "We catch broken edge includes that ruin page assembly.",
        "ESI failures create partial pages that are hard to spot in averages.",
        "Speeds collaboration between CDN and app teams.",
    )
    row(
        "5.14.16",
        "Varnish Workspace Client Overflow Detection",
        "high",
        "advanced",
        ["Fault", "Performance"],
        'index=proxy sourcetype="varnish:log"\n| regex _raw="(?i)workspace.*overflow|WS.*overflow"\n| stats count by host\n| where count >= 1',
        "`index=proxy` `sourcetype=varnish:log` stderr/syslog workspace errors",
        "Raise `workspace_client` and hunt oversized cookies or headers.",
        "https://varnish-cache.org/docs/trunk/reference/varnishd.html",
        "varnish",
        "We find Varnish errors from headers or cookies that are too large.",
        "Workspace overflows drop transactions abruptly.",
        "Prevents mysterious 503s during marketing campaigns with huge headers.",
    )
    row(
        "5.14.17",
        "Varnish Object TTL Distribution Sampling",
        "low",
        "advanced",
        ["Analytics", "Capacity"],
        'index=proxy sourcetype="varnish:vsl"\n| rex field=_raw "TTL:\\s+(?<ttl>\\d+)"\n| where isnotnull(ttl)\n| bin ttl span=30\n| stats count by ttl',
        "`index=proxy` `sourcetype=varnish:vsl` TTL VSL lines (sampled)",
        "Sample high-volume VSL 1:N to control license cost.",
        "https://varnish-cache.org/docs/trunk/users-guide/increasing-your-hitrate.html",
        "varnish",
        "We study how long objects live in cache.",
        "TTL spread explains hit ratio and origin offload variance.",
        "Supports data-driven cache policy reviews.",
    )
    row(
        "5.14.18",
        "Varnish Backend Connection Reuse Signals",
        "medium",
        "intermediate",
        ["Performance"],
        'index=proxy sourcetype="varnish:stats"\n| eval conn=tonumber(backend_conn), reuse=tonumber(backend_recycle)\n| eval reuse_ratio=if(conn>0, round(100*reuse/conn,1), null())\n| timechart span=15m avg(reuse_ratio) by host',
        "`index=proxy` `sourcetype=varnish:stats` backend connection counters",
        "Low reuse may indicate TLS handshake storms toward origin.",
        "https://varnish-cache.org/docs/trunk/reference/varnishstat.html",
        "varnish",
        "We verify warm backend connections are reused.",
        "Poor reuse increases latency and CPU on both sides.",
        "Guides keep-alive and TLS session settings.",
    )
    row(
        "5.14.19",
        "Varnish SMA Allocator Free Ratio Watch",
        "medium",
        "advanced",
        ["Capacity"],
        'index=proxy sourcetype="varnish:stats"\n| eval alloc=tonumber(sma_bytes_allocated), free=tonumber(sma_bytes_free)\n| eval free_pct=if((alloc+free)>0, round(100*free/(alloc+free),1), null())\n| where free_pct > 40\n| table host, alloc, free, free_pct',
        "`index=proxy` `sourcetype=varnish:stats` SMA memory gauges (`sma0` naming varies)",
        "Map counter names per version; plan storage migration if chronic fragmentation.",
        "https://varnish-cache.org/docs/trunk/users-guide/storage-backends.html",
        "varnish",
        "We watch memory fragmentation that can reduce hit rate.",
        "Fragmentation silently shrinks effective cache space.",
        "Triggers proactive rebuilds or storage backend changes.",
    )
    row(
        "5.14.20",
        "Varnish Pipe Session Bypass Trending",
        "medium",
        "intermediate",
        ["Performance", "Analytics"],
        'index=proxy sourcetype="varnish:vsl"\n| regex _raw="(?i)VCL_pipe|Link\\s+pipe"\n| bin _time span=5m\n| stats count as pipe_sess by host, _time',
        "`index=proxy` `sourcetype=varnish:vsl` pipe transactions",
        "Pipe mode disables caching for those requests; watch WebSocket or upload paths.",
        "https://varnish-cache.org/docs/trunk/users-guide/vcl-pipe.html",
        "varnish",
        "We track requests that skip caching entirely.",
        "Unexpected pipe volume loads origin more than dashboards suggest.",
        "Explains origin spikes during large uploads.",
    )
    row(
        "5.14.21",
        "Varnish VCL Reload and Compilation Errors",
        "critical",
        "intermediate",
        ["Change", "Fault"],
        'index=proxy sourcetype="varnish:log"\n| regex _raw="(?i)(VCL compilation failed|syntax error in.*vcl)"\n| stats count by host, _raw\n| where count >= 1',
        "`index=proxy` `sourcetype=varnish:log` management stderr from reload",
        "Page immediately on compile failure in production paths.",
        "https://varnish-cache.org/docs/trunk/users-guide/vcl-separate.html",
        "varnish",
        "We catch bad VCL deploys before they take the cache offline.",
        "Compile errors during reloads can strand traffic on old VCL or stop updates.",
        "Protects release pipelines that touch edge logic.",
    )
    row(
        "5.14.22",
        "Varnish Gzip Compression Ratio by Content Type",
        "low",
        "intermediate",
        ["Performance", "Cost"],
        'index=proxy sourcetype="varnish:vsl"\n| rex field=_raw "Content-Type:\\s+(?<ctype>[^\\s;]+)"\n| stats count by ctype',
        "`index=proxy` `sourcetype=varnish:vsl` response header lines (sampled)",
        "Pair with byte counters if available; sample to control volume.",
        "https://varnish-cache.org/docs/trunk/users-guide/compression.html",
        "varnish",
        "We compare compression coverage across content types.",
        "JSON and text compress better than images; mis-tuned filters waste CPU.",
        "Optimizes CPU spend versus egress savings.",
    )

    # Squid 5.14.23 - 35
    row(
        "5.14.23",
        "Squid Cache Hit Ratio by Request Method",
        "high",
        "intermediate",
        ["Performance"],
        'index=proxy sourcetype="squid:access"\n| eval meth=coalesce(request_method, cs_method)\n| eval is_hit=if(match(code, "TCP_(HIT|MEM_HIT|REFRESH_HIT)"),1,0)\n| stats sum(is_hit) as hits count as total by meth\n| eval hit_pct=round(100*hits/total,2)\n| table meth, hits, total, hit_pct',
        "`index=proxy` `sourcetype=squid:access` native log with Squid result `code`",
        "Use `cache_access_log` with Splunk-friendly format; map `%>hs` status and `%rm` method in `props.conf`.",
        "http://www.squid-cache.org/Doc/config/access_log/",
        "squid",
        "We compare cache effectiveness for GET pages versus CONNECT tunnels.",
        "CONNECT-heavy networks behave differently in hit ratio than browser traffic.",
        "Guides peering and SSL bump policies with evidence.",
    )
    row(
        "5.14.24",
        "Squid Internal DNS Resolver Errors and Latency",
        "high",
        "intermediate",
        ["Performance", "Availability"],
        'index=proxy sourcetype="squid:cache"\n| regex _raw="(?i)(DNS|ipcache|fqdn).*(?:FAIL|timeout|missing)"\n| stats count by host\n| sort - count',
        "`index=proxy` `sourcetype=squid:cache` (`cache.log`) resolver warnings",
        "Point `dns_nameservers` at resilient anycast resolvers; alert on repeated failures.",
        "http://www.squid-cache.org/Doc/config/dns_nameservers/",
        "squid",
        "We spot DNS problems that slow every proxied fetch.",
        "Resolver health is easy to overlook until all MISS latency spikes.",
        "Shortens outages where Squid is blamed but DNS is root cause.",
    )
    row(
        "5.14.25",
        "Squid Cache Peer Selection and Failure Events",
        "high",
        "intermediate",
        ["Availability"],
        'index=proxy sourcetype="squid:cache"\n| regex _raw="(?i)(peer.*(?:DEAD|DOWN|FAILED)|DETECT UP|DETECT DOWN)"\n| stats count by cache_peer\n| sort - count',
        "`index=proxy` `sourcetype=squid:cache` peer state transitions",
        "Log `cache_peer` lines at appropriate debug level; aggregate to Splunk via UF.",
        "http://www.squid-cache.org/Doc/config/cache_peer/",
        "squid",
        "We know when Squid stops using a parent or sibling proxy.",
        "Peer flaps shift load unexpectedly across the mesh.",
        "Stabilizes hierarchical cache designs.",
    )
    row(
        "5.14.26",
        "Squid CONNECT Tunnel Duration and Volume",
        "medium",
        "advanced",
        ["Security", "Performance"],
        'index=proxy sourcetype="squid:access"\n| where request_method=="CONNECT"\n| eval dur_ms=tonumber(time_taken_ms)\n| eval bytes=tonumber(bytes_sent)+tonumber(bytes_received)\n| timechart span=5m perc95(dur_ms) as p95_tunnel_ms sum(bytes) as tunnel_bytes',
        "`index=proxy` `sourcetype=squid:access` CONNECT with millisecond timing and byte counters",
        "Ensure log format includes duration; never log decrypted payload. Comply with local interception law.",
        "http://www.squid-cache.org/Doc/config/access_log/",
        "squid",
        "We summarize HTTPS tunnel load for capacity planning.",
        "CONNECT dominates bandwidth on many enterprise proxies.",
        "Supports fair sharing and DLP placement decisions.",
    )
    row(
        "5.14.27",
        "Squid ICAP and eCAP Adaptation Failures",
        "high",
        "advanced",
        ["Performance", "Security"],
        'index=proxy sourcetype="squid:cache"\n| regex _raw="(?i)(ICAP|ECAP).*(?:fail|error|timeout)"\n| bin _time span=5m\n| stats count by _time, host\n| where count > 10',
        "`index=proxy` `sourcetype=squid:cache` ICAP/eCAP diagnostics",
        "Tune service timeouts; scale scanners horizontally when counts rise.",
        "http://www.squid-cache.org/Doc/config/icap_service/",
        "squid",
        "We see when security scanners slow or break browsing.",
        "Adaptation failures look like random web errors to users.",
        "Protects both security coverage and productivity.",
    )
    row(
        "5.14.28",
        "Squid HTTP Access Denied by ACL",
        "medium",
        "intermediate",
        ["Security", "Audit"],
        'index=proxy sourcetype="squid:access"\n| where match(code, "TCP_DENIED|ERR_ACCESS_DENIED|NONE_ABORTED")\n| stats count by acl, dst_domain, src_ip\n| sort - count\n| head 40',
        "`index=proxy` `sourcetype=squid:access` with ACL name field if configured",
        "Add ACL tag to `access_log format` (Squid 4+); sanitize sensitive domains in dashboards.",
        "http://www.squid-cache.org/Doc/config/http_access/",
        "squid",
        "We show which rule blocks which clients.",
        "Policy tuning needs ranked deny reasons not anecdotes.",
        "Supports zero-trust web gateway reviews.",
    )
    row(
        "5.14.29",
        "Squid Disk Cache Swap Utilization",
        "high",
        "intermediate",
        ["Capacity"],
        'index=proxy sourcetype="squid:info"\n| regex _raw="(?i)(store_swap_size|Swap capacity|disk cache)"\n| rex field=_raw "(?<swap_mb>\\d+(?:\\.\\d+)?)\\s*(?:MB|GB)"\n| table _time, host, swap_mb',
        "`index=proxy` `sourcetype=squid:info` from `squidclient mgr:info` or cachemgr scrape",
        "Poll cachemgr over loopback; alert when swap usage crosses `cache_swap_high`.",
        "http://www.squid-cache.org/Doc/config/cache_dir/",
        "squid",
        "We monitor on-disk cache fill before Squid thrashes.",
        "Disk full leads to excessive MISS and origin load.",
        "Preserves browsing quality during traffic spikes.",
    )
    row(
        "5.14.30",
        "Squid Memory Hit vs Disk Hit Distribution",
        "medium",
        "intermediate",
        ["Performance"],
        'index=proxy sourcetype="squid:access"\n| eval layer=case(match(code, "TCP_MEM_HIT"),"mem", match(code, "TCP_HIT|TCP_REFRESH_HIT"),"disk", true(), "other")\n| bin _time span=15m\n| stats count by layer, _time',
        "`index=proxy` `sourcetype=squid:access` hierarchy `code` field",
        "Tune `cache_mem` versus disk to shift hot objects to RAM.",
        "http://www.squid-cache.org/Doc/config/cache_mem/",
        "squid",
        "We balance ultra-fast RAM hits versus disk hits.",
        "Mis-tuned memory leaves performance on the table.",
        "Improves latency for hot assets.",
    )
    row(
        "5.14.31",
        "Squid HTTP Status Code Distribution",
        "medium",
        "beginner",
        ["Availability", "Security"],
        'index=proxy sourcetype="squid:access"\n| eval sc=tonumber(status_code)\n| where isnotnull(sc)\n| bin sc span=100\n| timechart span=1h count by sc',
        "`index=proxy` `sourcetype=squid:access` origin or Squid status",
        "Separate `ERR_*` Squid codes from upstream HTTP for triage.",
        "http://www.squid-cache.org/Doc/config/http_status_codes/",
        "squid",
        "We trend errors seen through the proxy.",
        "Spikes in 5xx often precede origin incidents visible here first.",
        "Gives NOC a single pane for user-impacting web errors.",
    )
    row(
        "5.14.32",
        "Squid Delay Pool Throttling Signals",
        "medium",
        "advanced",
        ["Performance", "Governance"],
        'index=proxy sourcetype="squid:cache"\n| regex _raw="(?i)Delay pool|delay_pool"\n| bin _time span=5m\n| stats count by host, _time',
        "`index=proxy` `sourcetype=squid:cache` delay pool notices (controlled verbosity)",
        "Avoid verbose debug in prod; use short cache log notices or manager counters.",
        "http://www.squid-cache.org/Doc/config/delay_pools/",
        "squid",
        "We verify bandwidth policies activate when expected.",
        "Fair-use rules should be observable, not silent.",
        "Supports regulatory bandwidth management.",
    )
    row(
        "5.14.33",
        "Squid SSL Bump Peek-and-Splice Decision Audit",
        "high",
        "advanced",
        ["Security", "Compliance"],
        'index=proxy sourcetype="squid:access"\n| where match(_raw, "(?i)bump|splice|peek|SSL_")\n| stats count by ssl_bump_action, dst_domain\n| sort - count\n| head 50',
        "`index=proxy` `sourcetype=squid:access` SSL-bump enhanced format",
        "Restrict index permissions; follow jurisdiction on TLS inspection. Redact sensitive domains in exports.",
        "http://www.squid-cache.org/Doc/config/ssl_bump/",
        "squid",
        "We audit HTTPS inspection decisions for policy reviews.",
        "Regulators expect proof of what is inspected versus passed through.",
        "Reduces legal and privacy risk through transparency.",
    )
    row(
        "5.14.34",
        "Squid External ACL Helper Failures",
        "high",
        "intermediate",
        ["Performance", "Security"],
        'index=proxy sourcetype="squid:cache"\n| regex _raw="(?i)external_acl.*(?:fail|timeout|error)"\n| stats count by host\n| where count > 5',
        "`index=proxy` `sourcetype=squid:cache` helper diagnostics",
        "Scale concurrent helpers; cap slow identity providers.",
        "http://www.squid-cache.org/Doc/config/external_acl_type/",
        "squid",
        "We catch slow identity helpers that stall users.",
        "External ACLs are on the critical path for every request.",
        "Prevents cascading auth outages.",
    )
    row(
        "5.14.35",
        "Squid Client Connection Load from cachemgr",
        "high",
        "intermediate",
        ["Capacity", "Security"],
        'index=proxy sourcetype="squid:info"\n| regex _raw="(?i)Current active connections|client_http\\.conns"\n| rex field=_raw "(?<conns>\\d{3,})"\n| eval conns=tonumber(conns)\n| where conns > 20000\n| table _time, host, conns',
        "`index=proxy` `sourcetype=squid:info` manager snapshot",
        "Poll during incidents; baseline diurnal curves. Correlate with SYN flood mitigations.",
        "http://www.squid-cache.org/Doc/config/max_filedescriptors/",
        "squid",
        "We scale Squid before connection tables overflow.",
        "Proxies fail open or drop sessions when fds exhaust.",
        "Protects peak events like live streams and exams.",
    )

    # Envoy 5.14.36 - 42
    row(
        "5.14.36",
        "Envoy Circuit Breaker Open Events by Cluster",
        "critical",
        "intermediate",
        ["Resilience", "Availability"],
        'index=proxy sourcetype="envoy:stats"\n| search metric_name="*circuit_breakers*open*" OR metric_name="*cx_open*"\n| eval v=tonumber(metric_value)\n| where v > 0\n| timechart span=1m max(v) by cluster_name',
        "`index=proxy` `sourcetype=envoy:stats` Prometheus text from `/stats/prometheus`",
        "Scrape via OpenTelemetry Collector or Telegraf; normalize `cluster_name` label.",
        "https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_circuit_breakers",
        "envoy",
        "We see when Envoy stops sending traffic to protect upstreams.",
        "Open breakers shed load but indicate real upstream pain.",
        "Prioritizes which service mesh cluster needs attention.",
    )
    row(
        "5.14.37",
        "Envoy Outlier Detection Ejection Events",
        "high",
        "intermediate",
        ["Resilience", "Performance"],
        'index=proxy sourcetype="envoy:access"\n| where match(response_flags, "UH") OR match(response_flags, "UF") OR match(_raw, "(?i)eject")\n| stats count by upstream_host, cluster_name\n| where count > 5',
        "`index=proxy` `sourcetype=envoy:access` JSON access log with `%RESPONSE_FLAGS%`",
        "Tune outlier `consecutive_5xx`; confirm with periodic `/clusters` admin dumps (low volume).",
        "https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier",
        "envoy",
        "We track unhealthy hosts Envoy removes from rotation.",
        "Ejections explain uneven load and surprise latency.",
        "Speeds kube workload investigations.",
    )
    row(
        "5.14.38",
        "Envoy HTTP/2 RST_STREAM and Protocol Errors",
        "high",
        "advanced",
        ["Fault", "Performance"],
        'index=proxy sourcetype="envoy:access"\n| regex _raw="(?i)(RST_STREAM|GOAWAY|protocol_error)"\n| bin _time span=5m\n| stats count by cluster_name, _time\n| where count > 15',
        "`index=proxy` `sourcetype=envoy:access` or `envoy:log` codec warnings",
        "Align `http2` settings with language runtimes; log `%RESPONSE_CODE_DETAILS%`.",
        "https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto",
        "envoy",
        "We debug HTTP/2 issues between services.",
        "Protocol errors masquerade as application timeouts.",
        "Shortens mesh-wide incident resolution.",
    )
    row(
        "5.14.39",
        "Envoy HTTP Rate Limit Filter 429 Rate",
        "high",
        "intermediate",
        ["Security", "Performance"],
        'index=proxy sourcetype="envoy:access"\n| where response_code==429 OR match(response_flags, "RL")\n| stats count by route_name, cluster_name\n| sort - count',
        "`index=proxy` `sourcetype=envoy:access` with rate-limit outcomes",
        "Ensure xDS pushes consistent descriptors; log external RL service errors separately.",
        "https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rate_limit_filter",
        "envoy",
        "We measure how often Envoy enforces throttles.",
        "429 spikes indicate abuse or mis-set quotas.",
        "Balances protection versus legitimate burst traffic.",
    )
    row(
        "5.14.40",
        "Envoy Upstream Connection Pool Overflow",
        "critical",
        "advanced",
        ["Availability", "Capacity"],
        'index=proxy sourcetype="envoy:stats"\n| search metric_name="*overflow*" OR metric_name="*pending_requests*"\n| eval v=tonumber(metric_value)\n| where v > 0\n| timechart span=1m sum(v) by cluster_name',
        "`index=proxy` `sourcetype=envoy:stats` Prometheus metrics",
        "Increase `max_connections` and `max_pending_requests` carefully; verify upstream capacity.",
        "https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/connection_pooling",
        "envoy",
        "We catch Envoy running out of connections to backends.",
        "Pool overflow produces 503s without obvious CPU load.",
        "Prevents mesh-wide retry storms.",
    )
    row(
        "5.14.41",
        "Envoy Active Health Check Failure Spike",
        "high",
        "advanced",
        ["Availability"],
        'index=proxy sourcetype="envoy:stats"\n| search metric_name="*health_check*failure*" OR metric_name="*health_check*network_failure*"\n| eval v=tonumber(metric_value)\n| where v > 0\n| timechart span=1m sum(v) by cluster_name',
        "`index=proxy` `sourcetype=envoy:stats` health check counters",
        "Correlate with Kubernetes pod restart metrics and upstream deploys.",
        "https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/health_checking",
        "envoy",
        "We link health check noise to unstable workloads.",
        "Failing checks drain endpoints before user monitors react.",
        "Aligns platform and service owner visibility.",
    )
    row(
        "5.14.42",
        "Envoy ext_authz Latency and Denials",
        "high",
        "intermediate",
        ["Security", "Performance"],
        'index=proxy sourcetype="envoy:access"\n| eval dur=tonumber(duration_ms)\n| where response_code IN (401,403) OR match(response_flags, "UAEX")\n| timechart span=5m perc95(dur) as p95_ms count by cluster_name',
        "`index=proxy` `sourcetype=envoy:access` JSON with duration and flags",
        "Avoid logging tokens; use separate debug index for authz bodies.",
        "https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter",
        "envoy",
        "We watch external authorization slowdowns and denials.",
        "Authz latency becomes user latency on every request.",
        "Keeps zero-trust gates fast and observable.",
    )

    # Traefik 5.14.43 - 52
    row(
        "5.14.43",
        "Traefik Entrypoint Open Connections",
        "high",
        "intermediate",
        ["Capacity", "Performance"],
        'index=proxy sourcetype="traefik:metrics"\n| search metric_name="*entrypoint*open_connections*" OR match(metric_name, "traefik_entrypoint_open_connections")\n| eval v=tonumber(metric_value)\n| timechart span=1m max(v) by entrypoint',
        "`index=proxy` `sourcetype=traefik:metrics` Prometheus scrape",
        "Enable `--metrics.prometheus`; label series by entrypoint. Use OTel if multi-tenant.",
        "https://doc.traefik.io/traefik/observability/metrics/prometheus/",
        "traefik",
        "We track how many connections Traefik holds per listener.",
        "Connection growth predicts fds and memory pressure.",
        "Supports right-sizing edge nodes.",
    )
    row(
        "5.14.44",
        "Traefik Service Health Check Failures",
        "critical",
        "beginner",
        ["Availability"],
        'index=proxy sourcetype="traefik:log"\n| regex _raw="(?i)(Health check failed|Status.*DOWN|Server.*Unhealthy)"\n| stats count by service_name\n| sort - count',
        "`index=proxy` `sourcetype=traefik:log` JSON application logs",
        "Ship container stdout via sidecar; set log level INFO in prod.",
        "https://doc.traefik.io/traefik/routing/services/#health-check",
        "traefik",
        "We see backends Traefik marks unhealthy.",
        "Router health drives load balancing; silent failures hurt most.",
        "Accelerates rollback when a deploy breaks probes.",
    )
    row(
        "5.14.45",
        "Traefik Middleware Time Share of Request Duration",
        "high",
        "advanced",
        ["Performance"],
        'index=proxy sourcetype="traefik:access"\n| eval mw=tonumber(MiddlewareDuration), total=tonumber(Duration)\n| eval mw_pct=if(total>0, round(100*mw/total,1), null())\n| where mw_pct > 25\n| timechart span=5m perc95(mw_pct) by RouterName',
        "`index=proxy` `sourcetype=traefik:access` JSON access (Traefik v2+ fields)",
        "If fields absent, export OpenTelemetry traces with span attributes for middleware.",
        "https://doc.traefik.io/traefik/observability/access-logs/",
        "traefik",
        "We split latency between middleware and upstream.",
        "Auth and compression should not dominate latency budgets.",
        "Guides middleware ordering and tuning.",
    )
    row(
        "5.14.46",
        "Traefik ACME / Let's Encrypt Renewal Errors",
        "high",
        "intermediate",
        ["Availability", "Security"],
        'index=proxy sourcetype="traefik:log"\n| regex _raw="(?i)(acme|letsencrypt).*(error|fail|unable)"\n| stats latest(_time) as last_seen count by _raw\n| sort - count\n| head 20',
        "`index=proxy` `sourcetype=traefik:log` ACME client lines",
        "Prefer DNS challenge in complex networks; monitor cert NotAfter via separate exporter.",
        "https://doc.traefik.io/traefik/https/acme/",
        "traefik",
        "We catch certificate renewal failures before browsers do.",
        "TLS expiry outages are preventable with log monitoring.",
        "Protects customer trust on public edges.",
    )
    row(
        "5.14.47",
        "Traefik Default Router / Catch-All Traffic Spike",
        "medium",
        "intermediate",
        ["Security", "Performance"],
        'index=proxy sourcetype="traefik:access"\n| where RouterName=="default@internal" OR match(RouterName, "(?i)dashboard@internal")\n| bin _time span=5m\n| stats count by ClientAddr, entryPointName, _time\n| where count > 200',
        "`index=proxy` `sourcetype=traefik:access` with `RouterName`",
        "High catch-all volume may be scanners; pair with WAF and geo blocking.",
        "https://doc.traefik.io/traefik/routing/routers/",
        "traefik",
        "We find traffic that misses real routers.",
        "Unexpected default-router hits expose config gaps.",
        "Improves edge hygiene and security posture.",
    )
    row(
        "5.14.48",
        "Traefik Retry Middleware Activations",
        "medium",
        "intermediate",
        ["Resilience", "Fault"],
        'index=proxy sourcetype="traefik:access"\n| where RetryAttempts > 0\n| stats sum(RetryAttempts) as retries by ServiceName\n| sort - retries',
        "`index=proxy` `sourcetype=traefik:access` field `RetryAttempts`",
        "Enable retries only on idempotent routes; watch for retry amplification.",
        "https://doc.traefik.io/traefik/middlewares/http/retry/",
        "traefik",
        "We measure how often Traefik replays failed requests.",
        "Retries mask flaky upstreams but add load when misconfigured.",
        "Balances resilience versus thundering herds.",
    )
    row(
        "5.14.49",
        "Traefik Mutual TLS Client Certificate Errors",
        "high",
        "intermediate",
        ["Security", "Audit"],
        'index=proxy sourcetype="traefik:access"\n| where DownstreamStatus==401 OR match(_raw, "(?i)(unknown ca|certificate required|handshake failure)")\n| stats count by RouterName, ClientAddr\n| where count > 15',
        "`index=proxy` `sourcetype=traefik:access` with TLS fields",
        "Configure `tls.options.clientAuthType`; never log private keys or full chains in access logs.",
        "https://doc.traefik.io/traefik/https/tls/",
        "traefik",
        "We track client certificate validation failures.",
        "mTLS ecosystems break silently when CAs rotate.",
        "Keeps partner B2B APIs reliable.",
    )
    row(
        "5.14.50",
        "Traefik Dynamic Configuration Reload Events",
        "medium",
        "intermediate",
        ["Change", "Operational"],
        'index=proxy sourcetype="traefik:log"\n| regex _raw="(?i)(Configuration loaded|Provider event|Reloaded)"\n| stats count by _raw\n| sort - count\n| head 30',
        "`index=proxy` `sourcetype=traefik:log` provider notifications",
        "Correlate with GitOps commits; alert only on error-level reload failures in prod.",
        "https://doc.traefik.io/traefik/providers/overview/",
        "traefik",
        "We record when Traefik picks up new routing config.",
        "Reload storms during incidents explain sudden behavior changes.",
        "Supports blameless postmortems with timestamps.",
    )
    row(
        "5.14.51",
        "Traefik Request Content-Length Distribution",
        "medium",
        "advanced",
        ["Security", "Performance"],
        'index=proxy sourcetype="traefik:access"\n| eval cl=tonumber(RequestContentSize)\n| where cl > 5000000\n| bin cl span=1000000\n| stats count by cl, RouterName',
        "`index=proxy` `sourcetype=traefik:access` with `RequestContentSize`",
        "Use for large upload monitoring; pair with body size limits middleware.",
        "https://doc.traefik.io/traefik/observability/access-logs/#access-logs",
        "traefik",
        "We highlight unusually large payloads hitting Traefik.",
        "Big bodies stress buffers and may signal exfiltration.",
        "Informs WAF and API gateway limits.",
    )
    row(
        "5.14.52",
        "Traefik Weighted Round-Robin Backend Imbalance",
        "medium",
        "advanced",
        ["Performance", "Operational"],
        'index=proxy sourcetype="traefik:access"\n| stats count by ServiceName, ServiceAddr\n| eventstats sum(count) as tot by ServiceName\n| eval share_pct=round(100*count/tot,2)\n| where share_pct < 5 OR share_pct > 80\n| table ServiceName, ServiceAddr, count, share_pct',
        "`index=proxy` `sourcetype=traefik:access` per-target `ServiceAddr`",
        "Validate dynamic weights from Consul/Kubernetes; investigate cold endpoints.",
        "https://doc.traefik.io/traefik/routing/services/#weighted-round-robin",
        "traefik",
        "We verify traffic spreads across weighted backends.",
        "Skewed weights waste capacity or overload canaries.",
        "Keeps progressive delivery honest.",
    )

    print("written proxy UCs 5.14.1-5.14.52 (52 files)")


if __name__ == "__main__":
    main()
