#!/usr/bin/env python3
"""
audit_doc_vendor_products.py — vendor / product-name hallucination
sweep across the repository's prose documentation.

Why this script exists
----------------------

URL audits (scripts/audit_doc_urls.py) catch dead links, but a
fully resolvable URL can still sit next to a hallucinated *product
name* — "Cisco Catalyst Center Identity Services Engine" (a
real-sounding mash-up that does not exist) or "Splunk Real Time
Observability Suite" (no such product). This script extracts every
"Vendor + 1–4 capitalised tokens" phrase from the prose docs and:

1. **Phase A — Frequency report**
   Groups by phrase, counts occurrences across the corpus, and
   lists the source files. Human review tags suspicious phrases.

2. **Phase B — Targeted allowlist check** (Cisco / Splunk)
   Cross-references each phrase against an allowlist seeded from
   `api/v1/equipment/index.json` plus a curated baseline of
   well-known product names. Anything outside the allowlist is
   flagged for review as a *candidate* hallucination — false
   positives are expected, so the script is **report-only**.

Outputs
-------

Writes `data/doc-vendor-mentions.json` (machine-readable, used by
follow-up audits and reviews) and prints a human summary to stdout.

What it does NOT do
-------------------

- Does not modify any markdown. Fix-ups belong in a separate
  curated pass once human review has tagged the truly bad mentions.
- Does not probe vendor sites to validate product names. The
  allowlist is the source of truth; expand it as legitimate
  products surface.
- Skips fenced code blocks, inline code, the auto-generated
  references footer, and the YAML front-matter `product_aliases`
  block (which is intentionally a sprawling SEO keyword list,
  not prose claims about reality).

Stdlib-only. No third-party dependencies.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
STATUS_PATH = REPO / "data" / "doc-vendor-mentions.json"

# ---------------------------------------------------------------- corpus
#
# Re-use the same set of prose docs that audit_doc_urls.py walks.
# (Historical: content/cat-*/UC-*.md companions were deleted in F21
# close on 2026-05-18, so the explicit exclusion below is now a no-op
# but harmless. The LLM markdown twin lives only in
# dist/uc/UC-X.Y.Z/uc.md, which this audit does not walk either.)

DOCS_DIR = REPO / "docs"
DEFAULT_EXTRA = [
    "AGENTS.md", "AGENTS-EXAMPLES.md", "CONTRIBUTING.md", "GOVERNANCE.md",
    "ROADMAP.md", "README.md", "SECURITY.md", "LEGAL.md",
    "CODE_OF_CONDUCT.md", "CODEBASE-DIAGRAM.md",
    "api/README.md", "mcp/README.md", "samples/README.md",
    "templates/replication-starter/README.md",
    "ta/DA-ITSI-monitoring-use-cases/README.md",
]


def collect_docs() -> list[Path]:
    out: list[Path] = []
    if DOCS_DIR.is_dir():
        for p in DOCS_DIR.rglob("*.md"):
            if p.is_file():
                out.append(p)
    for rel in DEFAULT_EXTRA:
        p = REPO / rel
        if p.is_file():
            out.append(p)
    return sorted({p.resolve() for p in out})


# ---------------------------------------------------------------- cleaning
#
# Mirror audit_doc_urls.py exactly so the two audits see the same
# "prose" view of every doc. Front-matter is stripped wholesale.

FRONTMATTER_RE = re.compile(r"\A---\s*\n.*?\n---\s*\n", re.DOTALL)
FENCED_CODE_RE = re.compile(
    r"^\s*```.*?^\s*```",
    re.DOTALL | re.MULTILINE,
)
INLINE_CODE_RE = re.compile(r"`[^`\n]*`")
AUTOGEN_RE = re.compile(
    r"<!-- BEGIN-AUTOGENERATED-SOURCES -->.*?"
    r"<!-- END-AUTOGENERATED-SOURCES -->",
    re.DOTALL,
)
# Markdown link wrappers leak literal "[", "]", "(" characters into
# our token stream; strip the (URL) half so we keep the display label.
MARKDOWN_LINK_RE = re.compile(r"\[([^\]]+)\]\([^)]+\)")
# HTML inline tags (`<sup>`, `<a id="…">`) — strip to plain text.
HTML_TAG_RE = re.compile(r"<[^>]+>")


def clean_prose(text: str) -> str:
    text = FRONTMATTER_RE.sub("", text)
    text = AUTOGEN_RE.sub("", text)
    text = FENCED_CODE_RE.sub("", text)
    text = INLINE_CODE_RE.sub("", text)
    text = MARKDOWN_LINK_RE.sub(r"\1", text)
    text = HTML_TAG_RE.sub("", text)
    return text


# ---------------------------------------------------------------- vendor surfaces
#
# A vendor surface is the *anchor* token we look for in the prose.
# Each anchor declares its maximum greedy product-tail length so we
# don't gobble half a sentence after the vendor name. Tails stop at
# any lower-case token (English connector), punctuation, or a fresh
# proper-noun the user clearly meant as a new sentence subject.

VENDOR_SURFACES: dict[str, int] = {
    # Hyperscalers / global IT vendors. Higher-stake names get larger
    # tails because their product naming is multi-token.
    "Cisco": 5,
    "Splunk": 5,
    "Microsoft": 4,
    "AWS": 3,
    "Amazon": 4,
    "Google": 4,
    "Oracle": 4,
    "IBM": 4,
    "Apple": 3,
    "Adobe": 3,
    "Salesforce": 4,
    "ServiceNow": 4,
    "SAP": 4,
    "VMware": 4,
    "Broadcom": 4,
    "Red Hat": 4,
    "Canonical": 3,
    # Networking / security vendors.
    "Palo Alto": 4,
    "Fortinet": 4,
    "Check Point": 4,
    "Juniper": 4,
    "Aruba": 4,
    "Arista": 4,
    "F5": 4,
    "Citrix": 3,
    "Trellix": 3,
    "Trend Micro": 4,
    "CrowdStrike": 4,
    "SentinelOne": 3,
    "Sophos": 3,
    "Symantec": 3,
    "Tenable": 3,
    "Qualys": 3,
    "Rapid7": 3,
    "Zscaler": 3,
    "Cloudflare": 3,
    "Akamai": 3,
    "Imperva": 3,
    # Storage / hyperconverged.
    "NetApp": 4,
    "Pure Storage": 4,
    "Dell": 4,
    "HPE": 4,
    "Lenovo": 4,
    "Nutanix": 4,
    "Veeam": 3,
    "Rubrik": 3,
    "Cohesity": 3,
    "Hitachi": 4,
    # Observability / data / AIOps.
    "Datadog": 4,
    "New Relic": 4,
    "Dynatrace": 4,
    "Elastic": 4,
    "Grafana": 4,
    "Prometheus": 3,
    "OpenTelemetry": 3,
    "HashiCorp": 4,
    "Atlassian": 4,
    "GitLab": 3,
    "GitHub": 3,
    "Apache": 4,
    # AI / LLM vendors.
    "Anthropic": 3,
    "OpenAI": 3,
    "Mistral": 3,
    "Cohere": 3,
    "Hugging Face": 4,
    "DeepMind": 3,
    "NVIDIA": 4,
}

# Build a flat anchor list once. Multi-word anchors (e.g. "Red Hat",
# "Palo Alto", "Check Point") have to be matched as a single unit so
# we don't mis-attribute the trailing token as the "product".
ANCHORS_SORTED = sorted(VENDOR_SURFACES.keys(), key=len, reverse=True)

# ---------------------------------------------------------------- tail tokenisation
#
# A "product tail" is up to N CAPITALISED tokens that immediately
# follow the vendor anchor. Stop conditions:
#
# - Lower-case word (English connector or sentence continuation).
# - Punctuation (sentence boundary).
# - End of line.
# - Another vendor anchor (the writer pivoted to a new vendor).
#
# Capitalised here = starts with [A-Z] OR is fully uppercase (acronym)
# OR contains a digit (e.g. "9300", "ASA5500", "IOS-XE"). Single-letter
# trailing initials are allowed (e.g. "Splunk D Universal Forwarder").

CAPITALISED_TOKEN_RE = re.compile(
    # A capitalised "product-name word" — letter-start words (e.g.
    # "Catalyst"), all-caps acronyms (e.g. "ASA", "ESA"), and
    # alpha-leading version qualifiers (e.g. "v9", "X.Y"). Purely
    # numeric tokens are NOT accepted here because the walker would
    # otherwise gobble random version numbers next to the vendor
    # name ("Splunk 9.4", "Splunk 17", "Splunk 134") as if they
    # were product names.
    r"[A-Z][A-Za-z0-9][\w./+\-]*"
    r"|[A-Z]{2,}"
)
ENGLISH_STOPWORDS = {
    "and", "or", "the", "a", "an", "of", "for", "with", "to",
    "in", "on", "from", "by", "as", "at", "is", "are", "was",
    "were", "be", "been", "being", "this", "that", "these",
    "those", "but", "if", "then", "else", "than", "when",
    "while", "where", "via", "into", "onto", "over", "under",
    "across", "between", "per", "vs", "versus", "such",
}
# Tail tokens that look like product-name words but are nearly
# always English prose verbs / nouns the walker has mis-classified.
# Lower-case for membership testing.
PROSE_VERB_BLACKLIST = {
    "added", "adds", "alerts", "blogs", "checks", "combine",
    "connection", "correlate", "detectors", "docs", "documentation",
    "done", "fits", "five", "four", "generated", "guide",
    "guides", "include", "includes", "install", "installed",
    "integration", "integrations", "itself", "logging", "most",
    "official", "okay", "pages", "patterns", "platform", "plus",
    "provides", "review", "see", "settings", "shows", "store",
    "supports", "team", "teams", "three", "two", "umbrella",
    "use", "useful", "vendor", "vendors", "what", "you",
    "yes", "yourself",
}


def tokenise(text: str) -> list[tuple[str, int]]:
    """Return [(token, char_offset)] for one cleaned-prose document.

    We keep punctuation and case intact so the tail-walker can stop
    on a comma or a lower-case word."""
    return [(m.group(0), m.start()) for m in re.finditer(r"\S+", text)]


# Each token may carry trailing punctuation. Strip it for matching
# but record the original so the boundary detector still sees it.
TRAILING_PUNCT = ".,;:!?)]}\u201d\u2019\u2014\u2013"  # ASCII + curly + dashes


def is_capitalised(token: str) -> bool:
    """Return True for a token that's a plausible product-name word."""
    bare = token.rstrip(TRAILING_PUNCT)
    if not bare:
        return False
    return bool(CAPITALISED_TOKEN_RE.fullmatch(bare))


def is_terminating_punct(token: str) -> bool:
    """Return True if the token ends a clause (so the tail must stop)."""
    return token and token[-1] in ".,;:!?)]"


def normalise_phrase(words: list[str]) -> str:
    """Strip trailing punctuation from the last word and collapse spaces."""
    if not words:
        return ""
    out = list(words)
    out[-1] = out[-1].rstrip(TRAILING_PUNCT)
    return " ".join(out).strip()


# ---------------------------------------------------------------- extraction
#
# The walker is intentionally conservative — it errs on the side of
# emitting fewer, higher-confidence phrases. A few real product
# mentions WILL be missed; that's preferable to a noise-flooded
# allowlist.

def extract_phrases(text: str) -> list[tuple[str, str, int]]:
    """Return [(anchor, phrase, char_offset)] for one document."""
    cleaned = clean_prose(text)
    tokens = tokenise(cleaned)
    out: list[tuple[str, str, int]] = []

    i = 0
    while i < len(tokens):
        token, offset = tokens[i]
        # Look for the longest anchor starting at position i.
        anchor = None
        anchor_len = 0
        for cand in ANCHORS_SORTED:
            parts = cand.split()
            if i + len(parts) > len(tokens):
                continue
            if all(
                tokens[i + k][0].rstrip(TRAILING_PUNCT) == parts[k]
                for k in range(len(parts))
            ):
                anchor = cand
                anchor_len = len(parts)
                break
        if not anchor:
            i += 1
            continue

        # Walk the tail.
        max_tail = VENDOR_SURFACES[anchor]
        tail: list[str] = []
        j = i + anchor_len
        while j < len(tokens) and len(tail) < max_tail:
            t, _ = tokens[j]
            bare = t.rstrip(TRAILING_PUNCT)
            if not bare:
                break
            if bare.lower() in ENGLISH_STOPWORDS:
                break
            if bare.lower() in PROSE_VERB_BLACKLIST:
                # Vendor-prefixed prose ("Splunk provides…",
                # "Cisco offers…"); not a product name.
                break
            if not is_capitalised(t):
                break
            # Tokens with "/" are nearly always slash-separated
            # alternatives ("Cisco IOS/NX-OS/IOS-XR" — three OSes
            # listed inline, not a single product) or vendor-chains
            # ("Splunk Stealthwatch/Securonix"). Stop the tail at
            # the slash rather than emit a Frankenphrase.
            if "/" in bare:
                break
            # UC-X.Y.Z references are catalogue IDs, not products.
            if re.fullmatch(r"UC-\d+\.\d+\.\d+", bare):
                break
            if bare in ANCHORS_SORTED:
                break
            tail.append(t)
            if is_terminating_punct(t):
                # Token had a comma/period — accept this token but
                # do not extend further.
                break
            j += 1

        if not tail:
            i = i + anchor_len
            continue

        phrase = anchor + " " + normalise_phrase(tail)
        out.append((anchor, phrase, offset))
        i = j
    return out


# ---------------------------------------------------------------- allowlists
#
# Allowlists are seeded from the equipment registry, the Splunkbase
# catalog, and a curated baseline of canonical product names. The
# curated lists are deliberately UNDER-inclusive — names get added
# as they're verified against the authoritative source.

EQUIPMENT_INDEX = REPO / "api" / "v1" / "equipment" / "index.json"
SPLUNKBASE_CATALOG = REPO / "data" / "splunkbase-catalog.json"

# Curated baseline. Every entry has been verified against the
# vendor's own product page or documentation; do NOT add entries
# without verifying them yourself. Lower-case for matching.
CURATED_CISCO = {
    # Core platforms and product families.
    "cisco aci",  # Application Centric Infrastructure
    "cisco advanced malware protection",  # legacy AMP brand
    "cisco ai endpoint analytics",  # Catalyst Center feature
    "cisco ai endpoint behavioural",  # newer Catalyst Center feature
    "cisco ai endpoint behavioral",  # US spelling
    "cisco amp",  # Advanced Malware Protection — legacy
    "cisco anyconnect",
    "cisco appdynamics",
    "cisco appid",  # application-identification feature
    "cisco apic",
    "cisco asa",
    "cisco asyncos",  # email / web appliance OS
    "cisco av-pair",  # RADIUS vendor-specific attribute pair
    "cisco bgp",  # protocol, vendor-prefixed in docs
    "cisco catalyst",
    "cisco catalyst center",  # f.k.a. DNA Center
    "cisco catalyst sd-wan",  # Viptela rebrand
    "cisco cloud security",
    "cisco connect",  # event / program name
    "cisco crosswork",
    "cisco cube",  # Unified Border Element
    "cisco cssm",  # Cisco Smart Software Manager
    "cisco cyber vision",
    "cisco dc networking app",  # Splunkbase app name
    "cisco devnet",
    "cisco discovery protocol",  # CDP
    "cisco dna",
    "cisco dna center",
    "cisco duo",
    "cisco edge intelligence",
    "cisco enterprise",
    "cisco enterprise networking",
    "cisco esa",  # Email Security Appliance
    "cisco firepower",
    "cisco firewall",
    "cisco firepower threat defense",
    "cisco flexible netflow",  # protocol variant
    "cisco ftd",
    "cisco hyperflex",
    "cisco identity",
    "cisco identity intelligence",
    "cisco identity services",
    "cisco identity services engine",
    "cisco ios",
    "cisco ios xe",
    "cisco ios xr",
    "cisco ios-xe",
    "cisco ios-xr",
    "cisco ios-xe sd-wan",
    "cisco intersight",
    "cisco ise",
    "cisco isr",
    "cisco live",  # annual conference
    "cisco mds",
    "cisco meraki",
    "cisco ndi",  # Nexus Dashboard Insights
    "cisco netflow",
    "cisco nexus",
    "cisco nexus dashboard",
    "cisco networks add-on",  # Splunkbase TA
    "cisco nx-os",
    "cisco partner",
    "cisco platform",
    "cisco prime",
    "cisco prime infrastructure",
    "cisco psirt",  # Product Security Incident Response Team
    "cisco pxgrid",
    "cisco rest api",
    "cisco router",
    "cisco sd-wan",
    "cisco sd-access",
    "cisco secure access",
    "cisco secure client",
    "cisco secure cloud analytics",  # former Stealthwatch Cloud
    "cisco secure endpoint",
    "cisco secure email",  # f.k.a. ESA
    "cisco secure firewall",
    "cisco secure malware analytics",  # f.k.a. Threat Grid
    "cisco secure network analytics",
    "cisco secure web appliance",  # f.k.a. WSA
    "cisco secure workload",
    "cisco security cloud",
    "cisco security suite",
    "cisco services",
    "cisco smart licensing",
    "cisco smart software manager",
    "cisco sna",  # Secure Network Analytics abbreviation
    "cisco snmp",
    "cisco sns",  # Secure Network Server (ISE appliance line)
    "cisco solutions",
    "cisco spaces",
    "cisco stealthwatch",
    "cisco support",
    "cisco syslog",
    "cisco systems",
    "cisco tac",
    "cisco tas",  # Splunk technology add-ons (plural)
    "cisco talos",
    "cisco technical assistance center",
    "cisco thousandeyes",
    "cisco threat grid",  # legacy name, predecessor to Secure Malware Analytics
    "cisco trustsec",
    "cisco ucm",  # Unified Communications Manager
    "cisco ucs",
    "cisco umbrella",
    "cisco unified computing system",
    "cisco validated designs",  # CVD program
    "cisco viptela",
    "cisco vmanage",
    "cisco wlc",
    "cisco wsa",  # Web Security Appliance
    "cisco xdr",
    # 4-token product lines.
    "cisco catalyst 9000",
    "cisco catalyst 9100",
    "cisco catalyst 9200",
    "cisco catalyst 9300",
    "cisco catalyst 9400",
    "cisco catalyst 9500",
    "cisco catalyst 9600",
    "cisco catalyst 9800",
    "cisco catalyst ie",
    "cisco catalyst sd-wan manager",
    "cisco catalyst wireless",
    "cisco c9800 client authentication",
    "cisco c9800 rf performance",
    "cisco c9800 wlc ap join failures",
    "cisco data center analytics",
    "cisco esa add-on",
    "cisco identity services engine 3.4",
    "cisco nexus 7000",
    "cisco nexus 9000",
    "cisco nexus dashboard fabric controller",
    "cisco secure firewall 3100",
    "cisco smart licensing cssm",
    "cisco trustsec configuration guide",
    "cisco ucm 14.x",
    "cisco ucm add-on",
    "cisco ucm cdr",  # Call Detail Records
    "cisco ucs manager",
    "cisco ucs central",
    "cisco unified communications manager",  # CUCM voice (real)
    "cisco unified communications manager cucm voice cdr",
    "cisco unified communications manager cucm voice cdr/cmr",
    "cisco webex",
    "cisco webex calling",
    "cisco webex contact center",
    "cisco webex meetings",
    "cisco webex teams",
    # Hardware models surfaced by the walker; all are real Cisco SKUs
    # listed in the Identity Services Engine appliance datasheet.
    "cisco sns-3700",
    "cisco sns-3700 series",
    "cisco sns-3700 series datasheet",
    # Rebrands kept for historical references in the corpus.
    "cisco attack surface management",  # current name (2024+)
    "cisco secure cloud insights",  # legacy, end-of-sale Aug 2024
}

CURATED_SPLUNK = {
    "splunk ad",  # internal abbreviation for AppDynamics in some docs
    "splunk add-on",
    "splunk add-ons",
    "splunk add-on builder",
    "splunk ai",  # umbrella product family
    "splunk ai assistant",
    "splunk ai assistant for spl",
    "splunk apis",
    "splunk app",
    "splunk app navigator",
    "splunk apm",
    "splunk appinspect",
    "splunk application performance",  # truncated; counts toward APM
    "splunk application performance monitoring",
    "splunk apps",
    "splunk asset",  # Asset & Identity
    "splunk attack analyzer",
    "splunk attack range",
    "splunk base",
    "splunk catalyst center",  # Cisco Catalyst Center, vendor-prefixed by writers
    "splunk certified",
    "splunk cim",  # Common Information Model — official abbreviation
    "splunk cloud",
    "splunk cloud platform",
    "splunk cluster",
    "splunk common information",  # truncated alias of CIM
    "splunk common information model",
    "splunk community",
    "splunk connect",
    "splunk connect for snmp",
    "splunk connect for syslog",
    "splunk connect for kafka",
    "splunk connect for kubernetes",
    "splunk content pack",
    "splunk content packs",
    "splunk dashboard",
    "splunk dashboard studio",
    "splunk db",  # short alias for DB Connect
    "splunk db connect",
    "splunk dbx",  # DB Connect ID
    "splunk deployment server",
    "splunk detectors",  # Observability Cloud detectors
    "splunk distribution",
    "splunk distribution of opentelemetry collector",
    "splunk docs",
    "splunk edge",  # alias for Edge Hub / Edge Processor
    "splunk edge hub",
    "splunk edge processor",
    "splunk education",
    "splunk enterprise",
    "splunk enterprise security",
    "splunk es",
    "splunk eventgen",
    "splunk extension",  # Cribl Splunk extension
    "splunk federated search",
    "splunk forwarder",
    "splunk forwarders",
    "splunk hec",
    "splunk hf",  # Heavy Forwarder
    "splunk heavy forwarder",
    "splunk http event collector",
    "splunk index",
    "splunk indexer",
    "splunk indexer cluster",
    "splunk industrial",
    "splunk industrial asset intelligence",
    "splunk infrastructure",
    "splunk infrastructure monitoring",
    "splunk insights",
    "splunk inputs",
    "splunk inputs.conf",
    "splunk install",
    "splunk integration",
    "splunk intelligence management",
    "splunk it",
    "splunk it essentials",
    "splunk it essentials learn",
    "splunk it essentials work",
    "splunk it service",  # truncated alias for ITSI
    "splunk it service intelligence",
    "splunk itsi",
    "splunk knowledge object",
    "splunk lantern",
    "splunk license master",
    "splunk litmus",  # internal Splunk performance tool referenced in docs
    "splunk log observer",
    "splunk logging",
    "splunk machine learning toolkit",
    "splunk mission control",
    "splunk mcp",
    "splunk mcp server",
    "splunk metrics",
    "splunk microsegmentation",  # Microsegmentation app concept
    "splunk mint",
    "splunk ml toolkit",
    "splunk mltk",
    "splunk modular inputs",
    "splunk monitoring console",
    "splunk monitoring use cases",
    "splunk obs",  # short alias for Observability Cloud
    "splunk observability",
    "splunk observability cloud",
    "splunk on-call",
    "splunk openshift app",  # Splunkbase TA name
    "splunk operational telemetry",
    "splunk opsgenie app",
    "splunk oscal",  # Splunk's OSCAL profile — vendor-prefixed in docs
    "splunk otel",
    "splunk otel collector",
    "splunk otel java",
    "splunk otel python",
    "splunk otel node.js",
    "splunk ot security add-on",  # real Splunkbase app
    "splunk paas",
    "splunk pagerduty app",
    "splunk phantom",
    "splunk platform",
    "splunk poc",
    "splunk premium",
    "splunk premium app",
    "splunk premium apps",
    "splunk premium ta",
    "splunk professional services",
    "splunk ps",  # Professional Services abbreviation
    "splunk rbac",
    "splunk react",
    "splunk react ui",
    "splunk real user",  # truncated alias for RUM
    "splunk real user monitoring",
    "splunk rba",
    "splunk reference architecture",
    "splunk reference design",
    "splunk reference solution",
    "splunk rest api",
    "splunk rum",
    "splunk sc4s",  # Connect for Syslog abbreviation
    "splunk security cloud",
    "splunk security content",
    "splunk security essentials",
    "splunk security operations",
    "splunk ses",  # sales engineers
    "splunk sales engineer",
    "splunk smartstore",
    "splunk soar",
    "splunk soar cloud",
    "splunk software development kit",
    "splunk spl",
    "splunk sso",
    "splunk stream",
    "splunk studio",  # Dashboard Studio short alias
    "splunk support",
    "splunk surge",  # Splunk SURGe research team
    "splunk synthetic",  # alias for Synthetic Monitoring
    "splunk synthetics",
    "splunk synthetic monitoring",
    "splunk ta",
    "splunk tas",
    "splunk technology add-on",
    "splunk threat intelligence management",
    "splunk ui",
    "splunk ui toolkit",
    "splunk uba",
    "splunk uc recommender",  # this repo's recommender app
    "splunk uf",  # universal-forwarder abbreviation
    "splunk universal forwarder",
    "splunk universal forwarders",
    "splunk validated architecture",
    "splunk validated architectures",
    "splunk web",
    "splunk web framework",
    "splunk webex ta",
    "splunk workload pricing",
    # Phrases from this repository's own ecosystem that are real.
    "splunk monitoring",  # short form of "Splunk monitoring use cases" (repo title)
    "splunk monitoring use cases",
    "splunk ot",  # abbreviation for Operational Telemetry data model
    "splunk solutions",  # Lantern Splunk Solutions area
    "splunkbase",
    "splunkbase app",
    "splunkbase apps",
}

# Phrases we already know are *not* products — sentences that
# trigger the walker but mean something else. Lower-case.
KNOWN_PROSE_NOISE = {
    # Cisco prose accidents.
    "cisco 3",  # numeric stub
    "cisco blogs",
    "cisco check point",  # vendor chain
    "cisco customer",
    "cisco customers",
    "cisco it",  # generic "Cisco IT" reference
    "cisco networks",  # heading, not product
    "cisco networks guide",
    "cisco palo alto",  # vendor chain
    "cisco partner",
    "cisco partners",
    "cisco psirt security advisories",
    "cisco product",
    "cisco products",
    "cisco rogue ap",  # descriptive
    "cisco secure fw",  # bare abbreviation, not a product
    "cisco secure fw ha",  # bare abbreviation
    "cisco solution briefs",
    "cisco stealthwatch/securonix",
    "cisco store",
    "cisco use cases",
    "cisco vista",  # internal program name
    # Splunk prose accidents — content pivots, version numbers, and
    # vendor chains that the walker absorbed by mistake.
    "splunk admin",
    "splunk admins",
    "splunk administrator",
    "splunk administrators",
    "splunk azure app account",
    "splunk blogs",
    "splunk cloud-friendly",
    "splunk cloud-native",
    "splunk cloud-safe",
    "splunk cloud-vetted",
    "splunk compliance",  # descriptive heading
    "splunk compliance patterns",
    "splunk compliance add-ons",
    "splunk content packs every",
    "splunk core certified consultant",
    "splunk core certified power user",
    "splunk customer",
    "splunk customers",
    "splunk docker",  # often "Splunk Docker / Kubernetes" lists
    "splunk done",
    "splunk evidence",  # descriptive
    "splunk evidence platform pattern",
    "splunk evidence platform pattern compliance",
    "splunk fits",
    "splunk five",
    "splunk generated pdf",
    "splunk hf/single",
    "splunk itself",
    "splunk most",
    "splunk official documentation",
    "splunk plugin",  # descriptive
    "splunk plugin 3332",  # Splunkbase app ID reference
    "splunk professional",
    "splunk provides",
    "splunk security blog",
    "splunk see multi-vendor coverage",
    "splunk self-health",  # descriptive
    "splunk self-health 4",
    "splunk sentinel",  # vendor chain with Microsoft Sentinel
    "splunk settings",
    "splunk solutions pages",
    "splunk sourcetype",
    "splunk stream-only",
    "splunk team",
    "splunk teams",
    "splunk three",
    "splunk tls",  # descriptive ("Splunk TLS hardening")
    "splunk tls always",
    "splunk tls use",
    "splunk trust",
    "splunk trust slack/forum",
    "splunk uc mcp",  # cross-vendor chain
    "splunk umbrella",  # vendor chain with Cisco Umbrella
    "splunk use",
    "splunk useful",
    "splunk user",
    "splunk users",
    "splunk vendor",
    "splunk virtual compute",
    "splunk visibility",
    "splunk what",
    "splunk you",
}


def load_equipment_allowlist() -> set[str]:
    if not EQUIPMENT_INDEX.is_file():
        return set()
    data = json.loads(EQUIPMENT_INDEX.read_text(encoding="utf-8"))
    out: set[str] = set()
    for entry in data.get("equipment", []):
        label = (entry.get("label") or "").strip()
        if label:
            out.add(label.lower())
        for model in entry.get("models", []):
            ml = (model.get("label") or "").strip()
            if ml:
                out.add(ml.lower())
    return out


def load_splunkbase_allowlist() -> set[str]:
    if not SPLUNKBASE_CATALOG.is_file():
        return set()
    try:
        data = json.loads(SPLUNKBASE_CATALOG.read_text(encoding="utf-8"))
    except Exception:
        return set()
    out: set[str] = set()
    # Catalog shape: {"apps": [{"id":"...","title":"..."}, ...]}
    apps = data.get("apps") or data.get("entries") or []
    if isinstance(apps, dict):
        apps = apps.values()
    for entry in apps:
        if not isinstance(entry, dict):
            continue
        title = (
            entry.get("title") or entry.get("name") or entry.get("label") or ""
        ).strip()
        if title:
            out.add(title.lower())
    return out


def build_allowlist() -> dict[str, set[str]]:
    """Return {vendor_anchor: {lower-case product phrase, ...}}."""
    equipment = load_equipment_allowlist()
    splunkbase = load_splunkbase_allowlist()

    # All entries are LOWER-cased; matching is case-insensitive but
    # preserves the original anchor case in reports.
    cisco = set(CURATED_CISCO)
    splunk = set(CURATED_SPLUNK)
    # Add equipment labels that start with a known vendor.
    for label in equipment:
        if label.startswith("cisco"):
            cisco.add(label)
        if label.startswith("splunk"):
            splunk.add(label)
    # Splunkbase apps are mostly "<Vendor> Add-on for X" — we use
    # them only to enrich the Splunk allowlist, not as gospel.
    for app_title in splunkbase:
        if app_title.startswith("splunk"):
            splunk.add(app_title)

    return {
        "Cisco": cisco,
        "Splunk": splunk,
    }


# ---------------------------------------------------------------- audit
#
# The audit walks every document, extracts vendor+product phrases,
# and emits two reports:
#
#   - mentions: every observed (anchor, phrase) with counts and
#     source documents. Useful for a human eyeball pass.
#   - suspicious: phrases for vendors with an allowlist (Cisco /
#     Splunk) that did NOT match the allowlist and are NOT in
#     KNOWN_PROSE_NOISE. Candidates for hallucination, not
#     proof of hallucination.

def audit(docs: list[Path]) -> dict:
    allowlists = build_allowlist()
    mentions: dict[str, dict] = defaultdict(
        lambda: {"count": 0, "files": defaultdict(int)}
    )
    by_anchor: dict[str, int] = defaultdict(int)

    for p in docs:
        rel = str(p.relative_to(REPO)).replace("\\", "/")
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except Exception:
            continue
        seen = set()
        for anchor, phrase, _ in extract_phrases(text):
            key = (anchor, phrase)
            seen.add(key)
            mentions[phrase]["anchor"] = anchor
            mentions[phrase]["count"] += 1
            mentions[phrase]["files"][rel] += 1
            by_anchor[anchor] += 1

    # Sort + tidy for serialisation.
    mentions_sorted = sorted(
        mentions.items(), key=lambda kv: (-kv[1]["count"], kv[0])
    )
    serial_mentions = []
    for phrase, rec in mentions_sorted:
        serial_mentions.append({
            "anchor": rec["anchor"],
            "phrase": phrase,
            "count": rec["count"],
            "files": dict(sorted(rec["files"].items(), key=lambda kv: -kv[1])),
        })

    # Build the suspicious list (Cisco / Splunk only for now).
    suspicious = []
    for entry in serial_mentions:
        anchor = entry["anchor"]
        if anchor not in allowlists:
            continue
        phrase_lower = entry["phrase"].lower()
        if phrase_lower in KNOWN_PROSE_NOISE:
            continue
        if phrase_lower in allowlists[anchor]:
            continue
        # Accept any allowlist entry that the phrase STARTS with — but
        # ONLY when the entry is multi-token (>= anchor + 1 product
        # part) and the next character after the entry is a space.
        # Without these guards, a 1-word entry like "cisco" would
        # silently absolve every "Cisco Foo Bar" extraction.
        if any(
            len(allow.split()) >= 2
            and phrase_lower.startswith(allow + " ")
            for allow in allowlists[anchor]
        ):
            continue
        suspicious.append(entry)

    return {
        "_meta": {
            "schemaVersion": "1.0",
            "description": (
                "Vendor / product-name mentions extracted from the "
                "prose docs corpus. Phase A (mentions) is exhaustive; "
                "Phase B (suspicious) flags Cisco / Splunk phrases "
                "that do not match the curated allowlist."
            ),
        },
        "anchor_counts": dict(
            sorted(by_anchor.items(), key=lambda kv: -kv[1])
        ),
        "mentions": serial_mentions,
        "suspicious": suspicious,
    }


# ---------------------------------------------------------------- CLI

def _print_summary(payload: dict, top: int) -> None:
    print()
    print(f"Vendor anchors:")
    for anchor, n in payload["anchor_counts"].items():
        print(f"  {anchor:<14s}  {n:>5d} mentions")
    susp = payload["suspicious"]
    print()
    print(f"Phase B — {len(susp)} suspicious phrases "
          f"(allowlist miss, Cisco / Splunk)")
    for entry in susp[:top]:
        print(f"  {entry['count']:>3d}  {entry['phrase']}")
        for fp, n in list(entry["files"].items())[:3]:
            print(f"        {n:>3d}× {fp}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--top", type=int, default=40,
                        help="Number of suspicious phrases to print "
                             "(default 40).")
    parser.add_argument("--report", action="store_true",
                        help="Read existing data/doc-vendor-mentions.json "
                             "and print the summary without re-scanning.")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit 1 if any suspicious phrases are found. Intended "
             "for CI once the allowlist is exhaustive.",
    )
    args = parser.parse_args(argv)

    if args.report:
        if not STATUS_PATH.is_file():
            print(f"No status file at {STATUS_PATH}.")
            return 2
        payload = json.loads(STATUS_PATH.read_text(encoding="utf-8"))
    else:
        docs = collect_docs()
        if not docs:
            print("No prose docs found under docs/.")
            return 2
        print(f"Scanning {len(docs)} markdown files ...")
        payload = audit(docs)
        STATUS_PATH.parent.mkdir(parents=True, exist_ok=True)
        STATUS_PATH.write_text(
            json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

    _print_summary(payload, args.top)
    if args.strict and payload.get("suspicious"):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
