#!/usr/bin/env python3
"""
audit_doc_urls.py — probe every external URL referenced from the
repository's documentation and surface broken / hallucinated links.

Why this script exists
----------------------

scripts/check_source_links.py audits the curated bibliography
(data/source-references.json — 124 records). This script audits the
*body* of every documentation file: docs/**/*.md plus repo-root
README/AGENTS/CONTRIBUTING/etc. URLs.

LLM-authored documentation commonly hallucinates URLs that look
plausible but 404 or redirect to a generic landing page. This audit
catches that class of issue at scale.

What it does
------------

1. Walks all markdown sources (same set generate_doc_references.py
   processes, minus the auto-generated SKIP files).
2. Strips out fenced code blocks (``` ... ```) and inline `code` so
   example URLs in code snippets do not get probed.
3. Strips the auto-generated references footer
   (<!-- BEGIN-AUTOGENERATED-SOURCES --> .. <!-- END... -->), which is
   already audited by scripts/check_source_links.py.
4. Extracts every http:// / https:// URL from the remaining prose,
   normalising trailing punctuation.
5. Probes every unique URL with the same UA / HEAD-then-GET /
   bot-blocked-host logic as check_source_links.py.
6. Writes data/doc-link-status.json with per-URL status, redirect
   chain, and the list of source documents that reference it.
7. Prints a per-classification summary and a leaderboard of broken
   URLs grouped by host.

The script is **not** wired into per-PR validate.yml — it makes
outbound network calls. It is meant to run on demand and on a
scheduled workflow (see `make audit-doc-urls`).

Stdlib-only.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import socket
import ssl
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
STATUS_PATH = REPO / "data" / "doc-link-status.json"

# Same UA stack as check_source_links.py — many vendor portals 403
# urllib's default UA.
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14.6; rv:131.0) "
    "Gecko/20100101 Firefox/131.0"
)
EXTRA_HEADERS = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,"
              "image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Accept-Encoding": "gzip, deflate",
    "Connection": "close",
    "Upgrade-Insecure-Requests": "1",
}
TIMEOUT_SEC = 25
MAX_REDIRECTS = 5
MAX_WORKERS = 12

GET_ONLY_HOSTS = {
    "csrc.nist.gov", "pages.nist.gov", "www.nist.gov", "nist.gov",
    "eur-lex.europa.eu", "www.iso.org", "iso.org",
    "www.legislation.gov.uk", "pcaobus.org",
    "www.coso.org", "coso.org",
    "www.aicpa-cima.com", "aicpa-cima.com",
    "listings.pcisecuritystandards.org",
}

BOT_BLOCKED_HOSTS = {
    # US federal — strong bot defences, return 403 to every UA we've
    # tried, but humans can load these URLs in a browser.
    "www.hhs.gov", "hhs.gov",
    "www.sec.gov", "sec.gov",
    "www.congress.gov", "congress.gov",
    "www.ferc.gov", "ferc.gov",
    "dodcio.defense.gov",
    "www.ecfr.gov", "ecfr.gov",
    "www.cyber.gov.au",
    # EU national authorities — return 400/403/connection-reset to
    # urllib but are valid in a browser.
    "www.iec.ch", "iec.ch",
    "unece.org",
    "www.bafin.de", "bafin.de",
    "www.bfdi.bund.de", "bfdi.bund.de",
    "www.bsi.bund.de", "bsi.bund.de",
    "www.enisa.europa.eu", "enisa.europa.eu",
    # Middle East — geo-restricted or strong bot defences.
    "sdaia.gov.sa",
    # Vendor docs — Cloudflare / Akamai / WAFs in front of these.
    "docs.openshift.com",
    "access.redhat.com",
    "docs.aws.amazon.com",
    "docs.splunk.com",
    "developer.salesforce.com",
    "docs.cribl.io",
    "docs.versa-networks.com",
    "dev.mysql.com",
    "global.ihs.com",
    "intersight.com",
    "software.cisco.com",
    "www.arubanetworks.com",
    "www.ashrae.org",
    "www.cisco.com",
    "www.swift.com",
    "listings.pcisecuritystandards.org",
    "documentation.meraki.com",
    "docs.fortinet.com",
    # Middle East regulators — geo / WAF restrictions; TLS handshake,
    # DNS-resolution failures, or timeouts observed from urllib but
    # reachable from the browser. Treat as bot-blocked rather than
    # failing the audit.
    "www.qcb.gov.qa",
    "www.tra.gov.ae", "tra.gov.ae",
    # Certificate Transparency public log — Cloudflare-fronted; serves
    # intermittent 502s to scripted clients but the search page is
    # alive for humans.
    "crt.sh",
}

# Status codes from BOT_BLOCKED_HOSTS that we treat as evidence of bot
# defences rather than a real broken URL.
#
# - 400 — Bafin / BSI / BfDI IIS+Apache setups reject our header style.
# - 403 — Cloudflare / Akamai canonical block response.
# - 405 / 406 / 451 — niche WAF responses seen in the wild.
# - 500 — eCFR transient errors on long URLs.
# - 502 — Intersight / crt.sh / docs.aws.amazon.com Cloudflare 502s.
# - 503 — docs.openshift.com / Akamai transient throttling.
#
# 5xx codes here are intentionally scoped to BOT_BLOCKED_HOSTS — we do
# NOT want to mask a genuine 500 from an arbitrary host.
BOT_BLOCKED_STATUSES = {400, 403, 405, 406, 451, 500, 502, 503}

# Hosts that nearly always 200 us (Splunkbase, GitHub, Splunk docs) but
# can also return a soft-404 — a 200 response served from a "page not
# found" template. For those we need extra content-shape checks before
# trusting `ok`. Handled in `probe_extra_validation`.
SOFT_404_HOSTS = {
    "splunkbase.splunk.com",
}

# We exclude URLs in code blocks; this regex spots a fenced code block
# header at the start of a line.
FENCED_CODE_RE = re.compile(
    r"^\s*```.*?^\s*```",
    re.DOTALL | re.MULTILINE,
)
INLINE_CODE_RE = re.compile(r"`[^`\n]*`")
AUTOGEN_RE = re.compile(
    r"<!-- BEGIN-AUTOGENERATED-SOURCES -->.*?"
    r"<!-- END-AUTOGENERATED-SOURCES -->",
    re.DOTALL,
)
# URLs: http(s):// followed by anything that isn't whitespace, quotes,
# brackets, or angle brackets. Trailing punctuation is stripped after.
URL_RE = re.compile(r'https?://[^\s<>"\'`)\]]+')
TRAILING_PUNCT = ".,;:!?)]\u201d\u2019"  # ASCII + curly quotes

DEFAULT_EXTRA = [
    "AGENTS.md", "AGENTS-EXAMPLES.md", "CONTRIBUTING.md", "GOVERNANCE.md",
    "ROADMAP.md", "README.md", "SECURITY.md", "LEGAL.md",
    "CODE_OF_CONDUCT.md", "CODEBASE-DIAGRAM.md",
    "api/README.md", "mcp/README.md", "samples/README.md",
    "templates/replication-starter/README.md",
    "ta/DA-ITSI-monitoring-use-cases/README.md",
    "eventgen_data/README.md",
    ".github/PULL_REQUEST_TEMPLATE.md",
    ".github/PULL_REQUEST_TEMPLATE/architecture.md",
    ".github/PULL_REQUEST_TEMPLATE/security.md",
]


def collect_docs() -> list[Path]:
    out: list[Path] = []
    for p in (REPO / "docs").rglob("*.md"):
        if p.is_file():
            out.append(p)
    for rel in DEFAULT_EXTRA:
        p = REPO / rel
        if p.is_file():
            out.append(p)
    return sorted({p.resolve() for p in out})


def extract_urls(text: str) -> set[str]:
    # Drop the auto-generated references footer first — those URLs are
    # the curated bibliography, separately audited by
    # scripts/check_source_links.py.
    text = AUTOGEN_RE.sub("", text)
    # Drop fenced code blocks.
    text = FENCED_CODE_RE.sub("", text)
    # Drop inline code.
    text = INLINE_CODE_RE.sub("", text)
    found: set[str] = set()
    for m in URL_RE.finditer(text):
        url = m.group(0)
        # Strip trailing punctuation iteratively.
        while url and url[-1] in TRAILING_PUNCT:
            url = url[:-1]
        # Skip obviously templated URLs.
        if "<" in url or ">" in url or "{" in url or "}" in url:
            continue
        if not url:
            continue
        found.add(url)
    return found


def classify(status: int) -> str:
    if 200 <= status < 300:
        return "ok"
    if 300 <= status < 400:
        return "redirect"
    if 400 <= status < 500:
        return "client_error"
    if 500 <= status < 600:
        return "server_error"
    return "unknown_status"


class NoRedirectHandler(urllib.request.HTTPRedirectHandler):
    def http_error_301(self, req, fp, code, msg, headers):
        return fp
    http_error_302 = http_error_301
    http_error_303 = http_error_301
    http_error_307 = http_error_301
    http_error_308 = http_error_301


def _request(method: str, url: str) -> dict:
    chain: list[str] = []
    current = url
    for _ in range(MAX_REDIRECTS + 1):
        chain.append(current)
        req = urllib.request.Request(
            current, method=method,
            headers={"User-Agent": UA, **EXTRA_HEADERS},
        )
        opener = urllib.request.build_opener(NoRedirectHandler())
        try:
            with opener.open(req, timeout=TIMEOUT_SEC) as resp:
                status = resp.status
                if 300 <= status < 400:
                    loc = resp.headers.get("Location")
                    if not loc:
                        return {
                            "status": status,
                            "classification": classify(status),
                            "final_url": current,
                            "redirect_chain": chain,
                        }
                    current = urllib.parse.urljoin(current, loc)
                    continue
                # Capture a small slice of the response body so soft-404
                # detection can inspect it without burning bandwidth.
                body_peek = ""
                if method == "GET":
                    try:
                        body_peek = resp.read(4096).decode(
                            "utf-8", errors="replace"
                        )
                    except Exception:
                        body_peek = ""
                return {
                    "status": status,
                    "classification": classify(status),
                    "final_url": current,
                    "redirect_chain": chain,
                    "body_peek": body_peek,
                }
        except urllib.error.HTTPError as e:
            return {
                "status": e.code,
                "classification": classify(e.code),
                "final_url": current,
                "redirect_chain": chain,
                "error": str(e),
            }
        except urllib.error.URLError as e:
            reason = getattr(e, "reason", e)
            if isinstance(reason, socket.timeout):
                err_class = "timeout"
            elif isinstance(reason, socket.gaierror):
                err_class = "dns"
            elif isinstance(reason, ssl.SSLError):
                err_class = "tls"
            else:
                err_class = "unknown_error"
            return {
                "status": None,
                "classification": err_class,
                "final_url": current,
                "redirect_chain": chain,
                "error": str(reason),
            }
        except Exception as e:
            return {
                "status": None,
                "classification": "unknown_error",
                "final_url": current,
                "redirect_chain": chain,
                "error": str(e),
            }
    return {
        "status": None,
        "classification": "too_many_redirects",
        "final_url": current,
        "redirect_chain": chain,
    }


def probe_extra_validation(url: str, result: dict) -> dict:
    """Special-case soft-404 detection for known offenders."""
    host = urllib.parse.urlparse(url).netloc.lower()
    if host in SOFT_404_HOSTS and host == "splunkbase.splunk.com":
        body = (result.get("body_peek") or "").lower()
        # Splunkbase serves a 200 OK with a "page not found" template
        # for non-existent /app/<id> URLs. Detect both the marketing
        # 404 template and the catalogue-fallback template.
        if (
            "page not found" in body
            or "we can't find the page" in body
            or "404 - page not found" in body
        ):
            result["classification"] = "soft_404"
            result["status"] = result.get("status") or 200
    return result


def probe(url: str) -> dict:
    parsed = urllib.parse.urlparse(url)
    host = parsed.netloc.lower()
    # GET for hosts that 4xx/5xx on HEAD; HEAD-then-GET otherwise.
    methods = ["GET"] if host in GET_ONLY_HOSTS else ["HEAD", "GET"]
    # Soft-404 detection requires a body read, so always use GET there.
    if host in SOFT_404_HOSTS:
        methods = ["GET"]
    last: dict = {}
    for method in methods:
        result = _request(method, url)
        last = result
        if result.get("classification") == "ok":
            break
        # 403/405/501 on HEAD → fall back to GET.
        if result.get("status") in (403, 405, 501):
            continue
        break
    if last.get("status") in BOT_BLOCKED_STATUSES and host in BOT_BLOCKED_HOSTS:
        last["classification"] = "bot_blocked"
    # crt.sh returns 404 to bare-root GETs without a query string but
    # the host IS alive — the search page renders fine in a browser.
    # Treat this 404 as evidence of bot defences, not a real outage.
    if last.get("status") == 404 and host == "crt.sh":
        last["classification"] = "bot_blocked"
    # `None`-status errors (DNS refusal, TLS handshake fail, connection
    # reset, timeout) from known bot-blocked hosts are almost always
    # WAF behaviour, not real outages. Re-classify those too.
    if last.get("status") is None and host in BOT_BLOCKED_HOSTS \
            and last.get("classification") in {
                "unknown_error", "tls", "dns", "timeout",
            }:
        last["classification"] = "bot_blocked"
    # Soft-404 inspection (after we have a body_peek).
    last = probe_extra_validation(url, last)
    # Body peek is verbose — drop it from the saved payload unless we
    # actually used it.
    if last.get("body_peek") and last.get("classification") != "soft_404":
        last.pop("body_peek", None)
    return last


def collect_urls() -> dict[str, list[str]]:
    """Return {url: [list of doc paths referencing it]} repo-relative."""
    docs = collect_docs()
    by_url: dict[str, list[str]] = defaultdict(list)
    for p in docs:
        rel = str(p.relative_to(REPO)).replace("\\", "/")
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except Exception:
            continue
        for url in extract_urls(text):
            by_url[url].append(rel)
    return {u: sorted(set(srcs)) for u, srcs in by_url.items()}


def _hosts_in(urls: list[str]) -> dict[str, int]:
    counts: dict[str, int] = defaultdict(int)
    for u in urls:
        counts[urllib.parse.urlparse(u).netloc.lower()] += 1
    return counts


def _print_summary(payload: dict) -> None:
    urls = payload.get("urls", {})
    by_cls: dict[str, list[str]] = defaultdict(list)
    for u, rec in urls.items():
        by_cls[rec.get("classification", "?")].append(u)
    print()
    print(f"Total URLs probed: {len(urls)}")
    width = max((len(k) for k in by_cls), default=10)
    for cls in sorted(by_cls, key=lambda k: -len(by_cls[k])):
        print(f"  {cls:<{width}s}  {len(by_cls[cls]):>4d}")
    # Top broken hosts.
    broken = [
        u for u, rec in urls.items()
        if rec.get("classification") in {
            "client_error", "server_error", "dns", "tls",
            "timeout", "soft_404", "unknown_error", "too_many_redirects",
        }
    ]
    if not broken:
        print("\nNo dead/suspicious URLs found.")
        return
    by_host = _hosts_in(broken)
    print(f"\n{len(broken)} suspicious URLs across {len(by_host)} hosts:")
    for host, n in sorted(by_host.items(), key=lambda x: -x[1])[:20]:
        print(f"  {n:>3d}  {host}")


def _exit_code(payload: dict, strict: bool) -> int:
    if not strict:
        return 0
    urls = payload.get("urls", {})
    real_bad = {
        "client_error", "server_error", "dns", "tls",
        "soft_404", "unknown_error", "too_many_redirects",
    }
    for u, rec in urls.items():
        if rec.get("classification") in real_bad:
            return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--threads", type=int, default=MAX_WORKERS,
                        help=f"Concurrency (default {MAX_WORKERS}).")
    parser.add_argument("--only", help="Only check URLs whose host contains "
                                       "this substring (debug aid).")
    parser.add_argument("--report", action="store_true",
                        help="Print summary from data/doc-link-status.json "
                             "without re-probing.")
    parser.add_argument("--strict", action="store_true",
                        help="Exit 1 if any real bad URL remains.")
    parser.add_argument("--list-broken", action="store_true",
                        help="After probing (or in --report mode), print the "
                             "full list of broken URLs with source docs.")
    args = parser.parse_args(argv)

    if args.report:
        if not STATUS_PATH.exists():
            print(f"No status file at {STATUS_PATH}.")
            return 2
        payload = json.loads(STATUS_PATH.read_text(encoding="utf-8"))
        _print_summary(payload)
        if args.list_broken:
            _print_broken_detail(payload)
        return _exit_code(payload, args.strict)

    url_to_sources = collect_urls()
    if args.only:
        url_to_sources = {
            u: srcs for u, srcs in url_to_sources.items()
            if args.only in urllib.parse.urlparse(u).netloc.lower()
        }
    print(f"Probing {len(url_to_sources)} unique URLs with "
          f"{args.threads} workers ...")
    started = time.time()
    results: dict[str, dict] = {}
    with ThreadPoolExecutor(max_workers=args.threads) as pool:
        futures = {pool.submit(probe, u): u for u in url_to_sources}
        for i, fut in enumerate(as_completed(futures), 1):
            u = futures[fut]
            try:
                result = fut.result()
            except Exception as e:
                result = {
                    "status": None,
                    "classification": "unknown_error",
                    "error": str(e),
                }
            results[u] = {
                "url": u,
                "host": urllib.parse.urlparse(u).netloc.lower(),
                "sources": url_to_sources[u],
                **result,
            }
            cls = result.get("classification", "?")
            short = u if len(u) <= 70 else u[:67] + "..."
            sys.stdout.write(f"\r  {i}/{len(futures)}  {cls:<14s}  {short:<70s}")
            sys.stdout.flush()
    print()
    elapsed = time.time() - started

    payload = {
        "_meta": {
            "generated": dt.datetime.now(dt.timezone.utc)
                .isoformat(timespec="seconds").replace("+00:00", "Z"),
            "elapsedSeconds": round(elapsed, 1),
            "totalChecked": len(results),
            "tool": "scripts/audit_doc_urls.py",
            "notes": (
                "Run on demand; not wired into per-PR CI because the "
                "probe is network-dependent. Audits every external URL "
                "referenced from docs/**/*.md + repo-root *.md, "
                "EXCLUDING fenced code blocks, inline `code`, and the "
                "auto-generated references footer (those URLs are "
                "audited by scripts/check_source_links.py)."
            ),
        },
        "urls": dict(sorted(results.items())),
    }
    STATUS_PATH.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    _print_summary(payload)
    if args.list_broken:
        _print_broken_detail(payload)
    return _exit_code(payload, args.strict)


def _print_broken_detail(payload: dict) -> None:
    real_bad = {
        "client_error", "server_error", "dns", "tls",
        "soft_404", "unknown_error", "too_many_redirects",
    }
    urls = payload.get("urls", {})
    broken = [
        (u, rec) for u, rec in urls.items()
        if rec.get("classification") in real_bad
    ]
    if not broken:
        return
    print(f"\n=== Broken URL detail ({len(broken)}) ===")
    for u, rec in sorted(broken, key=lambda x: x[1]["host"]):
        status = rec.get("status")
        cls = rec.get("classification")
        srcs = rec.get("sources", [])
        print(f"\n  [{cls}/{status}]  {u}")
        for s in srcs[:5]:
            print(f"      ↳ {s}")
        if len(srcs) > 5:
            print(f"      ↳ ... and {len(srcs) - 5} more")


if __name__ == "__main__":
    sys.exit(main())
