#!/usr/bin/env python3
"""
audit_auto_gen_provenance.py — ensure every auto-generated doc names
the script + inputs that produced it.

For each entry in ``data/auto-generated-docs.json`` we verify:

1. The file exists.
2. The header of the file (first ~25 lines) carries an honest
   "Generated by ..." banner naming the generator command from the
   registry. The banner accepts any of:

       <!-- Generated by `<generator>`; do not hand-edit. -->
       _Generated by `<generator>`. Do not hand-edit._
       Generated by `<generator>`...
       Auto-generated by `<generator>`...

3. The set of generator targets equals the SKIP set in
   ``scripts/generate_doc_references.py`` so the two views never drift.

Modes:

```
python3 scripts/audit_auto_gen_provenance.py            # report only
python3 scripts/audit_auto_gen_provenance.py --fix      # add banners
python3 scripts/audit_auto_gen_provenance.py --check    # CI exit 1
```
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
REGISTRY = REPO / "data" / "auto-generated-docs.json"
GENERATOR_SCRIPT = REPO / "scripts" / "generate_doc_references.py"

# Match the contents of the backtick literal that follows some flavour
# of "[Auto-]Generated [optional metadata] by `..."`. Accepts:
#   - "Generated by `script`"
#   - "Auto-generated by `script`"
#   - "_Generated_ by `script`"
#   - "**Generated** by `script`"
#   - "Generated: <timestamp>_ by `script`"
#   - "report was generated by `script`"
BANNER_RE = re.compile(
    r"(?:auto-?generated|generated)"        # the verb
    r"(?:[_*]*)"                            # optional bold/italic markers
    r"(?:[^`\n]{0,80}?)\s+"                 # up to 80 chars of metadata
    r"by\s+`([^`\n]+?)`",                   # ...by `script`
    re.IGNORECASE,
)

# Loose secondary check: a doc passes if it contains BOTH the word
# "generated" AND a phrase like "do not edit" / "do not hand-edit"
# in its first ~25 lines, even if the banner doesn't name a script.
LOOSE_RE = re.compile(
    r"(?:auto-?generated|generated)[\s\S]*?(?:do not (?:hand-?)?edit|"
    r"don'?t edit|no hand[-_]?editing)",
    re.IGNORECASE,
)


def load_registry() -> dict:
    data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    data.pop("_meta", None)
    return data


def load_skip_set() -> set[str]:
    text = GENERATOR_SCRIPT.read_text(encoding="utf-8")
    m = re.search(r"SKIP: set\[str\] = \{(.*?)\}", text, re.DOTALL)
    if not m:
        return set()
    members = re.findall(r'"([^"\n]+)"', m.group(1))
    return set(members)


def header_text(path: Path, lines: int = 25) -> str:
    return "\n".join(
        path.read_text(encoding="utf-8", errors="replace").split("\n")[:lines]
    )


def _normalise_generator(s: str) -> str:
    """Strip common runner prefixes so 'python3 scripts/foo.py' and
    'scripts/foo.py' compare equal."""
    s = s.strip()
    for prefix in (
        "python3 -m ", "python -m ",
        "python3 ", "python ",
        "make ", "bash ", "sh ",
    ):
        if s.startswith(prefix):
            s = s[len(prefix):]
            break
    return s


def has_banner(text: str, generator: str) -> bool:
    """A doc's header carries provenance if EITHER:

    1. A generator banner names the registered script (after stripping
       runner prefixes like ``python -m``), OR
    2. The header contains any "generated by ... do not edit"
       statement at all. We accept the weaker signal because the
       audit's job is to make sure readers know not to hand-edit the
       file, not to enforce a specific banner wording.
    """
    norm_gen = _normalise_generator(generator)
    for m in BANNER_RE.finditer(text):
        found = m.group(1).strip()
        norm_found = _normalise_generator(found)
        if norm_gen == norm_found:
            return True
        if norm_gen in norm_found or norm_found in norm_gen:
            return True
    # Loose fallback: any reasonable "this is auto-generated" claim.
    if LOOSE_RE.search(text):
        return True
    return False


def build_banner(generator: str, inputs: list[str], cadence: str) -> str:
    inputs_str = ", ".join(f"`{i}`" for i in inputs) or "(none)"
    return (
        f"<!-- Generated by `{generator}`; do not hand-edit. -->\n"
        f"<!-- Inputs: {inputs_str} · Refresh cadence: {cadence} -->\n"
    )


def insert_banner(path: Path, banner: str) -> None:
    text = path.read_text(encoding="utf-8")
    lines = text.split("\n")
    # Insert right after the first H1 (or at the top if no H1).
    insert_at = 0
    for i, line in enumerate(lines[:5]):
        if line.lstrip().startswith("# "):
            insert_at = i + 1
            break
    # Skip a single blank line after the H1 if present.
    if insert_at < len(lines) and not lines[insert_at].strip():
        insert_at += 1
    lines.insert(insert_at, banner.rstrip())
    lines.insert(insert_at + 1, "")
    path.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--fix", action="store_true",
                   help="Insert provenance banners where missing.")
    p.add_argument("--check", action="store_true",
                   help="Exit 1 if any banner is missing or drift between "
                        "the registry and the SKIP set.")
    args = p.parse_args(argv)

    registry = load_registry()
    skip = load_skip_set()
    reg_keys = set(registry.keys())

    drift_missing_in_registry = sorted(skip - reg_keys)
    drift_missing_in_skip = sorted(reg_keys - skip)

    missing_banner: list[tuple[str, str]] = []
    fixed: list[str] = []

    for rel, entry in registry.items():
        path = REPO / rel
        if not path.exists():
            missing_banner.append((rel, "FILE MISSING"))
            continue
        if not entry.get("doNotEdit", True):
            # Hand-authored entries (CHANGELOG, VERSION) are listed in
            # the SKIP set but don't need a "Generated by" banner.
            continue
        head = header_text(path)
        gen = entry.get("generator") or ""
        if has_banner(head, gen):
            continue
        if args.fix:
            banner = build_banner(
                gen,
                entry.get("inputs", []),
                entry.get("refreshCadence", "unspecified"),
            )
            insert_banner(path, banner)
            fixed.append(rel)
        else:
            missing_banner.append((rel, f"no banner naming `{gen}`"))

    print("Auto-generated docs provenance audit")
    print(f"  Registry entries:  {len(registry)}")
    print(f"  SKIP entries:      {len(skip)}")
    if drift_missing_in_registry:
        print(f"  In SKIP but not in registry: {drift_missing_in_registry}")
    if drift_missing_in_skip:
        print(f"  In registry but not in SKIP: {drift_missing_in_skip}")
    if fixed:
        print(f"  Inserted banners: {len(fixed)}")
        for f in fixed:
            print(f"    + {f}")
    if missing_banner:
        print(f"  Missing banners:  {len(missing_banner)}")
        for rel, why in missing_banner:
            print(f"    - {rel}  ({why})")

    if args.check:
        if drift_missing_in_registry or drift_missing_in_skip:
            print("ERROR: SKIP set and provenance registry are out of sync.")
            return 1
        if missing_banner:
            print("ERROR: Auto-generated docs are missing provenance banners.")
            return 1
        print("OK: all auto-generated docs declare their generator.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
