#!/usr/bin/env python3
"""Generate Splunkbase TA content from the catalog.

Reads ``catalog.json`` plus the Quick-Start picks in ``use-cases/INDEX.md``
and emits three configuration files into
``ta/TA-splunk-use-cases/default/``:

- ``savedsearches.conf`` — one scheduled saved search per Quick-Start UC
  (≈ 2 critical UCs × 23 categories ≈ 46 searches), all disabled by default.
- ``macros.conf`` — convenience macros for common index filters used in the
  catalog (``uc_index_os``, ``uc_index_net``, ``uc_index_sec`` …).
- ``eventtypes.conf`` — eventtype aliases that mirror the catalog's
  sourcetype groupings (e.g. ``sourcetype=cpu`` → eventtype ``uc_cpu``).

Run:

    python3 scripts/build_ta.py

The generator is **idempotent** — running it twice yields the same file
content.  It must be re-run after content changes before packaging.
"""

from __future__ import annotations

import json
import os
import re
import sys
import textwrap
from typing import Dict, Iterable, List, Tuple

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
CATALOG = os.path.join(REPO_ROOT, "catalog.json")
INDEX_MD = os.path.join(REPO_ROOT, "use-cases", "INDEX.md")
TA_DIR = os.path.join(REPO_ROOT, "ta", "TA-splunk-use-cases")
DEFAULT_DIR = os.path.join(TA_DIR, "default")

# Criticality → cron schedule.  Values are deliberately conservative so a
# fresh install cannot accidentally overload a small Splunk deployment.
CRIT_TO_CRON: Dict[str, Tuple[str, str, str, str, str]] = {
    # (cron_schedule, earliest, latest, alert.severity, alert_condition)
    "critical": ("*/15 * * * *", "-30m@m", "now", "4", "search count > 0"),
    "high":     ("0 * * * *",    "-1h@h",  "now", "3", "search count > 0"),
    "medium":   ("0 */2 * * *",  "-2h@h",  "now", "2", "search count > 0"),
    "low":      ("0 */6 * * *",  "-6h@h",  "now", "2", "search count > 0"),
}

# Per-category preferred index macro (resolved in macros.conf).
CAT_INDEX_MACRO: Dict[int, str] = {
    1: "uc_index_os",
    2: "uc_index_virt",
    3: "uc_index_k8s",
    4: "uc_index_cloud",
    5: "uc_index_net",
    6: "uc_index_storage",
    7: "uc_index_db",
    8: "uc_index_app",
    9: "uc_index_idm",
    10: "uc_index_sec",
    11: "uc_index_email",
    12: "uc_index_devops",
    13: "uc_index_obs",
    14: "uc_index_ot",
    15: "uc_index_dc",
    16: "uc_index_itsm",
    17: "uc_index_zerotrust",
    18: "uc_index_fabric",
    19: "uc_index_hci",
    20: "uc_index_capacity",
    21: "uc_index_vertical",
    22: "uc_index_compliance",
    23: "uc_index_ba",
}


# --------------------------------------------------------------------------
# INDEX.md parser — picks Quick Start UC IDs per category.
# --------------------------------------------------------------------------

QS_CAT_RX = re.compile(r"^## (\d+)\. (.+)$")
QS_UC_RX = re.compile(r"^\s+-\s+UC-(\d+\.\d+\.\d+)\s")


def parse_quickstart() -> Dict[int, List[str]]:
    """Return ``{cat_number: ["1.1.23", …]}`` for every `## Quick Start:` block."""
    by_cat: Dict[int, List[str]] = {}
    current_cat: int | None = None
    with open(INDEX_MD, "r", encoding="utf-8") as f:
        for line in f:
            m_cat = QS_CAT_RX.match(line)
            if m_cat:
                current_cat = int(m_cat.group(1))
                continue
            m_uc = QS_UC_RX.match(line)
            if m_uc and current_cat is not None:
                by_cat.setdefault(current_cat, []).append(m_uc.group(1))
    return by_cat


# --------------------------------------------------------------------------
# Catalog helpers.
# --------------------------------------------------------------------------

def load_catalog() -> dict:
    with open(CATALOG, "r", encoding="utf-8") as f:
        return json.load(f)


def index_by_id(catalog: dict) -> Dict[str, dict]:
    idx: Dict[str, dict] = {}
    for cat in catalog.get("DATA", []):
        for sub in cat.get("s", []):
            for uc in sub.get("u", []):
                uid = uc.get("i")
                if uid:
                    idx[uid] = {**uc, "_cat": cat.get("i")}
    return idx


# --------------------------------------------------------------------------
# Conf helpers.
# --------------------------------------------------------------------------

CONF_HEADER = (
    "# ---------------------------------------------------------------------\n"
    "# GENERATED by scripts/build_ta.py — DO NOT EDIT BY HAND.\n"
    "# Source of truth: use-cases/*.md + INDEX.md (Quick Start), catalog.json.\n"
    "# Re-run `python3 scripts/build_ta.py` after updating content.\n"
    "# ---------------------------------------------------------------------\n"
)


def _escape_conf(val: str) -> str:
    """Conf line continuation: lines ending with `\\` → next line keeps reading.

    For multi-line SPL we emit the value as a single logical line by using
    Splunk conf's whitespace-preserving backslash-newline continuation.
    """
    stripped = val.strip()
    if "\n" not in stripped:
        return stripped
    lines = stripped.splitlines()
    return " \\\n".join(line.rstrip() for line in lines)


def _stanza_name(uc: dict) -> str:
    uid = uc.get("i", "?")
    name = uc.get("n", "Untitled")
    safe = name.replace("[", "(").replace("]", ")").replace("\n", " ").strip()
    return f"UC-{uid} — {safe}"


def render_savedsearches(ucs: Iterable[dict]) -> str:
    out = [CONF_HEADER, ""]
    for uc in ucs:
        uid = uc.get("i", "?")
        crit = (uc.get("c") or "medium").lower()
        cron, earliest, latest, severity, cond = CRIT_TO_CRON.get(crit, CRIT_TO_CRON["medium"])
        spl = uc.get("q") or ""
        if not spl.strip():
            continue
        desc_parts: List[str] = []
        if uc.get("v"):
            desc_parts.append(uc["v"].strip())
        if uc.get("kfp"):
            desc_parts.append(f"Known false positives: {uc['kfp'].strip()}")
        out.append(f"[{_stanza_name(uc)}]")
        out.append(f"description = {uc.get('n','')} (UC-{uid}, criticality: {crit})")
        out.append(f"search = {_escape_conf(spl)}")
        out.append(f"cron_schedule = {cron}")
        out.append(f"dispatch.earliest_time = {earliest}")
        out.append(f"dispatch.latest_time = {latest}")
        out.append("enableSched = 0")
        out.append("is_scheduled = 0")
        out.append("disabled = 1")
        out.append("run_n_times = 0")
        out.append(f"alert.severity = {severity}")
        out.append(f"alert_condition = {cond}")
        out.append("alert.track = 1")
        out.append("alert.suppress = 0")
        out.append("action.email = 0")
        # Use the catalog field names verbatim to preserve traceability.
        if uc.get("mitre"):
            out.append(f"action.notable.param.mitre_attack = {','.join(uc['mitre'])}")
        out.append(
            "# Upstream reference: https://github.com/fenre/splunk-monitoring-use-cases"
            f"#use-case-{uid}"
        )
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_macros() -> str:
    out = [CONF_HEADER, ""]
    for cat, macro in sorted(CAT_INDEX_MACRO.items()):
        out.append(f"[{macro}]")
        # The default resolves to `index=*` so every search works on a fresh
        # install; operators are expected to replace the definition with
        # their actual index name(s) for their environment.
        out.append("definition = index=*")
        out.append(
            f"iseval = 0\n# Operator override: replace `index=*` with the specific\n"
            f"# index(es) for category {cat}."
        )
        out.append("")
    # Cross-category helpers.
    for macro, definition, comment in [
        ("uc_index_any", "index=*", "Catch-all — falls back to main indexes"),
        ("uc_fields_cim", '`comment(\"CIM-normalised fields enforced in searches\")`',
         "Placeholder for CIM normalisation decisions"),
    ]:
        out.append(f"[{macro}]")
        out.append(f"definition = {definition}")
        out.append(f"iseval = 0\n# {comment}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


# Minimal eventtypes that cover the most common sourcetypes referenced by
# Quick-Start UCs.  Kept short to avoid polluting the search head namespace.
EVENTTYPES: List[Tuple[str, str, str]] = [
    ("uc_linux_cpu", "sourcetype=cpu", "CPU metrics via Splunk_TA_nix"),
    ("uc_linux_mem", "sourcetype=vmstat", "Memory/swap metrics via vmstat"),
    ("uc_linux_auth", "sourcetype=linux_secure", "Linux authentication events"),
    ("uc_windows_sec", "source=WinEventLog:Security", "Windows Security channel"),
    ("uc_windows_sys", "source=WinEventLog:System", "Windows System channel"),
    ("uc_aws_cloudtrail", "sourcetype=\"aws:cloudtrail\"", "AWS CloudTrail API audit"),
    ("uc_azure_activity", "sourcetype=\"mscs:azure:audit\"", "Azure Activity Log"),
    ("uc_gcp_audit", "sourcetype=\"google:gcp:pubsub:message\"", "GCP audit via Pub/Sub"),
    ("uc_firewall", "tag=firewall", "CIM: firewall-tagged events"),
    ("uc_auth_fail", "tag=authentication action=failure", "CIM: failed auth events"),
]


def render_eventtypes() -> str:
    out = [CONF_HEADER, ""]
    for name, search, desc in EVENTTYPES:
        out.append(f"[{name}]")
        out.append(f"search = {search}")
        out.append(f"#description = {desc}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_tags() -> str:
    out = [CONF_HEADER, ""]
    tag_map = [
        ("eventtype=uc_auth_fail", "authentication", "enabled"),
        ("eventtype=uc_auth_fail", "failure", "enabled"),
        ("eventtype=uc_firewall", "firewall", "enabled"),
        ("eventtype=uc_windows_sec", "authentication", "enabled"),
    ]
    # Group by stanza (eventtype=xxx).
    by_stanza: Dict[str, List[Tuple[str, str]]] = {}
    for stanza, tag, state in tag_map:
        by_stanza.setdefault(stanza, []).append((tag, state))
    for stanza, pairs in by_stanza.items():
        out.append(f"[{stanza}]")
        for tag, state in pairs:
            out.append(f"{tag} = {state}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


NAV_XML = textwrap.dedent(
    """\
    <nav search_view="search" color="#000000">
        <view name="search" default="true" />
        <collection label="Use cases">
            <a href="https://fenre.github.io/splunk-monitoring-use-cases/">Dashboard</a>
            <a href="https://github.com/fenre/splunk-monitoring-use-cases">Source</a>
        </collection>
    </nav>
    """
)


def pick_ucs() -> List[dict]:
    """Return a de-duplicated list of Quick-Start UCs with full metadata."""
    catalog = load_catalog()
    by_id = index_by_id(catalog)
    qs = parse_quickstart()
    seen: set[str] = set()
    picked: List[dict] = []
    for cat in sorted(qs):
        for uid in qs[cat]:
            if uid in seen or uid not in by_id:
                continue
            seen.add(uid)
            picked.append(by_id[uid])
    return picked


def main() -> int:
    os.makedirs(DEFAULT_DIR, exist_ok=True)
    os.makedirs(os.path.join(DEFAULT_DIR, "data", "ui", "nav"), exist_ok=True)
    ucs = pick_ucs()
    print(f"[build_ta] packaging {len(ucs)} saved searches")

    files = {
        "savedsearches.conf": render_savedsearches(ucs),
        "macros.conf": render_macros(),
        "eventtypes.conf": render_eventtypes(),
        "tags.conf": render_tags(),
        "data/ui/nav/default.xml": NAV_XML,
    }
    for rel, contents in files.items():
        path = os.path.join(DEFAULT_DIR, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(contents)
        print(f"  wrote {os.path.relpath(path, REPO_ROOT)}  ({len(contents)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
