#!/usr/bin/env python3
"""
generate_doc_references.py — emit Wikipedia/academic-class "References"
footers on every documentation node in this repository.

For each markdown node:

1. Pulls the curated source library from `data/source-references.json`
   (hand-maintained bibliographic records: authority, year, title,
   publisher, URL, type, edition, identifier).
2. Resolves the doc's primary/supporting citations via
   `data/source-mappings.json` (hand-curated per-doc), with a
   keyword-driven auto-fill for unmapped docs.
3. Cross-checks the doc's body for any bare or labelled URL not yet
   covered and emits cleaned, deduplicated "Additional online sources"
   entries (with sensible labels — no more "[ssae]" or "[contents]"
   garbage).
4. Renders a numbered, anchored reference list in APA-flavoured form:
       [1] Splunk Inc. (2026). *Splunk IT Service Intelligence
           Administration Manual.* Splunk LLC, a Cisco company.
           Retrieved May 11, 2026, from
           https://docs.splunk.com/Documentation/ITSI
5. Adds a small "Related repository documents" / "Cited by" block at
   the very end so cross-navigation survives.
6. Wraps everything in idempotent HTML markers so re-runs are byte-for-
   byte stable.

Usage:
    python3 scripts/generate_doc_references.py            # write
    python3 scripts/generate_doc_references.py --check    # exit 1 if stale
    python3 scripts/generate_doc_references.py --dry-run  # preview
    python3 scripts/generate_doc_references.py --only docs/foo.md
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import sys
from collections import OrderedDict, defaultdict
from pathlib import Path
from urllib.parse import urlparse, urldefrag

REPO = Path(__file__).resolve().parent.parent

BEGIN_MARKER = "<!-- BEGIN-AUTOGENERATED-SOURCES -->"
END_MARKER = "<!-- END-AUTOGENERATED-SOURCES -->"
SECTION_HEADING = "## References"
SUBSECTION_PRIMARY = "### Primary sources"
SUBSECTION_SUPPORTING = "### Supporting sources"
SUBSECTION_ADDITIONAL = "### Additional online sources"
SUBSECTION_REPO_OUT = "### Related repository documents"
SUBSECTION_REPO_IN = "### Cited by"

# Limit how many auto-detected supporting refs we add per doc when no
# explicit mapping exists.
MAX_AUTO_SUPPORTING = 8
MAX_REPO_LINKS_PER_DIRECTION = 20

# Reproducibility: prefer the date stamped in source-references.json
# (_meta.accessedDate). Override with SOURCE_REFS_ACCESSED_DATE env var
# for ad-hoc reruns. Fall back to today's date in UTC.
ACCESSED_DATE_ENV = os.environ.get("SOURCE_REFS_ACCESSED_DATE")

LIBRARY_PATH = REPO / "data" / "source-references.json"
MAPPINGS_PATH = REPO / "data" / "source-mappings.json"
INLINE_PHRASES_PATH = REPO / "data" / "inline-citation-phrases.json"

# Pages that should NOT receive an auto-generated footer because some
# other script fully regenerates them on every build, which would
# clobber our footer. These are listed in `data/auto-generated-docs.json`
# alongside their producer script so the provenance is documented.
SKIP: set[str] = {
    "docs/backlinks.md",
    "CHANGELOG.md",
    "VERSION",
    "docs/compliance-coverage.md",
    "docs/compliance-gaps.md",
    "docs/provenance-coverage.md",
    "docs/scorecard.md",
    "docs/splunk-cloud-compat.md",
    "docs/samples-coverage.md",
    "docs/license-inventory.md",
    "docs/uc-migration-report.md",
}

# URL exclusion patterns — these aren't real sources, just badges /
# anchors / placeholders.
URL_EXCLUDE_PATTERNS = [
    r"^https?://img\.shields\.io/",
    r"^https?://example\.com",
    r"^https?://localhost",
    r"^https?://127\.0\.0\.1",
    r"^https?://\[?[:0-9a-f]+\]?/",          # raw IP addresses
    r"^https?://yourdomain\.",                # placeholder host
]


# ─────────────────────────────────────────────────────────────────────────
# Regexes (carefully tuned)
# ─────────────────────────────────────────────────────────────────────────

# Markdown link `[label](url)` with HTTP(S) target — used for external
# citation extraction.
LINK_RE = re.compile(r"\[([^\[\]\n]+?)\]\((https?://[^\s)>'\"<]+)\)")

# Markdown link `[label](target)` with ANY non-empty target — used for
# building the repo cross-reference graph (where the target is usually
# a relative `.md` path).
ANY_LINK_RE = re.compile(r"\[([^\[\]\n]+?)\]\(([^\s()<>]+)\)")

# Bare URL — EXCLUDE `[`, `]`, `(`, `)` so we don't bleed across
# markdown-link boundaries. This was the source of the `[label](url](url)`
# bug in the previous implementation.
URL_RE = re.compile(r"\bhttps?://[^\s\[\]()>'\"<\\]+")

MARKER_BLOCK_RE = re.compile(
    re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
    re.DOTALL,
)

# Inline citation marker. The class attribute makes it robust to strip
# on every regeneration without harming the human's hand-written prose.
INLINE_CITE_RE = re.compile(
    r'<sup class="ref">\[<a href="#ref-\d+">\d+</a>\]</sup>'
)


# ─────────────────────────────────────────────────────────────────────────
# Library loading
# ─────────────────────────────────────────────────────────────────────────


def load_library() -> tuple[dict[str, dict], str | None]:
    """Return a flat {source_id: record} map plus the meta accessed-date."""
    data = json.loads(LIBRARY_PATH.read_text(encoding="utf-8"))
    meta = data.get("_meta", {})
    accessed = meta.get("accessedDate")
    flat: dict[str, dict] = {}
    for section, entries in data.items():
        if section.startswith("_"):
            continue
        for sid, rec in entries.items():
            if sid in flat:
                raise ValueError(
                    f"Duplicate source-reference id {sid!r} in "
                    f"{LIBRARY_PATH.name}; ids must be globally unique."
                )
            flat[sid] = dict(rec, _section=section, _id=sid)
    return flat, accessed


def load_mappings() -> tuple[dict[str, dict], dict[str, list[str]]]:
    """Return (per-doc explicit mapping, keyword → source-id list)."""
    data = json.loads(MAPPINGS_PATH.read_text(encoding="utf-8"))
    keywords = data.pop("_topic_keywords", {})
    if isinstance(keywords, dict):
        keywords.pop("_comment", None)
    else:
        keywords = {}
    # Drop any underscore-prefixed metadata / section-comment keys.
    for k in [k for k in data if k.startswith("_")]:
        data.pop(k)
    return data, keywords


def load_inline_phrases() -> dict[str, list[str]]:
    """source-id → list of phrase variants for inline marker injection."""
    if not INLINE_PHRASES_PATH.exists():
        return {}
    data = json.loads(INLINE_PHRASES_PATH.read_text(encoding="utf-8"))
    data.pop("_meta", None)
    return {k: list(v) for k, v in data.items() if isinstance(v, list)}


# ─────────────────────────────────────────────────────────────────────────
# Node enumeration
# ─────────────────────────────────────────────────────────────────────────


def collect_md_nodes() -> list[Path]:
    """Every markdown file that participates in the wiki graph."""
    nodes: list[Path] = []
    for p in (REPO / "docs").rglob("*.md"):
        if p.is_file():
            nodes.append(p)
    extras = [
        "AGENTS.md", "AGENTS-EXAMPLES.md", "CONTRIBUTING.md", "GOVERNANCE.md",
        "ROADMAP.md", "README.md", "SECURITY.md", "LEGAL.md",
        "CODE_OF_CONDUCT.md", "CODEBASE-DIAGRAM.md",
        "samples/README.md", "mcp/README.md", "api/README.md",
        "templates/replication-starter/README.md",
        "ta/DA-ITSI-monitoring-use-cases/README.md",
        "eventgen_data/README.md",
        ".github/PULL_REQUEST_TEMPLATE.md",
        ".github/PULL_REQUEST_TEMPLATE/architecture.md",
        ".github/PULL_REQUEST_TEMPLATE/security.md",
    ]
    for rel in extras:
        p = REPO / rel
        if p.is_file():
            nodes.append(p)
    return sorted({p.resolve() for p in nodes})


# ─────────────────────────────────────────────────────────────────────────
# Helpers — code/marker stripping, URL hygiene, label cleanup
# ─────────────────────────────────────────────────────────────────────────


def strip_code_regions(text: str) -> str:
    lines = text.split("\n")
    in_fence = False
    out: list[str] = []
    for line in lines:
        if re.match(r"^[ \t]*```", line):
            in_fence = not in_fence
            out.append("")
            continue
        out.append("" if in_fence else line)
    body = "\n".join(out)
    body = re.sub(r"`[^`\n]*`", "", body)
    return body


def strip_autogen_block(text: str) -> str:
    """Strip our own footer so the body scan never feeds back on itself."""
    return MARKER_BLOCK_RE.sub("", text)


def url_excluded(url: str) -> bool:
    return any(re.match(pat, url) for pat in URL_EXCLUDE_PATTERNS)


def normalize_url(url: str) -> str:
    """Strip trailing punctuation that markdown / prose tends to attach."""
    url = url.rstrip(".,;:!?\"'>")
    while url.endswith(")") and url.count("(") < url.count(")"):
        url = url[:-1]
    return url


def humanise_url(url: str, library_titles: dict[str, str] | None = None) -> str:
    """Best-effort human-readable title for an uncurated URL.

    Falls back ONLY when no curated record covers this URL. Output is
    never a bare slug — we always produce a multi-word descriptor.
    """
    parsed = urlparse(url)
    host = parsed.netloc.lower()
    path = parsed.path.rstrip("/")
    fragment = parsed.fragment

    # Avoid producing weak single-slug labels: package the host as
    # publisher context in every case.
    def humanise_segment(seg: str) -> str:
        seg = re.sub(r"\.html?$", "", seg or "")
        seg = re.sub(r"[_\-]+", " ", seg)
        seg = re.sub(r"([a-z])([A-Z])", r"\1 \2", seg)
        return seg.strip().title()

    last = path.split("/")[-1] if path else ""

    # MITRE ATT&CK and friends
    if "attack.mitre.org" in host:
        m = re.search(r"/techniques/(T\d+(?:\.\d+)?)", path)
        if m:
            return f"MITRE ATT&CK Technique {m.group(1)}"
        m = re.search(r"/tactics/(TA\d+)", path)
        if m:
            return f"MITRE ATT&CK Tactic {m.group(1)}"
        m = re.search(r"/(groups|software|campaigns)/([A-Z0-9]+)", path)
        if m:
            return f"MITRE ATT&CK {m.group(1).rstrip('s').title()} {m.group(2)}"
        return "MITRE ATT&CK Knowledge Base"
    if "d3fend.mitre.org" in host:
        return f"MITRE D3FEND ({humanise_segment(last) or 'index'})"

    # RFCs
    m = re.search(r"rfc[-/]?(\d+)", path, re.IGNORECASE)
    if m and ("rfc-editor.org" in host or "ietf.org" in host or "tools.ietf.org" in host):
        return f"IETF RFC {m.group(1)}"

    # Splunkbase
    if "splunkbase.splunk.com" in host:
        m = re.search(r"/app/(\d+)", path)
        if m:
            return f"Splunkbase app #{m.group(1)}"
        return "Splunkbase"

    # Splunk docs
    if "docs.splunk.com" in host:
        # /Documentation/<Product>/<Version>/<Manual>/<Page>
        m = re.search(r"/Documentation/([^/]+)(?:/([^/]+))?(?:/([^/]+))?(?:/([^/]+))?", path)
        if m:
            prod, ver, manual, page = m.group(1), m.group(2), m.group(3), m.group(4)
            tail = humanise_segment(page or manual or "")
            ver_tag = f" {ver}" if ver and ver not in ("latest", "Latest") else ""
            return f"Splunk {prod}{ver_tag}: {tail}".strip(": ").rstrip()
        m = re.search(r"/observability/(?:en/)?([^/]+)?(?:/([^/]+))?", path)
        if m:
            section, page = m.group(1), m.group(2)
            tail = humanise_segment(page or section or "")
            return f"Splunk Observability: {tail}".strip(": ")
    if "lantern.splunk.com" in host:
        tail = humanise_segment(last) or "article"
        return f"Splunk Lantern: {tail}"

    # NIST publications
    if "csrc.nist.gov" in host or "nist.gov" in host:
        m = re.search(r"(SP\s*\d+-\d+[A-Z]?)", path + " " + fragment, re.IGNORECASE)
        if m:
            ident = m.group(1).upper().replace(" ", " ")
            return f"NIST {ident}"
        if "cyberframework" in path:
            return "NIST Cybersecurity Framework"
        return f"NIST: {humanise_segment(last) or 'publication'}"

    # ISO
    if "iso.org" in host:
        m = re.search(r"(\d{4,5}(?:-\d+)?)", path)
        if m:
            return f"ISO/IEC {m.group(1)}"
        return "ISO/IEC standard"

    # EU regulatory
    if "eur-lex.europa.eu" in host:
        m = re.search(r"/eli/(reg|dir|dec)/(\d{4})/(\d+)", path)
        if m:
            kind, year, num = m.groups()
            label = {"reg": "Regulation", "dir": "Directive", "dec": "Decision"}[kind]
            return f"EU {label} {year}/{num}"
        return f"EUR-Lex: {humanise_segment(last) or 'EU legal text'}"

    # Legislation.gov.uk
    if "legislation.gov.uk" in host:
        m = re.search(r"/(\w+)/(\d{4})/(\d+)", path)
        if m:
            return f"UK Legislation {m.group(2)} c. {m.group(3)}"
        return "UK Legislation: " + (humanise_segment(last) or "statute")

    # PCAOB / SEC / HHS
    if "pcaobus.org" in host:
        if "AS2201" in path:
            return "PCAOB AS 2201"
        return f"PCAOB: {humanise_segment(last) or 'document'}"
    if "sec.gov" in host:
        return f"U.S. SEC: {humanise_segment(last) or 'document'}"
    if "hhs.gov" in host:
        return f"U.S. HHS: {humanise_segment(last) or 'guidance'}"
    if "ftc.gov" in host:
        return f"U.S. FTC: {humanise_segment(last) or 'guidance'}"

    # AICPA
    if "aicpa" in host:
        return f"AICPA: {humanise_segment(last) or 'standard'}"

    # PCI SSC
    if "pcisecuritystandards.org" in host:
        return f"PCI SSC: {humanise_segment(last) or 'document'}"

    # OWASP
    if "owasp.org" in host or "cheatsheetseries.owasp.org" in host:
        return f"OWASP: {humanise_segment(last) or 'resource'}"

    # CISA
    if "cisa.gov" in host:
        return f"CISA: {humanise_segment(last) or 'advisory'}"

    # GitHub
    if "github.com" in host or "raw.githubusercontent.com" in host:
        parts = [p for p in path.split("/") if p]
        if len(parts) >= 2:
            return f"GitHub: {parts[0]}/{parts[1]}"
        if parts:
            return f"GitHub: {parts[0]}"
        return "GitHub"

    # Vendor platforms — produce "<Vendor>: <Page Title>"
    vendor_map: list[tuple[str, str]] = [
        ("learn.microsoft.com", "Microsoft Learn"),
        ("docs.microsoft.com", "Microsoft Docs"),
        ("azure.microsoft.com", "Microsoft Azure"),
        ("docs.aws.amazon.com", "AWS Documentation"),
        ("aws.amazon.com", "AWS"),
        ("cloud.google.com", "Google Cloud"),
        ("kubernetes.io", "Kubernetes"),
        ("docs.docker.com", "Docker"),
        ("redhat.com", "Red Hat"),
        ("access.redhat.com", "Red Hat Customer Portal"),
        ("paloaltonetworks.com", "Palo Alto Networks"),
        ("docs.paloaltonetworks.com", "Palo Alto Networks"),
        ("fortinet.com", "Fortinet"),
        ("docs.fortinet.com", "Fortinet"),
        ("vmware.com", "VMware"),
        ("docs.vmware.com", "VMware"),
        ("documentation.meraki.com", "Cisco Meraki"),
        ("cisco.com", "Cisco"),
        ("developer.cisco.com", "Cisco DevNet"),
        ("crowdstrike.com", "CrowdStrike"),
        ("falcon.crowdstrike.com", "CrowdStrike Falcon"),
        ("okta.com", "Okta"),
        ("developer.okta.com", "Okta Developer"),
        ("developer.hashicorp.com", "HashiCorp Developer"),
        ("hashicorp.com", "HashiCorp"),
        ("elastic.co", "Elastic"),
        ("grafana.com", "Grafana Labs"),
        ("prometheus.io", "Prometheus"),
        ("opentelemetry.io", "OpenTelemetry"),
        ("kubernetes.io", "Kubernetes"),
        ("docs.openshift.com", "OpenShift"),
        ("docs.citrix.com", "Citrix"),
        ("techdocs.f5.com", "F5"),
        ("f5.com", "F5"),
        ("docs.thousandeyes.com", "Cisco ThousandEyes"),
        ("modelcontextprotocol.io", "Model Context Protocol"),
        ("anthropic.com", "Anthropic"),
        ("coalitionforsecureai.org", "Coalition for Secure AI"),
        ("w3.org", "W3C"),
    ]
    for host_pat, vendor in vendor_map:
        if host == host_pat or host.endswith("." + host_pat):
            tail = humanise_segment(last) or humanise_segment(
                (path.strip("/").split("/")[-2] if "/" in path.strip("/") else path.strip("/"))
            )
            return f"{vendor}: {tail}" if tail else vendor

    # Pure-host fallback: prefix with the host so labels are at least
    # publisher-attributed.
    host_clean = host.removeprefix("www.")
    tail = humanise_segment(last) or humanise_segment(path.split("/")[-2] if "/" in path else "")
    if tail:
        return f"{host_clean}: {tail}"
    return host_clean or url


# ─────────────────────────────────────────────────────────────────────────
# Resolution: doc → curated source IDs + uncurated URLs
# ─────────────────────────────────────────────────────────────────────────


def get_doc_mapping(
    src_rel: str,
    mappings: dict[str, dict],
) -> dict[str, list[str]]:
    """Resolve a doc's citation mapping.

    Order:
    1. Exact full path match (e.g. ``docs/foo.md``).
    2. Short key match — ONLY for files under ``docs/`` — so legacy
       short keys like ``foo.md`` still resolve. This branch is
       intentionally NOT applied to repo-root files like
       ``README.md`` to keep the namespace disjoint.
    """
    if src_rel in mappings:
        return mappings[src_rel]
    if src_rel.startswith("docs/"):
        short = src_rel.removeprefix("docs/")
        if short in mappings:
            return mappings[short]
    return {}


def auto_resolve_keywords(
    body: str,
    keywords: dict[str, list[str]],
) -> list[str]:
    """Scan the doc for known terms and return matching source IDs."""
    hits: list[str] = []
    seen: set[str] = set()
    for term, source_ids in keywords.items():
        # Word-boundary, case-insensitive, but require the term to be
        # well-formed (no leading/trailing word chars). Some terms have
        # punctuation (e.g. "ISO/IEC 27001") so we don't \b around them.
        pat = re.escape(term)
        if re.search(rf"(?<![\w-]){pat}(?![\w-])", body, re.IGNORECASE):
            for sid in source_ids:
                if sid not in seen:
                    seen.add(sid)
                    hits.append(sid)
    return hits


def extract_additional_urls(
    body: str,
    covered_urls: set[str],
) -> "OrderedDict[str, str]":
    """URLs that appear in the body but aren't covered by curated sources.

    Returns an OrderedDict url → cleaned label, in first-appearance
    order, so the rendered list is stable.
    """
    found: "OrderedDict[str, str]" = OrderedDict()
    # First, markdown links (`[label](url)`).
    for m in LINK_RE.finditer(body):
        label = m.group(1).strip()
        url = normalize_url(m.group(2).strip())
        url_no_frag = urldefrag(url).url
        if url_excluded(url_no_frag):
            continue
        if url_no_frag in covered_urls:
            continue
        if url in found:
            continue
        # Drop labels that are URL-as-label or single-slug junk.
        url_only_label = label.startswith("http") or label == url
        single_slug = bool(re.fullmatch(r"[a-z0-9._-]{1,20}", label))
        # Markdown bold/italic noise.
        clean_label = re.sub(r"^[*_]+|[*_]+$", "", label).strip()
        if url_only_label or single_slug or not clean_label:
            found[url] = humanise_url(url)
        else:
            found[url] = clean_label
    # Then bare URLs.
    for m in URL_RE.finditer(body):
        url = normalize_url(m.group(0))
        url_no_frag = urldefrag(url).url
        if url_excluded(url_no_frag):
            continue
        if url_no_frag in covered_urls:
            continue
        if url in found:
            continue
        found[url] = humanise_url(url)
    return found


# ─────────────────────────────────────────────────────────────────────────
# Repo-internal graph (Related / Cited by)
# ─────────────────────────────────────────────────────────────────────────


def build_repo_graph(
    nodes: list[Path],
) -> tuple[dict[str, set[str]], dict[str, set[str]]]:
    by_path = {p.resolve(): p for p in nodes}
    in_links: dict[str, set[str]] = defaultdict(set)
    out_links: dict[str, set[str]] = defaultdict(set)

    def rel(p: Path) -> str:
        return str(p.relative_to(REPO)).replace(os.sep, "/")

    for src in nodes:
        raw = src.read_text(encoding="utf-8", errors="replace")
        text = strip_code_regions(strip_autogen_block(raw))
        for m in ANY_LINK_RE.finditer(text):
            raw_target = m.group(2).strip()
            target = raw_target.split("#", 1)[0]
            if not target or not target.endswith(".md"):
                continue
            if target.startswith(("http://", "https://", "mailto:",
                                  "file:", "//")):
                continue
            abs_t = (src.parent / target).resolve()
            if abs_t not in by_path:
                continue
            if abs_t == src.resolve():
                continue
            out_links[rel(src)].add(rel(by_path[abs_t]))
            in_links[rel(by_path[abs_t])].add(rel(by_path[src]))

    return out_links, in_links


# ─────────────────────────────────────────────────────────────────────────
# Rendering — APA-flavoured numbered citations
# ─────────────────────────────────────────────────────────────────────────


_ACCESSED_DATE_RESOLVED: str | None = None


def _resolve_accessed_date(library_accessed: str | None) -> str:
    """Resolve and cache the long-form retrieval date.

    Priority: SOURCE_REFS_ACCESSED_DATE env var > _meta.accessedDate >
    today's UTC date.
    """
    global _ACCESSED_DATE_RESOLVED
    if _ACCESSED_DATE_RESOLVED is not None:
        return _ACCESSED_DATE_RESOLVED
    raw = ACCESSED_DATE_ENV or library_accessed
    if raw:
        try:
            d = dt.date.fromisoformat(raw)
        except ValueError:
            d = dt.datetime.utcnow().date()
    else:
        d = dt.datetime.utcnow().date()
    fmt = "%B %-d, %Y" if sys.platform != "win32" else "%B %#d, %Y"
    _ACCESSED_DATE_RESOLVED = d.strftime(fmt)
    return _ACCESSED_DATE_RESOLVED


def format_accessed_date() -> str:
    """Long-form retrieval date like 'May 11, 2026'."""
    return _resolve_accessed_date(None)


def render_citation(idx: int, rec: dict) -> str:
    """Render one bibliographic record in APA-flavoured form.

    Output shape:
        [N] Authority. (Year). *Title* (Edition). Publisher.
            Identifier. Retrieved <date> from URL
    """
    parts: list[str] = []
    authority = rec.get("authority", "").strip()
    year = rec.get("year")
    month = rec.get("month")
    title = (rec.get("title") or "").strip()
    publisher = rec.get("publisher", "").strip()
    edition = rec.get("edition", "").strip()
    identifier = rec.get("identifier", "").strip()
    url = rec.get("url", "").strip()
    rec_type = rec.get("type", "documentation")

    def _terminated(s: str) -> str:
        s = s.rstrip()
        if s and s[-1] not in ".?!":
            s += "."
        return s

    # Authority (Year[, Month]).
    if authority:
        parts.append(_terminated(authority))
    if year:
        if month:
            try:
                m_name = dt.date(int(year), int(month), 1).strftime("%B")
                parts.append(f"({year}, {m_name}).")
            except (TypeError, ValueError):
                parts.append(f"({year}).")
        else:
            parts.append(f"({year}).")
    # Title.
    if title:
        title_str = f"*{title.rstrip('.')}*"
        if edition:
            title_str += f" ({edition})"
        parts.append(title_str + ".")
    # Publisher (italics not needed; period separates).
    if publisher and publisher != authority:
        parts.append(_terminated(publisher))
    # Identifier (RFC #, ISBN, NIST SP, ELI…)
    if identifier:
        parts.append(_terminated(identifier))
    # Retrieval (for live web sources) or DOI/URL.
    if url:
        if rec_type in {"documentation", "guide", "reference", "specification",
                        "whitepaper"}:
            parts.append(f"Retrieved {format_accessed_date()}, from {url}")
        else:
            # Standards, regulations, books — URL is canonical, no retrieval.
            parts.append(url)

    body = " ".join(parts).strip()
    return f'<a id="ref-{idx}"></a>**[{idx}]** {body}'


def render_section(
    src_rel: str,
    src_path: Path,
    library: dict[str, dict],
    mappings: dict[str, dict],
    keywords: dict[str, list[str]],
    out_links: set[str],
    in_links: set[str],
) -> tuple[str, dict[str, int]]:
    """Render the references footer and return (footer_text, id→number map).

    The id→number map lets the inline-citation pass look up which
    reference number a source-ID was assigned in *this* doc.
    """
    raw = src_path.read_text(encoding="utf-8", errors="replace")
    body = strip_code_regions(strip_autogen_block(raw))

    mapping = get_doc_mapping(src_rel, mappings)
    primary_ids = list(mapping.get("primary", []))
    supporting_ids = list(mapping.get("supporting", []))
    related_ids = list(mapping.get("related", []))

    # Auto-resolve more supporting IDs from keyword scan (capped).
    explicit = set(primary_ids) | set(supporting_ids) | set(related_ids)
    auto_hits = [sid for sid in auto_resolve_keywords(body, keywords)
                 if sid not in explicit]
    auto_added = auto_hits[:MAX_AUTO_SUPPORTING]

    # Validate IDs exist in the library; drop missing with a warning.
    def resolve(ids: list[str]) -> list[dict]:
        out: list[dict] = []
        seen = set()
        for sid in ids:
            if sid in seen:
                continue
            seen.add(sid)
            rec = library.get(sid)
            if rec is None:
                # Silent skip; a missing ID is reported separately by --check.
                continue
            out.append(rec)
        return out

    primary_records = resolve(primary_ids)
    supporting_records = resolve(supporting_ids + auto_added)
    # If the same ID appears in primary and supporting, drop from supporting.
    primary_set = {r["_id"] for r in primary_records}
    supporting_records = [r for r in supporting_records
                          if r["_id"] not in primary_set]
    related_records = [r for r in resolve(related_ids)
                       if r["_id"] not in primary_set
                       and r["_id"] not in {x["_id"] for x in supporting_records}]

    # Sort Supporting / Related sections alphabetically by authority then
    # title. (Primary is kept in author-chosen order so the foremost
    # source comes first.) This produces a stable, bibliography-style
    # ordering rather than first-mapped-wins.
    def _sort_key(r: dict) -> tuple[str, str]:
        # Normalise "European Parliament and Council of the European Union"
        # to behave like a single author surname for ordering.
        a = (r.get("authority") or "").lower()
        a = re.sub(r"^(the|a|an)\s+", "", a)
        # Strip honorifics / corporate suffixes for a cleaner sort.
        a = re.sub(r"\b(inc|llc|ltd|corp|corporation|company|gmbh|sa|nv)\.?\b",
                   "", a).strip()
        return (a, (r.get("title") or "").lower())

    supporting_records = sorted(supporting_records, key=_sort_key)
    related_records = sorted(related_records, key=_sort_key)

    # Track URLs covered by curated records so we don't double-list.
    covered: set[str] = set()
    for r in (*primary_records, *supporting_records, *related_records):
        if r.get("url"):
            covered.add(urldefrag(r["url"]).url)

    additional = extract_additional_urls(body, covered)

    # Number sequentially across all three buckets.
    lines: list[str] = []
    lines.append(BEGIN_MARKER)
    lines.append("")
    lines.append(SECTION_HEADING)
    lines.append("")
    lines.append(
        f"*Auto-generated by `scripts/generate_doc_references.py` from "
        f"`data/source-references.json` and `data/source-mappings.json`. "
        f"Edit those files (or the document body) to change citations; "
        f"this footer is rewritten on every run.*"
    )
    lines.append("")

    idx = 1
    id_to_num: dict[str, int] = {}

    def emit_record_list(heading: str, records: list[dict]) -> None:
        nonlocal idx
        if not records:
            return
        lines.append(heading)
        lines.append("")
        for r in records:
            lines.append(render_citation(idx, r))
            lines.append("")
            id_to_num[r["_id"]] = idx
            idx += 1

    emit_record_list(SUBSECTION_PRIMARY, primary_records)
    emit_record_list(SUBSECTION_SUPPORTING, supporting_records)

    if additional:
        # Filler "extra body URLs" — useful but not editorially curated.
        # Demote into a collapsed <details> fold so they don't outshout
        # the real bibliography. Drop the section entirely when the doc
        # already has plenty of curated refs and the extras are mostly
        # noise.
        skip_additional = (
            len(primary_records) + len(supporting_records) >= 12
            and len(additional) <= 2
        )
        if not skip_additional:
            lines.append("<details>")
            lines.append(
                "<summary>"
                f"Additional online sources cited in the document body "
                f"({len(additional)})"
                "</summary>"
            )
            lines.append("")
            for url, label in additional.items():
                rec = {
                    "title": label,
                    "authority": urlparse(url).netloc.removeprefix("www."),
                    "year": None,
                    "type": "reference",
                    "url": url,
                }
                lines.append(render_citation(idx, rec))
                lines.append("")
                idx += 1
            lines.append("</details>")
            lines.append("")

    # Internal repo cross-refs at the end (kept brief).
    def link_from(src_rel: str, target_rel: str) -> str:
        src_dir = (REPO / src_rel).parent.resolve()
        return os.path.relpath((REPO / target_rel).resolve(), src_dir).replace(os.sep, "/")

    out_sorted = sorted(out_links)
    in_sorted = sorted(in_links)
    if out_sorted:
        lines.append(SUBSECTION_REPO_OUT)
        lines.append("")
        for t in out_sorted[:MAX_REPO_LINKS_PER_DIRECTION]:
            lines.append(f"- [`{t}`]({link_from(src_rel, t)})")
        if len(out_sorted) > MAX_REPO_LINKS_PER_DIRECTION:
            lines.append(f"- _… and {len(out_sorted) - MAX_REPO_LINKS_PER_DIRECTION} "
                         f"more (see [`docs/backlinks.md`]"
                         f"({link_from(src_rel, 'docs/backlinks.md')}))._")
        lines.append("")
    if in_sorted:
        lines.append(SUBSECTION_REPO_IN)
        lines.append("")
        for s in in_sorted[:MAX_REPO_LINKS_PER_DIRECTION]:
            lines.append(f"- [`{s}`]({link_from(src_rel, s)})")
        if len(in_sorted) > MAX_REPO_LINKS_PER_DIRECTION:
            lines.append(f"- _… and {len(in_sorted) - MAX_REPO_LINKS_PER_DIRECTION} "
                         f"more (see [`docs/backlinks.md`]"
                         f"({link_from(src_rel, 'docs/backlinks.md')}))._")
        lines.append("")

    if idx == 1 and not (out_sorted or in_sorted):
        lines.append(
            "_No external sources are cited inline in this document and "
            "no repository documents currently link to it._"
        )
        lines.append("")

    lines.append(END_MARKER)
    return "\n".join(lines), id_to_num


# ─────────────────────────────────────────────────────────────────────────
# Insert / replace block
# ─────────────────────────────────────────────────────────────────────────


def _scan_protected_spans(text: str) -> list[tuple[int, int]]:
    """Return (start, end) byte spans we must NEVER inject into.

    Protected: fenced code blocks, inline code, ATX/Setext headings,
    HTML tags, YAML frontmatter, markdown link `[label](url)` body,
    URL of a link, and the auto-generated footer.
    """
    spans: list[tuple[int, int]] = []

    # Fenced code blocks
    for m in re.finditer(r"^[ \t]*```.*?\n.*?^[ \t]*```",
                         text, re.DOTALL | re.MULTILINE):
        spans.append((m.start(), m.end()))

    # Inline `code`
    for m in re.finditer(r"`[^`\n]*`", text):
        spans.append((m.start(), m.end()))

    # ATX headings
    for m in re.finditer(r"^[ \t]*#{1,6}.*$", text, re.MULTILINE):
        spans.append((m.start(), m.end()))

    # Setext underlines
    for m in re.finditer(r"^[ \t]*(=+|-+)[ \t]*$", text, re.MULTILINE):
        spans.append((m.start(), m.end()))

    # HTML tags (single line, conservative)
    for m in re.finditer(r"<[^<>\n]+>", text):
        spans.append((m.start(), m.end()))

    # YAML frontmatter
    if text.startswith("---\n"):
        m = re.match(r"---\n.*?\n---\n", text, re.DOTALL)
        if m:
            spans.append((m.start(), m.end()))

    # Existing markdown links — protect both label and URL.
    for m in ANY_LINK_RE.finditer(text):
        spans.append((m.start(), m.end()))

    # Reference-style link definitions `[id]: url`
    for m in re.finditer(r"^[ \t]*\[[^\]\n]+\]:[ \t]*\S+", text, re.MULTILINE):
        spans.append((m.start(), m.end()))

    # Our own footer
    for m in MARKER_BLOCK_RE.finditer(text):
        spans.append((m.start(), m.end()))

    spans.sort()
    return spans


def _in_protected(pos: int, spans: list[tuple[int, int]]) -> bool:
    # Binary-search style scan; spans is sorted.
    for s, e in spans:
        if pos < s:
            return False
        if s <= pos < e:
            return True
    return False


def _inline_marker_html(num: int) -> str:
    return f'<sup class="ref">[<a href="#ref-{num}">{num}</a>]</sup>'


def inject_inline_citations(
    body: str,
    id_to_num: dict[str, int],
    phrases: dict[str, list[str]],
) -> str:
    """Add inline `[N]` citation markers at the first mention of each
    cited source's phrase. Idempotent (caller is expected to have stripped
    pre-existing markers before this runs).
    """
    if not id_to_num:
        return body

    # Build the candidate (phrase, source_id) list, longest phrases first
    # so "ISO/IEC 27001:2022" beats "ISO 27001".
    candidates: list[tuple[str, str]] = []
    for sid in id_to_num:
        for phrase in phrases.get(sid, []):
            candidates.append((phrase, sid))
    candidates.sort(key=lambda x: -len(x[0]))

    protected_spans = _scan_protected_spans(body)

    annotated_ids: set[str] = set()
    # We do up to one insertion per source, at the first non-protected
    # match. Build a list of (insertion_position, source_id, num) then
    # apply them all at once to avoid index drift.
    insertions: list[tuple[int, str, int]] = []
    for phrase, sid in candidates:
        if sid in annotated_ids:
            continue
        # Case-sensitive, word-boundary anchored.
        pat = re.compile(
            r"(?<![\w])" + re.escape(phrase) + r"(?![\w])"
        )
        for m in pat.finditer(body):
            pos = m.start()
            if _in_protected(pos, protected_spans):
                continue
            # Position the marker AFTER the matched text.
            insertions.append((m.end(), sid, id_to_num[sid]))
            annotated_ids.add(sid)
            break

    if not insertions:
        return body

    insertions.sort(key=lambda x: x[0])
    parts: list[str] = []
    cursor = 0
    for end, _sid, num in insertions:
        parts.append(body[cursor:end])
        parts.append(_inline_marker_html(num))
        cursor = end
    parts.append(body[cursor:])
    return "".join(parts)


def apply_to_file(
    src_path: Path,
    src_rel: str,
    library: dict[str, dict],
    mappings: dict[str, dict],
    keywords: dict[str, list[str]],
    inline_phrases: dict[str, list[str]],
    out_links: set[str],
    in_links: set[str],
) -> tuple[str, str]:
    original = src_path.read_text(encoding="utf-8", errors="replace")

    block, id_to_num = render_section(
        src_rel, src_path, library, mappings, keywords,
        out_links, in_links,
    )

    # 1. Replace the footer block (or append if missing).
    if BEGIN_MARKER in original and END_MARKER in original:
        new = MARKER_BLOCK_RE.sub(lambda m: block, original, count=1)
    else:
        sep = "" if original.endswith("\n") else "\n"
        new = original + sep + "\n---\n\n" + block + "\n"

    # 2. Strip ALL pre-existing inline citation markers (idempotency).
    new = INLINE_CITE_RE.sub("", new)

    # 3. Re-inject inline markers using *current* per-doc ref numbering.
    new = inject_inline_citations(new, id_to_num, inline_phrases)

    return original, new


# ─────────────────────────────────────────────────────────────────────────
# Entrypoint
# ─────────────────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if any file would change.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would change without writing.")
    parser.add_argument("--only", default=None,
                        help="Only operate on files matching this glob pattern.")
    parser.add_argument("--validate-library", action="store_true",
                        help="Verify every mapping ID resolves to a record; "
                             "exit 1 on any dangling reference.")
    args = parser.parse_args(argv)

    library, library_accessed = load_library()
    _resolve_accessed_date(library_accessed)
    mappings, keywords = load_mappings()
    inline_phrases = load_inline_phrases()

    if args.validate_library:
        missing: list[tuple[str, str]] = []
        for doc, m in mappings.items():
            for bucket in ("primary", "supporting", "related"):
                for sid in m.get(bucket, []):
                    if sid not in library:
                        missing.append((doc, sid))
        for term, ids in keywords.items():
            for sid in ids:
                if sid not in library:
                    missing.append((f"_topic_keywords/{term}", sid))
        for sid in inline_phrases:
            if sid not in library:
                missing.append(("inline-citation-phrases.json", sid))
        if missing:
            print(f"FAIL: {len(missing)} dangling source IDs in source-mappings.json:")
            for doc, sid in missing[:30]:
                print(f"  {doc}  →  {sid}")
            return 1
        print(f"OK: {len(library)} source records, all mapping IDs resolve.")
        return 0

    nodes = collect_md_nodes()
    out_links_map, in_links_map = build_repo_graph(nodes)

    def rel_of(p: Path) -> str:
        return str(p.relative_to(REPO)).replace(os.sep, "/")

    if args.only:
        import fnmatch
        nodes = [p for p in nodes if fnmatch.fnmatch(rel_of(p), args.only)]

    changed = 0
    skipped = 0
    file_changes: list[str] = []
    for src in nodes:
        src_rel = rel_of(src)
        if src_rel in SKIP:
            skipped += 1
            continue
        outs = out_links_map.get(src_rel, set())
        ins = in_links_map.get(src_rel, set())
        original, new = apply_to_file(src, src_rel, library, mappings,
                                      keywords, inline_phrases, outs, ins)
        if original == new:
            continue
        changed += 1
        file_changes.append(src_rel)
        if not args.check and not args.dry_run:
            src.write_text(new, encoding="utf-8")

    if args.check:
        if changed:
            print(f"FAIL: {changed} files have stale auto-references.")
            for f in file_changes[:15]:
                print(f"  - {f}")
            if changed > 15:
                print(f"  … and {changed - 15} more.")
            print("Run scripts/generate_doc_references.py to refresh.")
            return 1
        print(f"OK: all {len(nodes)} docs have up-to-date auto-references.")
        return 0

    print(f"Processed {len(nodes)} files; "
          f"{changed} rewritten, {skipped} skipped, "
          f"{len(nodes) - changed - skipped} already current.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
