#!/usr/bin/env python3
"""
generate_backlinks.py — emit a per-doc "What links here" index.

A wiki staple: for every documentation page in the corpus, list which
other pages link to it (with the linking section anchor when present).
The output `docs/backlinks.md` is a single committable artefact a reader
can scroll or grep through to find what mentions a target doc.

Run before commits:
    python3 scripts/generate_backlinks.py
    python3 scripts/generate_backlinks.py --check  # exit 1 if stale
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUTPUT = REPO / "docs" / "backlinks.md"

LINK_RE = re.compile(r"\[([^\]]+?)\]\(([^)]+?)\)")

# Auto-generated "Sources and references" footer markers (from
# scripts/generate_doc_references.py). The footer's own outbound links
# are bookkeeping noise from the backlinks point of view — without
# stripping them this generator would never converge.
AUTOGEN_BEGIN = "<!-- BEGIN-AUTOGENERATED-SOURCES -->"
AUTOGEN_END = "<!-- END-AUTOGENERATED-SOURCES -->"
AUTOGEN_RE = re.compile(
    re.escape(AUTOGEN_BEGIN) + r".*?" + re.escape(AUTOGEN_END),
    re.DOTALL,
)


def collect_md_files() -> list[Path]:
    """All markdown files we treat as nodes in the wiki graph."""
    nodes: list[Path] = []
    for p in (REPO / "docs").rglob("*.md"):
        if p.is_file():
            nodes.append(p)
    extras = [
        "AGENTS.md", "AGENTS-EXAMPLES.md", "CONTRIBUTING.md", "GOVERNANCE.md",
        "CHANGELOG.md", "ROADMAP.md", "README.md", "SECURITY.md", "LEGAL.md",
        "CODE_OF_CONDUCT.md", "CODEBASE-DIAGRAM.md",
        "samples/README.md", "mcp/README.md", "api/README.md",
        "templates/replication-starter/README.md",
        "ta/DA-ITSI-monitoring-use-cases/README.md",
        "eventgen_data/README.md",
        ".github/PULL_REQUEST_TEMPLATE.md",
        ".github/PULL_REQUEST_TEMPLATE/architecture.md",
        ".github/PULL_REQUEST_TEMPLATE/security.md",
    ]
    for rel in extras:
        p = REPO / rel
        if p.is_file():
            nodes.append(p)
    for p in (REPO / ".cursor" / "skills").rglob("*.md"):
        if p.is_file():
            nodes.append(p)
    return sorted({p.resolve() for p in nodes})


def to_repo_rel(path: Path) -> str:
    return str(path.relative_to(REPO)).replace(os.sep, "/")


def collect_inbound(nodes: list[Path]) -> dict[str, list[tuple[str, str]]]:
    """Map repo-relative target path → list of (linking file, link text)."""
    by_path = {to_repo_rel(p): p for p in nodes}
    inbound: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for src in nodes:
        text = src.read_text(encoding="utf-8", errors="replace")
        # Strip the auto-generated references footer so its bookkeeping
        # links don't recurse into the backlinks graph.
        text = AUTOGEN_RE.sub("", text)
        # Strip code fences and inline code so example snippets that
        # contain markdown-link syntax don't pollute the index.
        lines = text.split("\n")
        in_fence = False
        cleaned: list[str] = []
        for line in lines:
            if re.match(r"^[ \t]*```", line):
                in_fence = not in_fence
                cleaned.append("")
                continue
            cleaned.append("" if in_fence else line)
        scan_text = "\n".join(cleaned)
        scan_text = re.sub(r"`[^`\n]*`", "", scan_text)
        seen_in_src: set[str] = set()
        for m in LINK_RE.finditer(scan_text):
            label = m.group(1).strip()
            raw = m.group(2).strip()
            tgt = raw.split("#", 1)[0]
            if not tgt or not tgt.endswith(".md"):
                continue
            if tgt.startswith(("http", "mailto:", "file:", "//")):
                continue
            abs_target = (src.parent / tgt).resolve()
            try:
                rel = str(abs_target.relative_to(REPO)).replace(os.sep, "/")
            except ValueError:
                continue
            if rel not in by_path:
                continue
            if rel == to_repo_rel(src):
                continue
            key = (to_repo_rel(src), rel)
            if key in seen_in_src:
                continue
            seen_in_src.add(key)
            inbound[rel].append((to_repo_rel(src), label[:80]))
    for rel in inbound:
        inbound[rel].sort()
    return inbound


def render(inbound: dict[str, list[tuple[str, str]]], nodes: list[Path]) -> str:
    out = [
        "# Backlinks — What links here",
        "",
        "> **Generated** by `scripts/generate_backlinks.py`. Do not edit by hand.",
        "> For every documentation node, this page lists the other pages",
        "> that link to it (the inbound edges of the doc graph). Use it as",
        "> the wiki-style \"What links here\" of this repository.",
        "",
        "Sorted by target path. Linking pages appear in alphabetical order.",
        "",
        "---",
        "",
    ]
    all_targets = sorted({to_repo_rel(p) for p in nodes})
    total_edges = 0
    pages_with_inbound = 0
    for tgt in all_targets:
        edges = inbound.get(tgt, [])
        out.append(f"## `{tgt}`")
        out.append("")
        if not edges:
            out.append("_No inbound links yet._")
            out.append("")
            continue
        pages_with_inbound += 1
        total_edges += len(edges)
        seen_src: set[str] = set()
        for src, _label in edges:
            if src in seen_src:
                continue
            seen_src.add(src)
            backlinks_dir = (REPO / "docs").resolve()
            src_abs = (REPO / src).resolve()
            try:
                rel = os.path.relpath(src_abs, backlinks_dir).replace(os.sep, "/")
            except ValueError:
                rel = src
            out.append(f"- [`{src}`]({rel})")
        out.append("")
    out.insert(
        9,
        f"_{len(all_targets)} pages indexed; {pages_with_inbound} have at "
        f"least one inbound link; {total_edges} unique source→target edges._",
    )
    out.insert(10, "")
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if the committed backlinks index is stale.")
    args = parser.parse_args(argv)

    nodes = collect_md_files()
    inbound = collect_inbound(nodes)
    rendered = render(inbound, nodes)

    if args.check:
        if not OUTPUT.exists():
            print(f"FAIL: {OUTPUT.relative_to(REPO)} does not exist.")
            return 1
        current = OUTPUT.read_text(encoding="utf-8")
        if current != rendered:
            print(f"FAIL: {OUTPUT.relative_to(REPO)} is stale. "
                  f"Run scripts/generate_backlinks.py to refresh.")
            return 1
        print(f"OK: {OUTPUT.relative_to(REPO)} is up to date.")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(REPO)} "
          f"({len(nodes)} pages, "
          f"{sum(len(v) for v in inbound.values())} edges).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
