#!/usr/bin/env bash
# Package Splunk apps under splunk-apps/ as Splunk-compatible .spl
# archives for direct installation or Splunkbase upload.
#
# Usage:
#   scripts/package_splunk_apps.sh [output_dir] [app_id ...]
#   scripts/package_splunk_apps.sh [output_dir] --all
#
# Default behaviour:
#   * output_dir = dist/
#   * If no app ids are provided, only the unified recommender app and
#     its optional companion TA are packaged, since those are the only
#     two apps this repo officially ships:
#       - splunk-uc-recommender       (Splunk Cloud safe)
#       - splunk-uc-recommender-ta    (Enterprise only)
#   * Pass app ids as positional args to override (e.g. only one app).
#   * Pass --all to opt back into packaging every splunk-apps/<id>/
#     directory (used by maintainers when refreshing legacy
#     per-regulation slices generated by scripts/generate_splunk_app.py;
#     not part of the standard release).
#
# Output layout:
#   <output_dir>/<app_id>-<version>.spl
#   <output_dir>/<app_id>-<version>.spl.sha256
#   <output_dir>/SHA256SUMS.txt          (combined checksum manifest)
#   <output_dir>/splunk-apps-manifest.md (per-file sizes + checksums)
#
# The script:
#   1) collects the list of app ids to package (default vs --all vs explicit),
#   2) strips development detritus (local/, .DS_Store, __pycache__),
#   3) tars with the fixed prefix matching the app name,
#   4) emits SHA-256 per file and a combined SHA256SUMS.txt.
#
# Intentionally POSIX-y so it runs on macOS BSD tar, GNU tar, and
# GitHub-hosted Ubuntu runners.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_DIR="${1:-${REPO_ROOT}/dist}"
shift || true

# Default release scope: only the unified recommender + its companion TA.
DEFAULT_APPS=(splunk-uc-recommender splunk-uc-recommender-ta)

# Parse remaining args.
PACKAGE_ALL=0
EXPLICIT_APPS=()
for arg in "$@"; do
    case "${arg}" in
        --all)
            PACKAGE_ALL=1
            ;;
        --help|-h)
            sed -n '2,33p' "$0"
            exit 0
            ;;
        --*)
            echo "error: unknown flag '${arg}'" >&2
            exit 2
            ;;
        *)
            EXPLICIT_APPS+=("${arg}")
            ;;
    esac
done

APPS_DIR="${REPO_ROOT}/splunk-apps"
if [ ! -d "${APPS_DIR}" ]; then
    echo "error: ${APPS_DIR} not found" >&2
    exit 1
fi

mkdir -p "${OUT_DIR}"
: > "${OUT_DIR}/SHA256SUMS.txt"

# Build the candidate list from disk.
ALL_DISCOVERED=()
while IFS= read -r -d '' manifest; do
    ALL_DISCOVERED+=("$(basename "$(dirname "${manifest}")")")
done < <(find "${APPS_DIR}" -mindepth 2 -maxdepth 2 -name app.manifest -print0 | sort -z)

# Decide which apps to actually package.
APP_IDS=()
if [ "${PACKAGE_ALL}" -eq 1 ]; then
    APP_IDS=("${ALL_DISCOVERED[@]}")
elif [ ${#EXPLICIT_APPS[@]} -gt 0 ]; then
    APP_IDS=("${EXPLICIT_APPS[@]}")
else
    APP_IDS=("${DEFAULT_APPS[@]}")
fi

# Sanity-check that every requested id actually exists on disk.
for id in "${APP_IDS[@]}"; do
    if [ ! -f "${APPS_DIR}/${id}/app.manifest" ]; then
        echo "error: ${APPS_DIR}/${id}/app.manifest not found" >&2
        echo "       (run python3 scripts/generate_recommender_app.py first" >&2
        echo "        to materialise the unified recommender app)" >&2
        exit 1
    fi
done

if [ ${#APP_IDS[@]} -eq 0 ]; then
    echo "error: no apps to package" >&2
    exit 1
fi

sha_tool=""
if command -v shasum >/dev/null 2>&1; then
    sha_tool="shasum -a 256"
elif command -v sha256sum >/dev/null 2>&1; then
    sha_tool="sha256sum"
fi

manifest_md="${OUT_DIR}/splunk-apps-manifest.md"
{
    echo "# Splunk Apps — packaged artefacts"
    echo
    echo "| App | Version | File | Size | SHA-256 |"
    echo "|-----|---------|------|------|---------|"
} > "${manifest_md}"

for APP_ID in "${APP_IDS[@]}"; do
    APP_DIR="${APPS_DIR}/${APP_ID}"
    MANIFEST="${APP_DIR}/app.manifest"

    # Prefer the embedded manifest version; fall back to VERSION file.
    VERSION="$(
        python3 - "${MANIFEST}" "${REPO_ROOT}/VERSION" <<'PY'
import json, sys, pathlib
manifest_path = pathlib.Path(sys.argv[1])
fallback = pathlib.Path(sys.argv[2])
try:
    data = json.loads(manifest_path.read_text())
    version = data.get("info", {}).get("id", {}).get("version")
    if version:
        print(version)
        raise SystemExit(0)
except Exception:
    pass
try:
    print(fallback.read_text().strip())
except Exception:
    print("0.0.0")
PY
    )"

    OUT_FILE="${OUT_DIR}/${APP_ID}-${VERSION}.spl"

    TMP_STAGE="$(mktemp -d)"
    trap 'rm -rf "${TMP_STAGE}"' EXIT
    cp -R "${APP_DIR}" "${TMP_STAGE}/${APP_ID}"

    # Strip runtime overrides and local dev artefacts.
    rm -rf "${TMP_STAGE}/${APP_ID}/local"
    find "${TMP_STAGE}/${APP_ID}" -name ".DS_Store" -delete
    find "${TMP_STAGE}/${APP_ID}" -name "__pycache__" -type d -prune -exec rm -rf {} +

    tar -C "${TMP_STAGE}" -czf "${OUT_FILE}" "${APP_ID}"
    rm -rf "${TMP_STAGE}"
    trap - EXIT

    SIZE_BYTES="$(wc -c < "${OUT_FILE}" | tr -d '[:space:]')"
    SIZE_HUMAN="$(du -h "${OUT_FILE}" | cut -f1)"

    if [ -n "${sha_tool}" ]; then
        SUM="$(${sha_tool} "${OUT_FILE}" | awk '{print $1}')"
        printf '%s\n' "${SUM}" > "${OUT_FILE}.sha256"
        # Combined manifest uses just the basename.
        printf '%s  %s\n' "${SUM}" "$(basename "${OUT_FILE}")" >> "${OUT_DIR}/SHA256SUMS.txt"
    else
        SUM="(no shasum tool available)"
    fi

    printf '| %s | %s | `%s` | %s | `%s` |\n' \
        "${APP_ID}" "${VERSION}" "$(basename "${OUT_FILE}")" "${SIZE_HUMAN}" "${SUM}" \
        >> "${manifest_md}"

    echo "Packaged ${OUT_FILE} (${SIZE_BYTES} bytes) sha256=${SUM}"
done

echo
echo "Wrote ${#APP_IDS[@]} .spl archive(s) under ${OUT_DIR}"
echo "Combined checksums: ${OUT_DIR}/SHA256SUMS.txt"
echo "Per-file manifest:  ${manifest_md}"
