#!/usr/bin/env python3
"""Remove auto-generated CIM SPL blocks that reference invalid CIM datamodels/datasets.

Targets blocks of the form:
  - **CIM SPL:**
  ```spl
  | tstats summariesonly=t ... from datamodel=<MODEL>[.<DATASET>] ... | sort - ...
  ```

If the (model, dataset) pair is not valid per Splunk CIM 6.x, the block is
removed so it can be regenerated by scripts/generate_cim_spl.py with corrected
logic. Pre-existing hand-written blocks (which typically use the `summariesonly`
macro rather than the literal flag) are preserved.
"""
from __future__ import annotations

import glob
import os
import re
import sys
from typing import Dict, Set

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
USE_CASES_GLOB = os.path.join(REPO_ROOT, "use-cases", "cat-*.md")

CIM_DATASETS: Dict[str, Set[str]] = {
    "Alerts": {"Alerts"},
    "Application_State": {"All_Application_State", "Ports", "Processes", "Services"},
    "Authentication": {
        "Authentication",
        "Default_Authentication",
        "Insecure_Authentication",
        "Privileged_Authentication",
        "Failed_Authentication",
        "Successful_Authentication",
        "Successful_Default_Authentication",
        "Failed_Default_Authentication",
        "Successful_Privileged_Authentication",
        "Failed_Privileged_Authentication",
    },
    "Certificates": {"All_Certificates", "SSL"},
    "Change": {
        "All_Changes",
        "Account_Management",
        "Auditing_Changes",
        "Endpoint_Changes",
        "Network_Changes",
        "Instance_Changes",
    },
    "Compute_Inventory": {
        "All_Inventory",
        "CPU",
        "Memory",
        "Network",
        "Storage",
        "OS",
        "User",
        "Virtual_OS",
        "Snapshot",
        "Hypervisor",
    },
    "Data_Access": {"Data_Access"},
    "Databases": {
        "All_Databases",
        "Database_Instance",
        "Instance_Stats",
        "Lock_Stats",
        "Session_Info",
        "Tablespace",
        "Query_Stats",
        "Query",
    },
    "Data_Loss_Prevention": {"DLP_Incidents"},
    "Email": {"All_Email", "Delivery", "Content", "Filtering"},
    "Endpoint": {"Ports", "Processes", "Filesystem", "Services", "Registry"},
    "Event_Signatures": {"Signatures"},
    "Interprocess_Messaging": {"All_Interprocess_Messaging"},
    "Intrusion_Detection": {"IDS_Attacks"},
    "Inventory": {"All_Inventory", "CPU", "Memory", "Network", "Storage", "OS", "User", "Virtual_OS", "Snapshot"},
    "JVM": {"JVM", "Threading", "Memory", "Runtime", "Classloading", "OS"},
    "Malware": {"Malware_Attacks", "Malware_Operations"},
    "Network_Resolution": {"DNS"},
    "Network_Sessions": {"All_Sessions", "DHCP", "Session_Start", "Session_End", "VPN"},
    "Network_Traffic": {"All_Traffic"},
    "Performance": {"All_Performance", "CPU", "Facilities", "FacilitiesAlerts", "Memory", "Network", "OS", "Storage"},
    "Splunk_Audit": {"Search_Activity", "Modular_Actions"},
    "Ticket_Management": {"All_Ticket_Management", "Change", "Incident", "Problem"},
    "Updates": {"Updates"},
    "Vulnerabilities": {"Vulnerabilities"},
    "Web": {"Web"},
}

# CIM SPL block pattern: marker line, blank lines, ```spl fence, body, ``` close
# Greedy match the body line by line to grab exactly one fenced block.
BLOCK_RE = re.compile(
    r"(?P<marker>^- \*\*CIM SPL:\*\*\s*\n)"  # the marker line
    r"(?P<fence>```spl\s*\n)"  # open fence
    r"(?P<body>.*?)"  # body
    r"(?P<close>\n```\s*\n)",  # close fence
    re.DOTALL | re.MULTILINE,
)

# Extract datamodel=<MODEL>[.<DATASET>] from body
DM_RE = re.compile(
    r"\bfrom\s+datamodel\s*=\s*([A-Za-z_][A-Za-z0-9_/.,;+()\-]*)",
    re.IGNORECASE,
)


def is_valid_cim_ref(ref: str) -> bool:
    """Return True if `Model` or `Model.Dataset` is valid per CIM 6.x."""
    ref = ref.strip()
    if "." in ref:
        model, dataset = ref.split(".", 1)
        model = model.strip()
        # dataset may still be followed by junk; take token of letters/underscores
        m = re.match(r"([A-Za-z_][A-Za-z0-9_]*)", dataset)
        if not m:
            return False
        dataset = m.group(1)
        return model in CIM_DATASETS and dataset in CIM_DATASETS[model]
    return ref in CIM_DATASETS


def process_file(path: str, dry_run: bool = False) -> int:
    with open(path, encoding="utf-8") as f:
        text = f.read()
    removed = 0
    new_text = text
    # Work through matches from end to start so offsets remain valid
    matches = list(BLOCK_RE.finditer(text))
    edits = []  # list of (start, end) to drop
    for m in matches:
        body = m.group("body")
        # Only target AUTO-generated blocks: they start with "| tstats summariesonly=t"
        # and reference `from datamodel=...`. Hand-written blocks that use the macro
        # ```| tstats `summariesonly` ...``` are left alone unless explicitly invalid.
        first_line = body.splitlines()[0].strip() if body else ""
        dm_match = DM_RE.search(body)
        if not dm_match:
            continue
        ref = dm_match.group(1)
        # Take only the cleaner leading portion up to whitespace
        ref = re.split(r"[\s|]", ref, 1)[0]
        if is_valid_cim_ref(ref):
            continue
        # Invalid reference: schedule removal of this whole block
        edits.append((m.start(), m.end(), ref, first_line))

    if not edits:
        return 0

    # Apply in reverse order
    lst = list(new_text)
    edits.sort(key=lambda e: e[0], reverse=True)
    for start, end, ref, first in edits:
        del lst[start:end]
        removed += 1
        print(f"  DROP {os.path.basename(path)}: datamodel={ref!r} -> {first[:100]}")

    new_text = "".join(lst)
    if removed and not dry_run:
        with open(path, "w", encoding="utf-8") as f:
            f.write(new_text)
    return removed


def main() -> int:
    dry = "--dry-run" in sys.argv
    files = sorted(glob.glob(USE_CASES_GLOB))
    total = 0
    for path in files:
        n = process_file(path, dry)
        if n:
            print(f"{os.path.basename(path)}: removed {n}")
        total += n
    print(f"Total removed: {total}")
    if dry:
        print("(dry-run — no files written)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
