/**
 * Source-of-truth invariants for the non-technical view catalogue
 * after the 2026-05-17 inversion (typed module is canonical; legacy
 * JS is generated by `apps/web/scripts/emit-legacy.ts`).
 *
 * These three tests pin the SOT contract that the CI drift guard in
 * `validate.yml`'s `frontend` job enforces at workflow time. Running
 * them locally catches emitter regressions during dev so a contributor
 * does not push a broken round-trip and discover it in CI.
 *
 *   1. The typed `NON_TECHNICAL` export from
 *      `src/data/non-technical-view.data.ts` is deep-equal to the
 *      catalogue loaded from the on-disk legacy JS file. Both sources
 *      must agree on every category, area, field, and UC ref.
 *
 *   2. `renderLegacy(NON_TECHNICAL)` (the emit script's pure render
 *      function, imported directly so this test does NOT execute
 *      side-effects on disk) is byte-identical to the on-disk
 *      `non-technical-view.js` file.
 *
 *   3. The emitter's output starts with the documented prologue and
 *      ends with `};\n` (one trailing newline) — pins the file shape
 *      that pre-existing consumers of the legacy script depend on.
 */

import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import { renderLegacy } from "../../scripts/emit-legacy.ts";
import {
  LEGACY_NON_TECHNICAL_JS_PATH,
  loadCatalogFromLegacyJs,
  NON_TECHNICAL,
} from "../non-technical-view.ts";

describe("SOT inversion (2026-05-17)", () => {
  it("typed NON_TECHNICAL matches the legacy-loaded catalog value-for-value", () => {
    const fromLegacy = loadCatalogFromLegacyJs();
    expect(NON_TECHNICAL).toEqual(fromLegacy);
  });

  it("renderLegacy(NON_TECHNICAL) is byte-identical to the on-disk non-technical-view.js", () => {
    const onDisk = readFileSync(LEGACY_NON_TECHNICAL_JS_PATH, "utf-8");
    const emitted = renderLegacy(NON_TECHNICAL);
    expect(emitted).toBe(onDisk);
  });

  it("emitter output has the expected prologue and a single trailing newline", () => {
    const emitted = renderLegacy(NON_TECHNICAL);
    expect(emitted.startsWith("/**\n")).toBe(true);
    expect(emitted).toContain("window.NON_TECHNICAL = {");
    expect(emitted.endsWith("};\n")).toBe(true);
    // Defensive: no double trailing newline regressions.
    expect(emitted.endsWith("};\n\n")).toBe(false);
  });
});
