"""Unit tests for the citation-chain hook in
``src/splunk_uc/generators/evidence_packs.py``.

Background
==========

``python -m splunk_uc generate-evidence-packs`` (write mode) rewrites
each ``docs/evidence-packs/*.md`` from scratch. The committed copies
also carry inline ``<sup class="ref">[<a href="#ref-N">N</a>]</sup>``
citation markers and an APA-formatted References footer between the
``<!-- BEGIN-AUTOGENERATED-SOURCES -->`` /
``<!-- END-AUTOGENERATED-SOURCES -->`` sentinels — bookkeeping owned by
``scripts/generate_doc_references.py``.

Because the evidence-pack generator deliberately strips that markup in
``--check`` mode (see ``_strip_citation_markers``), a stand-alone write
run that *didn't* re-invoke the citation generator would silently leave
the working tree with ~1000 deleted citation lines.  CI / the Makefile
already enforce the chained ordering, but ad-hoc local runs broke
without an in-process chain.

These tests pin the chain contract:

1. After a successful write, ``_chain_doc_references`` invokes
   ``scripts/generate_doc_references.py --only docs/evidence-packs/*.md``
   via ``subprocess.run`` with the repository root as cwd.
2. A missing citation script degrades gracefully to a warning and
   exit 0 — the evidence-pack body has been written, the absence of the
   citation generator should not turn a successful write into a hard
   failure (small forks / stripped deployments).
3. A non-zero exit from the citation generator propagates: callers
   (including the CLI) get the citation script's failure code so the
   regression that motivated the chain (stripped citations getting
   committed) cannot recur silently.
4. The ``--no-citation-chain`` flag plumbed through ``main()`` to
   ``_generate_all(chain_citations=False)`` so the opt-out actually
   skips the chain.

A regression on any of these would re-open the original bug where a
clean working tree could become 13 files dirty just by running
``generate-evidence-packs`` locally.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from splunk_uc.generators import evidence_packs


class _FakeScript:
    """Lightweight stand-in for ``evidence_packs._DOC_REFS_SCRIPT``.

    A real ``pathlib.Path`` cannot be monkey-patched at the attribute
    level (``Path.exists`` is read-only on instances), so the tests
    redirect the module constant to one of these instead.  ``exists``
    is parameterised; ``__fspath__`` / ``__str__`` keep the fake
    interoperable with ``subprocess`` argv construction.
    """

    def __init__(self, *, exists: bool, path: str = "/tmp/fake_doc_refs.py"):
        self._exists = exists
        self._path = path

    def exists(self) -> bool:
        return self._exists

    def __fspath__(self) -> str:
        return self._path

    def __str__(self) -> str:
        return self._path


# ──────────────────────────────────────────────────────────────────────
# _chain_doc_references — happy path
# ──────────────────────────────────────────────────────────────────────


def test_chain_invokes_doc_references_with_expected_args(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The helper shells out to scripts/generate_doc_references.py with
    ``--only docs/evidence-packs/*.md`` and the repo root as cwd."""
    calls: list[dict] = []

    def fake_run(cmd, cwd=None, **kwargs):  # type: ignore[no-untyped-def]
        calls.append({"cmd": cmd, "cwd": cwd, "kwargs": kwargs})
        return subprocess.CompletedProcess(args=cmd, returncode=0)

    fake_script = _FakeScript(exists=True)
    monkeypatch.setattr(evidence_packs, "_DOC_REFS_SCRIPT", fake_script)
    monkeypatch.setattr(subprocess, "run", fake_run)

    rc = evidence_packs._chain_doc_references()
    assert rc == 0
    assert len(calls) == 1
    cmd = calls[0]["cmd"]
    assert cmd[0] == sys.executable
    assert cmd[1] == str(fake_script)
    assert cmd[2] == "--only"
    assert cmd[3] == evidence_packs._EVIDENCE_PACK_GLOB
    assert calls[0]["cwd"] == str(evidence_packs.ROOT)


# ──────────────────────────────────────────────────────────────────────
# _chain_doc_references — missing-script degradation
# ──────────────────────────────────────────────────────────────────────


def test_chain_missing_script_warns_and_returns_zero(
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """When scripts/generate_doc_references.py is absent the helper
    must print a warning to stderr and exit 0 — the evidence-pack body
    is already written and the caller should not treat a stripped-down
    deployment as a build failure."""

    def fake_run(*_args, **_kwargs):  # type: ignore[no-untyped-def]
        pytest.fail("subprocess.run must not be called when script is missing")

    monkeypatch.setattr(
        evidence_packs, "_DOC_REFS_SCRIPT", _FakeScript(exists=False)
    )
    monkeypatch.setattr(subprocess, "run", fake_run)

    rc = evidence_packs._chain_doc_references()
    assert rc == 0
    err = capsys.readouterr().err
    assert "generate_doc_references.py not found" in err
    assert "--no-citation-chain" in err


# ──────────────────────────────────────────────────────────────────────
# _chain_doc_references — failure propagation
# ──────────────────────────────────────────────────────────────────────


def test_chain_propagates_non_zero_exit(
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """If the citation generator fails the parent must surface a hard
    error so callers (and CI) see the regression."""

    def fake_run(cmd, cwd=None, **_kwargs):  # type: ignore[no-untyped-def]
        return subprocess.CompletedProcess(args=cmd, returncode=2)

    monkeypatch.setattr(
        evidence_packs, "_DOC_REFS_SCRIPT", _FakeScript(exists=True)
    )
    monkeypatch.setattr(subprocess, "run", fake_run)

    rc = evidence_packs._chain_doc_references()
    assert rc == 2
    err = capsys.readouterr().err
    assert "exit 2" in err


# ──────────────────────────────────────────────────────────────────────
# CLI flag plumbing
# ──────────────────────────────────────────────────────────────────────


@pytest.mark.parametrize(
    "argv, expected_chain",
    [
        ([], True),
        (["--check"], True),
        (["--no-citation-chain"], False),
        (["--check", "--no-citation-chain"], False),
    ],
)
def test_main_flag_plumbing_passes_chain_kwarg(
    monkeypatch: pytest.MonkeyPatch,
    argv: list[str],
    expected_chain: bool,
) -> None:
    """``main()`` must translate ``--no-citation-chain`` into
    ``_generate_all(chain_citations=False)`` and otherwise default to
    ``chain_citations=True``."""
    captured: dict[str, object] = {}

    def fake_generate_all(*, check: bool, chain_citations: bool = True) -> int:
        captured["check"] = check
        captured["chain_citations"] = chain_citations
        return 0

    monkeypatch.setattr(evidence_packs, "_generate_all", fake_generate_all)

    rc = evidence_packs.main(argv)
    assert rc == 0
    assert captured["chain_citations"] is expected_chain
    assert captured["check"] is ("--check" in argv)


# ──────────────────────────────────────────────────────────────────────
# Path constants — defend against accidental drift
# ──────────────────────────────────────────────────────────────────────


def test_doc_refs_script_path_resolves_under_repo_root() -> None:
    """The constant must point at the canonical citation generator
    location.  Drift here is the single most common way the chain
    silently breaks (script gets moved, helper keeps pointing at the
    old path)."""
    expected = (Path(__file__).resolve().parents[2]
                / "scripts" / "generate_doc_references.py")
    assert evidence_packs._DOC_REFS_SCRIPT == expected


def test_evidence_pack_glob_is_canonical() -> None:
    """The ``--only`` glob must target every markdown file the
    evidence-pack generator owns — packs + README — and nothing else.
    """
    assert evidence_packs._EVIDENCE_PACK_GLOB == "docs/evidence-packs/*.md"
