"""Unit tests for the citation-marker stripping in
``src/splunk_uc/generators/evidence_packs.py``.

Background — why this test exists
=================================

Two CI generators write into ``docs/evidence-packs/``:

1. ``generate-evidence-packs`` (this module) renders one markdown pack
   per regulation plus a ``README.md`` index. Its ``--check`` mode
   byte-compares the planned output against the on-disk file.

2. ``scripts/generate_doc_references.py`` walks every markdown file in
   the repository and:
   *  injects inline ``<sup class="ref">[<a href="#ref-N">N</a>]</sup>``
      citation markers at first mention of curated phrases
      (``data/inline-citation-phrases.json``), and
   *  appends an APA-formatted References section between
      ``<!-- BEGIN-AUTOGENERATED-SOURCES -->`` /
      ``<!-- END-AUTOGENERATED-SOURCES -->`` sentinels.

Both generators run in the same ``validate.yml`` lane. Without
defensive stripping the second generator's edits would surface as
``DRIFT DETECTED`` from the first generator's ``--check`` even though
the citation markers and References footer are bookkeeping that the
evidence-pack generator does not own and should not police.

These tests pin three contracts:

1. Inline ``<sup class="ref">`` markers are stripped from arbitrary
   text without touching the surrounding prose.
2. The full ``BEGIN-AUTOGENERATED-SOURCES`` block — including the
   leading ``---`` separator and any flanking blank lines that
   ``generate_doc_references.py`` writes — is consumed.
3. A planned payload that never contained any citation system markup
   passes through ``_strip_citation_markers`` byte-identical (modulo
   the canonical single trailing newline that the helper enforces).

A regression on any of these would cause a flood of false-positive
drift on ``generate-evidence-packs --check`` and re-introduce the CI
failure that motivated the helper in the first place.
"""

from __future__ import annotations

import pytest

from splunk_uc.generators.evidence_packs import _strip_citation_markers


# ──────────────────────────────────────────────────────────────────────
# Inline citation markers
# ──────────────────────────────────────────────────────────────────────


def test_strip_inline_marker_single_digit() -> None:
    payload = (
        b"- **UC-17.1.82** \xe2\x80\x94 Splunk SOAR"
        b'<sup class="ref">[<a href="#ref-8">8</a>]</sup>'
        b" + ISE Closed-Loop Playbook\n"
    )
    stripped = _strip_citation_markers(payload)
    expected = (
        b"- **UC-17.1.82** \xe2\x80\x94 Splunk SOAR + ISE Closed-Loop Playbook\n"
    )
    assert stripped == expected


def test_strip_inline_marker_multi_digit() -> None:
    payload = (
        b"**SOC 2"
        b'<sup class="ref">[<a href="#ref-123">123</a>]</sup>'
        b"** | Tier 1 | US | `2017 TSC` | 100.0%\n"
    )
    stripped = _strip_citation_markers(payload)
    assert stripped == b"**SOC 2** | Tier 1 | US | `2017 TSC` | 100.0%\n"


def test_strip_multiple_inline_markers_same_line() -> None:
    payload = (
        b'A<sup class="ref">[<a href="#ref-1">1</a>]</sup> '
        b'B<sup class="ref">[<a href="#ref-2">2</a>]</sup> C\n'
    )
    assert _strip_citation_markers(payload) == b"A B C\n"


def test_no_marker_preserved_modulo_trailing_newline() -> None:
    # Plain markdown with one trailing newline must pass through
    # byte-identical — modulo the helper's canonical-newline guard.
    payload = b"Plain markdown text with no marker.\n"
    assert _strip_citation_markers(payload) == payload


def test_no_marker_no_trailing_newline_is_normalised() -> None:
    # The planned generator output always ends with exactly one ``\n``.
    # _strip_citation_markers re-adds that newline if the strip
    # consumed it, so a trailing-newline-free payload must still come
    # out with one trailing newline.
    payload = b"No trailing newline"
    assert _strip_citation_markers(payload) == b"No trailing newline\n"


# ──────────────────────────────────────────────────────────────────────
# Auto-generated References block
# ──────────────────────────────────────────────────────────────────────


def test_strip_references_block_with_separator() -> None:
    # Mirrors ``rebuild()`` in scripts/generate_doc_references.py
    # when it appends to a doc that had no prior footer.
    payload = (
        b"# Evidence pack body\n"
        b"\n"
        b"Some prose.\n"
        b"\n"
        b"---\n"
        b"\n"
        b"<!-- BEGIN-AUTOGENERATED-SOURCES -->\n"
        b"## References\n"
        b"<a id='ref-1'></a>**[1]** Source one.\n"
        b"<!-- END-AUTOGENERATED-SOURCES -->\n"
    )
    stripped = _strip_citation_markers(payload)
    assert b"BEGIN-AUTOGENERATED-SOURCES" not in stripped
    assert b"END-AUTOGENERATED-SOURCES" not in stripped
    assert b"## References" not in stripped
    # Body prose survives.
    assert b"# Evidence pack body" in stripped
    assert b"Some prose." in stripped
    # Exactly one trailing newline (canonical form).
    assert stripped.endswith(b"\n")
    assert not stripped.endswith(b"\n\n")


def test_strip_references_block_without_separator() -> None:
    # Some docs were written before the ``\n---\n`` separator
    # convention. The regex must still consume the block alone.
    payload = (
        b"# Body\n"
        b"\n"
        b"<!-- BEGIN-AUTOGENERATED-SOURCES -->\n"
        b"## References\n"
        b"<!-- END-AUTOGENERATED-SOURCES -->\n"
    )
    stripped = _strip_citation_markers(payload)
    assert b"BEGIN-AUTOGENERATED-SOURCES" not in stripped
    assert stripped.startswith(b"# Body\n")


# ──────────────────────────────────────────────────────────────────────
# Combined stripping — the realistic CI scenario
# ──────────────────────────────────────────────────────────────────────


def test_combined_marker_and_block_strip() -> None:
    payload = (
        b"- **UC-1.2.3**"
        b'<sup class="ref">[<a href="#ref-7">7</a>]</sup>'
        b" \xe2\x80\x94 Sample UC line\n"
        b"\n"
        b"More body.\n"
        b"\n"
        b"---\n"
        b"\n"
        b"<!-- BEGIN-AUTOGENERATED-SOURCES -->\n"
        b"## References\n"
        b"<!-- END-AUTOGENERATED-SOURCES -->\n"
    )
    stripped = _strip_citation_markers(payload)
    assert b'<sup class="ref">' not in stripped
    assert b"BEGIN-AUTOGENERATED-SOURCES" not in stripped
    assert stripped.startswith(b"- **UC-1.2.3** \xe2\x80\x94")
    assert b"More body." in stripped


@pytest.mark.parametrize(
    "marker_html",
    [
        b'<sup class="ref">[<a href="#ref-1">1</a>]</sup>',
        b'<sup class="ref">[<a href="#ref-99">99</a>]</sup>',
        b'<sup class="ref">[<a href="#ref-1000">1000</a>]</sup>',
    ],
)
def test_marker_regex_handles_any_ref_number(marker_html: bytes) -> None:
    payload = b"Word" + marker_html + b" continues.\n"
    assert _strip_citation_markers(payload) == b"Word continues.\n"
